ZVEADMP ;VE;Admin Domain RPC Probe + Full RPC Catalog Extract;2026-03-09
 ;
 ; Phase MP2: Comprehensive VistA introspection for admin domain mapping
 ; Outputs: (1) Full RPC count, (2) Per-namespace RPC counts, (3) Admin domain RPC availability
 ;
CATALOG ;Extract full RPC catalog from ^XWB(8994) as pipe-delimited lines
 N NAME,IEN,CT
 S CT=0
 S NAME=""
 F  S NAME=$O(^XWB(8994,"B",NAME)) Q:NAME=""  D
 . S IEN=$O(^XWB(8994,"B",NAME,""))
 . S CT=CT+1
 . W IEN,"|",NAME,!
 W "TOTAL_RPC_COUNT|",CT,!
 Q
 ;
NSCOUNT ;Count RPCs by namespace prefix (first word or 2-3 char prefix)
 N NAME,IEN,NS,CT,NSCNT
 S NAME=""
 F  S NAME=$O(^XWB(8994,"B",NAME)) Q:NAME=""  D
 . S NS=$P(NAME," ",1)
 . I $L(NS)>8 S NS=$E(NS,1,4)_"..."
 . S NSCNT(NS)=$G(NSCNT(NS))+1
 S NS=""
 F  S NS=$O(NSCNT(NS)) Q:NS=""  D
 . W NS,"|",NSCNT(NS),!
 Q
 ;
ADMIN ;Probe admin-relevant RPCs across 12 domains
 N NAME,IEN,LIST,I
 W "=== DOMAIN 1: SYSTEM INFRASTRUCTURE (Kernel/XU) ===",!
 S LIST(1)="XUS SIGNON SETUP"
 S LIST(2)="XUS AV CODE"
 S LIST(3)="XUS SET VISITOR"
 S LIST(4)="XUS GET USER INFO"
 S LIST(5)="XUS DIVISION GET"
 S LIST(6)="XUS DIVISION SET"
 S LIST(7)="XUS PKI GET UPN"
 S LIST(8)="XUS GET TOKEN"
 S LIST(9)="XUS INTRO MSG"
 S LIST(10)="XWB GET BROKER INFO"
 S LIST(11)="XWB IM HERE"
 S LIST(12)="XWB ARE YOU THERE"
 S LIST(13)="XWB CREATE CONTEXT"
 S LIST(14)="XWB GET VARIABLE VALUE"
 S LIST(15)="ORWU NEWPERS"
 S LIST(16)="ORWU USERINFO"
 S LIST(17)="ORWU DT"
 S LIST(18)="ORWU TOOLMENU"
 S LIST(19)="ORWU VALIDSIG"
 S LIST(20)="ORWU VERSRV"
 S LIST(21)="ORWU EXTNAME"
 S LIST(22)="ORWU HASKEY"
 S LIST(23)="ORWU PARAM"
 F I=1:1:23 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 2: FACILITY SETUP (DG/Registration) ===",!
 S LIST(1)="DG CHK PAT/DIV MEANS TEST"
 S LIST(2)="DG SENSITIVE RECORD ACCESS"
 S LIST(3)="DG SENSITIVE RECORD BULLETIN"
 S LIST(4)="DG REGISTRATION DEMOGRAPHIC"
 S LIST(5)="VBECS ADT EVENTS"
 S LIST(6)="ORWU CLINLOC"
 S LIST(7)="ORWU1 NAMECVT"
 S LIST(8)="ORWU GENERIC"
 F I=1:1:8 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 3: SCHEDULING (SD/SDES) ===",!
 S LIST(1)="SDES GET APPT TYPES"
 S LIST(2)="SDES GET APPT BY APPT IEN"
 S LIST(3)="SDES CANCEL APPOINTMENT"
 S LIST(4)="SDES GET CANCEL REASONS"
 S LIST(5)="SDES GET CLINIC DETAILS"
 S LIST(6)="SDES GET CLINIC RESOURCES"
 S LIST(7)="SDES GET CLINIC AVAILABILITY"
 S LIST(8)="SDES HELD APPOINTMENT"
 S LIST(9)="SDES BOOKED APPOINTMENT"
 S LIST(10)="SDES CREATE APPOINTMENT"
 S LIST(11)="SD WAIT LIST"
 S LIST(12)="SDOE LIST ENCOUNTERS FOR PAT"
 S LIST(13)="SDVW RESOURCE"
 S LIST(14)="SDVW APPTBYDT"
 S LIST(15)="SD W/L CLINICS"
 S LIST(16)="SDEC APPADD"
 S LIST(17)="SDEC APPDEL"
 S LIST(18)="SDEC CLINLET"
 F I=1:1:18 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 4: INPATIENT / ADT ===",!
 S LIST(1)="DGPM NEW ADMISSION"
 S LIST(2)="DGPM NEW TRANSFER"
 S LIST(3)="DGPM NEW DISCHARGE"
 S LIST(4)="DG ADT DISCHARGE"
 S LIST(5)="ORWPT ADMITLST"
 S LIST(6)="ORWPT CLINRNG"
 S LIST(7)="ORWPT BYWARD"
 S LIST(8)="ORWPT LAST5"
 F I=1:1:8 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 5: PHARMACY (PSO/PSJ/PSS/PSN) ===",!
 S LIST(1)="PSS DRUG LIST"
 S LIST(2)="PSS ORDER"
 S LIST(3)="PSO ACTIVE LIST"
 S LIST(4)="PSJ LM ORDER UPDATE"
 S LIST(5)="PSO UPDATE MED LIST"
 S LIST(6)="PSB ALLERGY"
 S LIST(7)="PSB VALIDATE ORDER"
 S LIST(8)="ORWPS ACTIVE"
 S LIST(9)="ORWPS DETAIL"
 S LIST(10)="ORWDPS32 AUTH"
 S LIST(11)="ORWDPS32 VALQTY"
 S LIST(12)="ORWDPS32 SCSTS"
 S LIST(13)="ORWDPS1 FAESSION"
 F I=1:1:13 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 6: LABORATORY (LR) ===",!
 S LIST(1)="ORWLRR ALLTESTS"
 S LIST(2)="ORWLRR CHART"
 S LIST(3)="ORWLRR GRID"
 S LIST(4)="ORWLRR INTERIM"
 S LIST(5)="ORWLRR INTERIMG"
 S LIST(6)="ORWLRR SPEC"
 S LIST(7)="ORWLRR USERS"
 S LIST(8)="LR ORDER"
 S LIST(9)="LR VERIFY"
 F I=1:1:9 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 7: RADIOLOGY (RA/MAG) ===",!
 S LIST(1)="ORWDXR NEW ORDER"
 S LIST(2)="RA EXAM STATUS"
 S LIST(3)="MAG4 ADD IMAGE"
 S LIST(4)="MAG4 GET IMAGE INFO"
 S LIST(5)="MAG DICOM QUERY RETRIEVE"
 S LIST(6)="ORWRA IMAGING EXAMS"
 F I=1:1:6 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 8: BILLING / IB / AR ===",!
 S LIST(1)="IBD SCANCODE"
 S LIST(2)="IBD SCAN ALL"
 S LIST(3)="IB PT STATUS"
 S LIST(4)="IBCN INSUR DATA"
 S LIST(5)="IBCN INSURANCE"
 S LIST(6)="IBARXMK MARKUP"
 S LIST(7)="IBARXMG GETDATA"
 S LIST(8)="IBARXMS STATS"
 S LIST(9)="DGBT CLAIM STATUS"
 F I=1:1:9 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 9: INVENTORY / IFCAP ===",!
 S LIST(1)="PRC ITEM INQUIRY"
 S LIST(2)="PRC PURCHASE ORDER"
 F I=1:1:2 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 10: WORKFORCE / PAID ===",!
 S LIST(1)="PRS EMPLOYEE"
 F I=1:1:1 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 11: QUALITY / REMINDERS ===",!
 S LIST(1)="PXRM REMINDERS"
 S LIST(2)="ORQQPX NEW REMINDERS"
 S LIST(3)="ORQQPX REMINDER DETAIL"
 F I=1:1:3 D CHKRPC(LIST(I))
 ;
 W !,"=== DOMAIN 12: CLINICAL APP SETUP ===",!
 S LIST(1)="ORWDXM MENU"
 S LIST(2)="ORWDX WRLST"
 S LIST(3)="ORWORDG IEN"
 S LIST(4)="ORWOR SHEETS"
 S LIST(5)="ORWTIU GET LISTBOX"
 S LIST(6)="TIU TEMPLATE GETITEMS"
 S LIST(7)="TIU GET TEMPLATE TEXT"
 S LIST(8)="GMRC LIST CONSULT REQUESTS"
 S LIST(9)="TIU CREATE RECORD"
 S LIST(10)="TIU SET DOCUMENT TEXT"
 S LIST(11)="ORWDXM DLGORD"
 S LIST(12)="GMPL LIST"
 F I=1:1:12 D CHKRPC(LIST(I))
 ;
 W !,"=== DONE ===",!
 Q
 ;
CHKRPC(NAME) ;Check single RPC in File 8994
 N IEN
 S IEN=$O(^XWB(8994,"B",NAME,""))
 I IEN W "  FOUND  |",IEN,"|",NAME,!
 I 'IEN W "  MISSING|---|",NAME,!
 Q
 ;
COUNT ;Count total RPCs in File 8994
 N CT,X
 S CT=0,X=""
 F  S X=$O(^XWB(8994,"B",X)) Q:X=""  S CT=CT+1
 W "TOTAL_RPCS:",CT,!
 Q
 ;
FILEMAN ;Extract key FileMan file data dictionaries
 N FILE,FILES,I,FNAME,U
 S U="^"
 S FILES(1)=200
 S FILES(2)=44
 S FILES(3)=42
 S FILES(4)=4
 S FILES(5)=40.8
 S FILES(6)=49
 S FILES(7)=50
 S FILES(8)=60
 S FILES(9)=71
 S FILES(10)=350.9
 S FILES(11)=19
 S FILES(12)=19.1
 S FILES(13)=8989.3
 S FILES(14)=8994
 S FILES(15)=100
 S FILES(16)=101
 S FILES(17)=8925.1
 S FILES(18)=123.5
 S FILES(19)=409.1
 S FILES(20)=40.7
 S FILES(21)=42.4
 S FILES(22)=355.3
 S FILES(23)=399
 F I=1:1:23 D
 . S FILE=FILES(I)
 . S FNAME=$G(^DIC(FILE,0,"GL"))
 . I FNAME="" S FNAME="(not found)"
 . W "FILE|",FILE,"|",$P($G(^DIC(FILE,0)),U,1),"|",FNAME,"|RECORDS:",$P($G(^DIC(FILE,0)),U,4),!
 Q
