ZVECTX ;VE;Add admin RPCs to OR CPRS GUI CHART context;2026-03-09
 ;
 ; Adds all VE admin RPCs to the OR CPRS GUI CHART context.
 ; Uses the safe append pattern from VEMCTX3 -- never KILLs.
 ;
 N CTXIEN,RPCIEN,RPCNM,NAMES,I,MAXSUB,SUBIEN,FOUND,NEXT,HDR,EXISTCT,ADDEDCT,TOTALCT
 ;
 S CTXIEN=$$FIND1^DIC(19,,"B","OR CPRS GUI CHART")
 I CTXIEN<1 W "ERROR: OR CPRS GUI CHART not found",! Q
 W "Context IEN: ",CTXIEN,!
 ;
 S MAXSUB=0,SUBIEN=""
 F  S SUBIEN=$O(^DIC(19,CTXIEN,"RPC",SUBIEN)) Q:SUBIEN=""  D
 . Q:SUBIEN'=+SUBIEN
 . I SUBIEN>MAXSUB S MAXSUB=SUBIEN
 W "Current max sub-IEN: ",MAXSUB,!
 ;
 S EXISTCT=0,SUBIEN=0
 F  S SUBIEN=$O(^DIC(19,CTXIEN,"RPC",SUBIEN)) Q:SUBIEN=""  D
 . Q:SUBIEN'=+SUBIEN
 . S EXISTCT=EXISTCT+1
 W "Existing entries: ",EXISTCT,!
 ;
 ; --- Original read RPCs ---
 S NAMES="VE USER LIST,VE USER DETAIL,VE KEY LIST,VE MENU LIST"
 S NAMES=NAMES_",VE INST LIST,VE DIV LIST,VE SVC LIST,VE STOP LIST,VE SPEC LIST,VE SITE PARM"
 S NAMES=NAMES_",VE CLIN LIST,VE CLIN DETAIL,VE APPT TYPES"
 S NAMES=NAMES_",VE WARD LIST,VE WARD DETAIL,VE CENSUS"
 S NAMES=NAMES_",VE DRUG LIST,VE DRUG DETAIL,VE MED ROUTES,VE MED SCHEDULES"
 S NAMES=NAMES_",VE LAB TEST LIST,VE LAB TEST DETAIL,VE LAB COLL SAMP,VE LAB URGENCY"
 S NAMES=NAMES_",VE IB SITE,VE INS LIST,VE INS DETAIL,VE CLAIM COUNT"
 ;
 ; --- Write RPCs (ZVEUSER) ---
 S NAMES=NAMES_",VE USER EDIT,VE USER ADD KEY,VE USER REMOVE KEY"
 S NAMES=NAMES_",VE USER DEACTIVATE,VE USER REACTIVATE"
 ;
 ; --- Write RPCs (ZVECLIN) ---
 S NAMES=NAMES_",VE CLIN CREATE,VE CLIN EDIT,VE CLIN TOGGLE"
 ;
 ; --- Write RPCs (ZVEWARD) ---
 S NAMES=NAMES_",VE WARD EDIT"
 ;
 ; --- Write RPCs (ZVEFAC) ---
 S NAMES=NAMES_",VE SVC CREATE,VE SVC EDIT"
 ;
 ; --- Write RPCs (ZVEPHAR) ---
 S NAMES=NAMES_",VE DRUG EDIT"
 ;
 ; --- Write RPCs (ZVELAB) ---
 S NAMES=NAMES_",VE LAB TEST EDIT"
 ;
 ; --- Write RPCs (ZVEBILL) ---
 S NAMES=NAMES_",VE INS CREATE,VE INS EDIT"
 ;
 ; --- System admin RPCs (ZVESYS) ---
 S NAMES=NAMES_",VE TASKMAN LIST,VE ERROR TRAP,VE SYS STATUS"
 S NAMES=NAMES_",VE PARAM LIST,VE PARAM EDIT"
 ;
 ; --- Radiology RPCs (ZVERAD) ---
 S NAMES=NAMES_",VE RAD PROC LIST,VE RAD PROC DETAIL"
 S NAMES=NAMES_",VE RAD IMG LOCATIONS,VE RAD DIV PARAMS"
 ;
 ; --- Inventory RPCs (ZVEINV) ---
 S NAMES=NAMES_",VE INV ITEM LIST,VE INV ITEM DETAIL"
 S NAMES=NAMES_",VE INV VENDOR LIST,VE INV PO LIST"
 ;
 ; --- Workforce RPCs (ZVEWRKF) ---
 S NAMES=NAMES_",VE PROV LIST,VE PROV DETAIL,VE PERSON CLASS LIST"
 ;
 ; --- Quality RPCs (ZVEQUAL) ---
 S NAMES=NAMES_",VE REMINDER LIST,VE REMINDER DETAIL,VE QA SITE PARAMS"
 ;
 ; --- Clinical app setup RPCs (ZVECAPP) ---
 S NAMES=NAMES_",VE ORDER SETS,VE CONSULT SERVICES"
 S NAMES=NAMES_",VE TIU DEFINITIONS,VE TIU TEMPLATES,VE HEALTH SUMMARY TYPES"
 ;
 S NEXT=MAXSUB
 S ADDEDCT=0
 ;
 F I=1:1:$L(NAMES,",") D
 . S RPCNM=$P(NAMES,",",I)
 . S RPCIEN=$$FIND1^DIC(8994,,"B",RPCNM)
 . I RPCIEN<1 W "  SKIP: ",RPCNM," not registered",! Q
 . S FOUND=0,SUBIEN=0
 . F  S SUBIEN=$O(^DIC(19,CTXIEN,"RPC",SUBIEN)) Q:SUBIEN=""  D
 . . Q:SUBIEN'=+SUBIEN
 . . I +$G(^DIC(19,CTXIEN,"RPC",SUBIEN,0))=RPCIEN S FOUND=1
 . I FOUND W "  ALREADY: ",RPCNM,!  Q
 . S NEXT=NEXT+1
 . S ^DIC(19,CTXIEN,"RPC",NEXT,0)=RPCIEN
 . S ^DIC(19,CTXIEN,"RPC","B",RPCIEN,NEXT)=""
 . S ADDEDCT=ADDEDCT+1
 . W "  ADDED: ",RPCNM," (IEN=",RPCIEN,") sub=",NEXT,!
 ;
 S TOTALCT=EXISTCT+ADDEDCT
 S HDR=$G(^DIC(19,CTXIEN,"RPC",0))
 I HDR="" S HDR="^19.05PA^"_NEXT_"^"_NEXT
 E  S $P(HDR,"^",3)=NEXT,$P(HDR,"^",4)=TOTALCT
 S ^DIC(19,CTXIEN,"RPC",0)=HDR
 W !,"Added ",ADDEDCT," RPCs. Total: ",TOTALCT,!
 Q
