ZVECLIN ;VE;Clinic Setup Admin RPCs;2026-03-09
 ;
 ; Custom RPCs for File #44 (HOSPITAL LOCATION) clinic admin operations.
 ; Read RPCs: CLINLIST, CLINDET, APTTYPES
 ; Write RPCs: CLINCRT, CLINEDT, CLINTOGL
 ;
CLINLIST(RESULT,SEARCH,COUNT) ;List clinics from File #44
 N IEN,NM,I,U,MAXCT,TYPE
 S U="^",I=0,MAXCT=+$G(COUNT)
 I MAXCT<1 S MAXCT=200
 I MAXCT>1000 S MAXCT=1000
 S SEARCH=$G(SEARCH)
 I SEARCH'="" D  Q
 . S NM=SEARCH
 . F  S NM=$O(^SC("B",NM)) Q:NM=""  Q:$E(NM,1,$L(SEARCH))'=SEARCH  Q:I>=MAXCT  D
 . . S IEN=$O(^SC("B",NM,""))
 . . Q:'IEN
 . . S TYPE=$P($G(^SC(IEN,0)),U,3)
 . . Q:TYPE'="C"  ; Only clinics
 . . S I=I+1
 . . D CLINLN
 . S RESULT(0)=I
 S IEN=0
 F  S IEN=$O(^SC(IEN)) Q:'IEN  Q:I>=MAXCT  D
 . S NM=$P($G(^SC(IEN,0)),U,1)
 . Q:NM=""
 . S TYPE=$P($G(^SC(IEN,0)),U,3)
 . Q:TYPE'="C"
 . S I=I+1
 . D CLINLN
 S RESULT(0)=I
 Q
 ;
CLINLN ;Build clinic list line (called with IEN, I set)
 N Z0,SVC,STOP,PROV,APPTLEN
 S Z0=$G(^SC(IEN,0))
 S SVC=$P(Z0,U,4)
 S STOP=$P(Z0,U,7)
 S APPTLEN=$P(Z0,U,9)
 S PROV=$P($G(^SC(IEN,"PROV")),U,1)
 S RESULT(I)=IEN_U_$P(Z0,U,1)_U_$P(Z0,U,2)_U_SVC_U_STOP_U_APPTLEN_U_PROV_U_$$CLINACT(IEN)
 Q
 ;
CLINDET(RESULT,CLINIEN) ;Get detailed clinic info from File #44
 N U,Z0,I
 S U="^",CLINIEN=+$G(CLINIEN)
 I 'CLINIEN S RESULT(0)="-1^Clinic IEN required" Q
 I '$D(^SC(CLINIEN,0)) S RESULT(0)="-1^Clinic not found" Q
 S Z0=^SC(CLINIEN,0)
 S RESULT(0)="1^OK"
 S RESULT(1)="IEN^"_CLINIEN
 S RESULT(2)="NAME^"_$P(Z0,U,1)
 S RESULT(3)="ABBREVIATION^"_$P(Z0,U,2)
 S RESULT(4)="TYPE^"_$P(Z0,U,3)
 S RESULT(5)="SERVICE^"_$P(Z0,U,4)
 S RESULT(6)="TREATING_SPEC^"_$P(Z0,U,5)
 S RESULT(7)="STOP_CODE^"_$P(Z0,U,7)
 S RESULT(8)="APPT_LENGTH^"_$P(Z0,U,9)
 S RESULT(9)="DISPLAY_INCR^"_$P(Z0,U,19)
 S RESULT(10)="OVERBOOKS_DAY^"_$P(Z0,U,23)
 S RESULT(11)="MAX_OVERBOOKS^"_$P(Z0,U,24)
 S RESULT(12)="DEFAULT_PROVIDER^"_$P($G(^SC(CLINIEN,"PROV")),U,1)
 S RESULT(13)="INACTIVATE_DATE^"_$P($G(^SC(CLINIEN,"I")),U,1)
 S RESULT(14)="REACTIVATE_DATE^"_$P($G(^SC(CLINIEN,"I")),U,2)
 S RESULT(15)="TELEPHONE^"_$P($G(^SC(CLINIEN,.1)),U,1)
 S RESULT(16)="CLINIC_DIVISION^"_$P($G(^SC(CLINIEN,0)),U,15)
 Q
 ;
APTTYPES(RESULT) ;List appointment types from File #409.1
 N IEN,NM,I,U
 S U="^",I=0,IEN=0
 F  S IEN=$O(^SD(409.1,IEN)) Q:'IEN  D
 . S NM=$P($G(^SD(409.1,IEN,0)),U,1)
 . Q:NM=""
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^SD(409.1,IEN,0)),U,2)
 S RESULT(0)=I
 Q
 ;
CLINACT(IEN) ;Is clinic active?
 N INACT
 S INACT=$P($G(^SC(IEN,"I")),U,1)
 I INACT'="",$P($G(^SC(IEN,"I")),U,2)="" Q "INACTIVE"
 Q "ACTIVE"
 ;
CLINCRT(RESULT,NAME,ABBREV,SERVICE,STOPCODE,APPTLEN) ;Create clinic in File #44
 ; Uses DIC to create entry (UPDATE^DIE fails with File #44 identifier issue)
 ; then FILE^DIE to set remaining fields
 ; VEHU File #44 field map: 1=ABBREVIATION, 2=TYPE, 8=STOP CODE, 9=SERVICE,
 ;   1912=LENGTH OF APPT, 99=TELEPHONE, 1917=DISPLAY INCR, 1918=OVERBOOKS/DAY
 N U,DIC,DA,X,Y,DLAYGO,FDA,IENS,ERR
 S U="^"
 S NAME=$G(NAME),ABBREV=$G(ABBREV)
 S SERVICE=$G(SERVICE),STOPCODE=$G(STOPCODE),APPTLEN=$G(APPTLEN)
 I NAME="" S RESULT(0)="-1^Clinic name required" Q
 I ABBREV="" S ABBREV=$E(NAME,1,5)
 I APPTLEN<1 S APPTLEN=30
 ; Step 1: Create the entry via DIC
 S DIC="^SC(",DIC(0)="L",X=NAME,DLAYGO=44
 D ^DIC
 I +Y<1 S RESULT(0)="-1^Failed to create clinic: "_$G(Y) Q
 S DA=+Y
 ; Step 2: Set remaining fields via FILE^DIE
 S IENS=DA_","
 S FDA(44,IENS,1)=ABBREV
 S FDA(44,IENS,2)="C"
 I SERVICE'="" S FDA(44,IENS,9)=SERVICE
 I STOPCODE'="" S FDA(44,IENS,8)=STOPCODE
 S FDA(44,IENS,1912)=APPTLEN
 D FILE^DIE("E","FDA","ERR")
 I $D(ERR) S RESULT(0)="-1^Created IEN "_DA_" but field update failed: "_$G(ERR("DIERR",1,"TEXT",1)) Q
 S RESULT(0)="1^OK"
 S RESULT(1)="IEN^"_DA
 S RESULT(2)="NAME^"_NAME
 Q
 ;
CLINEDT(RESULT,CLINIEN,FIELD,VALUE) ;Edit clinic fields in File #44
 ; VEHU File #44 field map: 1=ABBREVIATION, 2=TYPE, 8=STOP CODE, 9=SERVICE,
 ;   1912=LENGTH OF APPT, 99=TELEPHONE, 1917=DISPLAY INCR, 1918=OVERBOOKS/DAY
 N U,FDA,IENS,ERR,FLDNUM
 S U="^",CLINIEN=+$G(CLINIEN)
 I 'CLINIEN S RESULT(0)="-1^Clinic IEN required" Q
 I '$D(^SC(CLINIEN,0)) S RESULT(0)="-1^Clinic not found" Q
 S FIELD=$G(FIELD),VALUE=$G(VALUE)
 I FIELD="" S RESULT(0)="-1^Field name required" Q
 S FLDNUM=""
 I FIELD="NAME" S FLDNUM=.01
 I FIELD="ABBREVIATION" S FLDNUM=1
 I FIELD="SERVICE" S FLDNUM=9
 I FIELD="STOP_CODE" S FLDNUM=8
 I FIELD="APPT_LENGTH" S FLDNUM=1912
 I FIELD="DISPLAY_INCR" S FLDNUM=1917
 I FIELD="OVERBOOKS_DAY" S FLDNUM=1918
 I FIELD="TELEPHONE" S FLDNUM=99
 I FLDNUM="" S RESULT(0)="-1^Unknown field: "_FIELD Q
 S IENS=CLINIEN_","
 S FDA(44,IENS,FLDNUM)=VALUE
 D FILE^DIE("E","FDA","ERR")
 I $D(ERR) S RESULT(0)="-1^"_$G(ERR("DIERR",1,"TEXT",1)) Q
 S RESULT(0)="1^OK"
 Q
 ;
CLINTOGL(RESULT,CLINIEN,ACTION) ;Toggle clinic active/inactive
 ; ACTION = "INACTIVATE" or "REACTIVATE"
 N U,FDA,IENS,ERR,NOW
 S U="^",CLINIEN=+$G(CLINIEN)
 I 'CLINIEN S RESULT(0)="-1^Clinic IEN required" Q
 I '$D(^SC(CLINIEN,0)) S RESULT(0)="-1^Clinic not found" Q
 S ACTION=$G(ACTION)
 I ACTION'="INACTIVATE",ACTION'="REACTIVATE" D  Q
 . S RESULT(0)="-1^ACTION must be INACTIVATE or REACTIVATE"
 S IENS=CLINIEN_","
 S NOW=$$NOW^XLFDT
 I ACTION="INACTIVATE" D
 . S FDA(44,IENS,2505)=NOW
 . S FDA(44,IENS,2506)="@"
 I ACTION="REACTIVATE" D
 . S FDA(44,IENS,2506)=NOW
 D FILE^DIE("K","FDA","ERR")
 I $D(ERR) S RESULT(0)="-1^"_$G(ERR("DIERR",1,"TEXT",1)) Q
 S RESULT(0)="1^OK"
 Q
 ;
INSTALL ;Register RPCs in File #8994
 ; Read RPCs
 D REG^ZVEUSER("VE CLIN LIST","CLINLIST","ZVECLIN")
 D REG^ZVEUSER("VE CLIN DETAIL","CLINDET","ZVECLIN")
 D REG^ZVEUSER("VE APPT TYPES","APTTYPES","ZVECLIN")
 ; Write RPCs
 D REG^ZVEUSER("VE CLIN CREATE","CLINCRT","ZVECLIN")
 D REG^ZVEUSER("VE CLIN EDIT","CLINEDT","ZVECLIN")
 D REG^ZVEUSER("VE CLIN TOGGLE","CLINTOGL","ZVECLIN")
 W "ZVECLIN RPCs registered",!
 Q
