ZVEINV ;VE;Inventory/Supply Chain Admin RPCs;2026-03-09
 ;
 ; Inventory domain RPCs for admin dashboard.
 ; File #441 (ITEM MASTER), File #445 (VENDOR), File #443 (PURCHASE ORDER)
 ;
ITEMLIST(RESULT,SEARCH,COUNT) ;List items from File #441
 N IEN,NM,I,U,MAXCT
 S U="^",I=0,MAXCT=+$G(COUNT)
 I MAXCT<1 S MAXCT=200
 I MAXCT>1000 S MAXCT=1000
 S SEARCH=$G(SEARCH)
 I '$D(^PRC(441)) S RESULT(0)=0 Q
 I SEARCH'="" D  Q
 . S NM=SEARCH
 . F  S NM=$O(^PRC(441,"B",NM)) Q:NM=""  Q:$E(NM,1,$L(SEARCH))'=SEARCH  Q:I>=MAXCT  D
 . . S IEN=$O(^PRC(441,"B",NM,""))
 . . Q:'IEN
 . . S I=I+1
 . . S RESULT(I)=IEN_U_NM_U_$P($G(^PRC(441,IEN,0)),U,2)_U_$P($G(^PRC(441,IEN,0)),U,3)
 . S RESULT(0)=I
 S IEN=0
 F  S IEN=$O(^PRC(441,IEN)) Q:'IEN  Q:I>=MAXCT  D
 . S NM=$P($G(^PRC(441,IEN,0)),U,1)
 . Q:NM=""
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^PRC(441,IEN,0)),U,2)_U_$P($G(^PRC(441,IEN,0)),U,3)
 S RESULT(0)=I
 Q
 ;
ITEMDET(RESULT,ITEMIEN) ;Item detail from File #441
 N U,Z0
 S U="^",ITEMIEN=+$G(ITEMIEN)
 I 'ITEMIEN S RESULT(0)="-1^Item IEN required" Q
 I '$D(^PRC(441,ITEMIEN,0)) S RESULT(0)="-1^Item not found" Q
 S Z0=$G(^PRC(441,ITEMIEN,0))
 S RESULT(0)="1^OK"
 S RESULT(1)="IEN^"_ITEMIEN
 S RESULT(2)="NAME^"_$P(Z0,U,1)
 S RESULT(3)="NSN^"_$P(Z0,U,2)
 S RESULT(4)="UNIT_OF_ISSUE^"_$P(Z0,U,3)
 S RESULT(5)="UNIT_COST^"_$P(Z0,U,4)
 S RESULT(6)="CATEGORY^"_$P($G(^PRC(441,ITEMIEN,1)),U,1)
 S RESULT(7)="VENDOR^"_$P($G(^PRC(441,ITEMIEN,1)),U,2)
 Q
 ;
VENDLIST(RESULT,SEARCH) ;List vendors from File #445
 N IEN,NM,I,U,MAXCT
 S U="^",I=0,MAXCT=200,SEARCH=$G(SEARCH)
 I '$D(^PRC(445)) S RESULT(0)=0 Q
 I SEARCH'="" D  Q
 . S NM=SEARCH
 . F  S NM=$O(^PRC(445,"B",NM)) Q:NM=""  Q:$E(NM,1,$L(SEARCH))'=SEARCH  Q:I>=MAXCT  D
 . . S IEN=$O(^PRC(445,"B",NM,""))
 . . Q:'IEN
 . . S I=I+1
 . . S RESULT(I)=IEN_U_NM_U_$P($G(^PRC(445,IEN,0)),U,2)_U_$P($G(^PRC(445,IEN,.11)),U,1)
 . S RESULT(0)=I
 S IEN=0
 F  S IEN=$O(^PRC(445,IEN)) Q:'IEN  Q:I>=MAXCT  D
 . S NM=$P($G(^PRC(445,IEN,0)),U,1)
 . Q:NM=""
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^PRC(445,IEN,0)),U,2)_U_$P($G(^PRC(445,IEN,.11)),U,1)
 S RESULT(0)=I
 Q
 ;
POLIST(RESULT,COUNT) ;List purchase orders from File #443
 N IEN,NM,I,U,MAXCT,STAT
 S U="^",I=0,MAXCT=+$G(COUNT)
 I MAXCT<1 S MAXCT=100
 I MAXCT>500 S MAXCT=500
 I '$D(^PRC(443)) S RESULT(0)=0 Q
 S IEN=0
 F  S IEN=$O(^PRC(443,IEN)) Q:'IEN  Q:I>=MAXCT  D
 . S NM=$P($G(^PRC(443,IEN,0)),U,1)
 . Q:NM=""
 . S STAT=$P($G(^PRC(443,IEN,0)),U,4)
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^PRC(443,IEN,0)),U,2)_U_$P($G(^PRC(443,IEN,0)),U,3)_U_STAT
 S RESULT(0)=I
 Q
 ;
INSTALL ;Register RPCs in File #8994
 D REG^ZVEUSER("VE INV ITEM LIST","ITEMLIST","ZVEINV")
 D REG^ZVEUSER("VE INV ITEM DETAIL","ITEMDET","ZVEINV")
 D REG^ZVEUSER("VE INV VENDOR LIST","VENDLIST","ZVEINV")
 D REG^ZVEUSER("VE INV PO LIST","POLIST","ZVEINV")
 W "ZVEINV RPCs registered",!
 Q
