// Auto-generated by vista-module-gen for Beneficiary Travel (DGBT)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package DGBT
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function dgbtRoutes(server: FastifyInstance) {

  /** RPC: DGBT CLAIM DEDUCTIBLE PAID (ARRAY) — 2 param(s) */
  server.get('/vista/dgbt/rpc/dgbt-claim-deductible-paid', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DGBT CLAIM DEDUCTIBLE PAID', [q.patient_icn || '', q.claim_date || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DGBT CLAIM DEDUCTIBLE PAID'], data: result };
  });
}