// Auto-generated by vista-module-gen for Release Of Information - DSSI (DSIR)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package DSIR
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function dsirRoutes(server: FastifyInstance) {

  /** RPC: DSIR GET STATUS CODES (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-status-codes', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET STATUS CODES', [q.actvonly || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET STATUS CODES'], data: result };
  });

  /** RPC: DSIR GET PATIENT DISC HIST (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-patient-disc-hist', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET PATIENT DISC HIST', [q.pat || '', q.frdt || '', q.todt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET PATIENT DISC HIST'], data: result };
  });

  /** RPC: DSIR GET AOD (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-aod', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET AOD', [q.aodien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET AOD'], data: result };
  });

  /** RPC: DSIR GET CLERK REQUESTS (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-clerk-requests', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET CLERK REQUESTS', [q.clerk || '', q.billing || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET CLERK REQUESTS'], data: result };
  });

  /** RPC: DSIR DELIVERY TYPE SUMMARY RPT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-delivery-type-summary-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR DELIVERY TYPE SUMMARY RPT', [q.sdate || '', q.edate || '', q.divl || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR DELIVERY TYPE SUMMARY RPT'], data: result };
  });

  /** RPC: DSIROI GETCMTS GET COMMENTS (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsiroi-getcmts-get-comments', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI GETCMTS GET COMMENTS', [q.ien || '', q.sel || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI GETCMTS GET COMMENTS'], data: result };
  });

  /** RPC: DSIROI1 QUEUELBL QUEUE A LABEL (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsiroi1-queuelbl-queue-a-label', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI1 QUEUELBL QUEUE A LABEL', [q.cien || '', q.rien || '', q.aien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI1 QUEUELBL QUEUE A LABEL'], data: result };
  });

  /** RPC: DSIROI1 PRINTLBL PRINT LABELS (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroi1-printlbl-print-labels', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI1 PRINTLBL PRINT LABELS', [q.cien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI1 PRINTLBL PRINT LABELS'], data: result };
  });

  /** RPC: DSIROI1 PURGELBL PURGE LABELS (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroi1-purgelbl-purge-labels', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI1 PURGELBL PURGE LABELS', [q.cien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI1 PURGELBL PURGE LABELS'], data: result };
  });

  /** RPC: DSIROI1 DEL1LBL DELETE 1 LABEL (SINGLE VALUE) — 3 param(s) */
  server.post('/vista/dsir/rpc/dsiroi1-del1lbl-delete-1-label', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI1 DEL1LBL DELETE 1 LABEL', [q.cien || '', q.rien || '', q.aien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI1 DEL1LBL DELETE 1 LABEL'], data: result };
  });

  /** RPC: DSIROIU LSTIN GET LAST INSTALL (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsiroiu-lstin-get-last-install', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIROIU LSTIN GET LAST INSTALL', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIU LSTIN GET LAST INSTALL'], data: result };
  });

  /** RPC: DSIR REQUESTS BY DATE (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-requests-by-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR REQUESTS BY DATE', [q.fromdate || '', q.todate || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR REQUESTS BY DATE'], data: result };
  });

  /** RPC: DSIR ADD DOCUMENT (ARRAY) — 1 param(s) */
  server.post('/vista/dsir/rpc/dsir-add-document', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR ADD DOCUMENT', [q.data_array || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR ADD DOCUMENT'], data: result };
  });

  /** RPC: DSIR GET DOCUMENTS (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-documents', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET DOCUMENTS', [q.request_ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET DOCUMENTS'], data: result };
  });

  /** RPC: DSIR CLEANUP (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-cleanup', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR CLEANUP', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR CLEANUP'], data: result };
  });

  /** RPC: DSIR SET FOLLOWUP DATE (ARRAY) — 0 param(s) */
  server.post('/vista/dsir/rpc/dsir-set-followup-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR SET FOLLOWUP DATE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR SET FOLLOWUP DATE'], data: result };
  });

  /** RPC: DSIR FOLLOWUP REQUIRED LIST (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-followup-required-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR FOLLOWUP REQUIRED LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR FOLLOWUP REQUIRED LIST'], data: result };
  });

  /** RPC: DSIR CHECK PREV REQ (ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-check-prev-req', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR CHECK PREV REQ', [q.dfn || '', q.requestor || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR CHECK PREV REQ'], data: result };
  });

  /** RPC: DSIR GET DOC DATES (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-doc-dates', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET DOC DATES', [q.request_ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET DOC DATES'], data: result };
  });

  /** RPC: DSIR SET DOC DATES (ARRAY) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-set-doc-dates', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR SET DOC DATES', [q.vejdifn || '', q.vejddats || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR SET DOC DATES'], data: result };
  });

  /** RPC: DSIR REQUESTS SINCE DATE (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-requests-since-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR REQUESTS SINCE DATE', [q.vejddfn || '', q.vejddate || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR REQUESTS SINCE DATE'], data: result };
  });

  /** RPC: DSIR GET ROUTINE VERSION (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-routine-version', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET ROUTINE VERSION', [q.vejdrtn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET ROUTINE VERSION'], data: result };
  });

  /** RPC: DSIR RPT BY REQUESTOR (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsir-rpt-by-requestor', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR RPT BY REQUESTOR', [q.from_date || '', q.to_date || '', q.status || '', q.clerk_s_ || '', q.division_s_ || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR RPT BY REQUESTOR'], data: result };
  });

  /** RPC: DSIR RPT REQUESTORS IN SYS (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-rpt-requestors-in-sys', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR RPT REQUESTORS IN SYS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR RPT REQUESTORS IN SYS'], data: result };
  });

  /** RPC: DSIR RPT REQUESTS BY TYPE (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsir-rpt-requests-by-type', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR RPT REQUESTS BY TYPE', [q.from_date || '', q.to_date || '', q.status || '', q.divisions || '', q.types || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR RPT REQUESTS BY TYPE'], data: result };
  });

  /** RPC: DSIR CLERKS LIST (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-clerks-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR CLERKS LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR CLERKS LIST'], data: result };
  });

  /** RPC: DSIR UPDATE ADDRESS (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dsir/rpc/dsir-update-address', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR UPDATE ADDRESS', [q.address_record || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR UPDATE ADDRESS'], data: result };
  });

  /** RPC: DSIR GET ADDRESSES (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-addresses', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET ADDRESSES', [q.patient_requestor || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET ADDRESSES'], data: result };
  });

  /** RPC: DSIR UPDATE STATUS (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-update-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR UPDATE STATUS', [q.roi_instance_number || '', q.status_code || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR UPDATE STATUS'], data: result };
  });

  /** RPC: DSIR CURRENT STATUS (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-current-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR CURRENT STATUS', [q.roi_instance_number || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR CURRENT STATUS'], data: result };
  });

  /** RPC: DSIR STATUS HISTORY (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-status-history', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR STATUS HISTORY', [q.request || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR STATUS HISTORY'], data: result };
  });

  /** RPC: DSIR GET REASONS FOR REQUEST (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-reasons-for-request', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET REASONS FOR REQUEST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET REASONS FOR REQUEST'], data: result };
  });

  /** RPC: DSIR GET REQUEST TYPES (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-request-types', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET REQUEST TYPES', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET REQUEST TYPES'], data: result };
  });

  /** RPC: DSIR GET REQUESTOR TYPES (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-requestor-types', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET REQUESTOR TYPES', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET REQUESTOR TYPES'], data: result };
  });

  /** RPC: DSIR GET AUTHORITY (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-authority', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET AUTHORITY', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET AUTHORITY'], data: result };
  });

  /** RPC: DSIR GET ROIS (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-rois', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET ROIS', [q.type_of_list || '', q.status || '', q.patient_clerk_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET ROIS'], data: result };
  });

  /** RPC: DSIR ADD/EDIT ROI (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dsir/rpc/dsir-add-edit-roi', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR ADD/EDIT ROI', [q.data_array || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR ADD/EDIT ROI'], data: result };
  });

  /** RPC: DSIR REFORMAT REPORTS (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsir-reformat-reports', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR REFORMAT REPORTS', [q.new_report_length || '', q.header_count || '', q.footer_count || '', q.old_line_count || '', q.incoming__old__report || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR REFORMAT REPORTS'], data: result };
  });

  /** RPC: DSIR STATUS ON DATE (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-status-on-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR STATUS ON DATE', [q.request || '', q.date || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR STATUS ON DATE'], data: result };
  });

  /** RPC: DSIR GET DOCUMENT TYPES (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-document-types', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET DOCUMENT TYPES', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET DOCUMENT TYPES'], data: result };
  });

  /** RPC: DSIR DELETE REQUESTOR (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-delete-requestor', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR DELETE REQUESTOR', [q.duplicate_orphan || '', q.repoint_to || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR DELETE REQUESTOR'], data: result };
  });

  /** RPC: DSIR YEAR END FOIA REPORT (GLOBAL ARRAY) — 4 param(s) */
  server.get('/vista/dsir/rpc/dsir-year-end-foia-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR YEAR END FOIA REPORT', [q.start_date || '', q.end_date || '', q.div || '', q.quick || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR YEAR END FOIA REPORT'], data: result };
  });

  /** RPC: DSIR GET EXEMPTION 3 INFO (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-exemption-3-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET EXEMPTION 3 INFO', [q.roi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET EXEMPTION 3 INFO'], data: result };
  });

  /** RPC: DSIR COMP ACCOUNTING SUMMARY (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-comp-accounting-summary', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR COMP ACCOUNTING SUMMARY', [q.dfn || '', q.start_date || '', q.end_date || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR COMP ACCOUNTING SUMMARY'], data: result };
  });

  /** RPC: DSIR GET DIVISIONS (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-divisions', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET DIVISIONS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET DIVISIONS'], data: result };
  });

  /** RPC: DSIR TURNAROUND TIME REPORT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-turnaround-time-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR TURNAROUND TIME REPORT', [q.clerk || '', q.start_date || '', q.end_date || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR TURNAROUND TIME REPORT'], data: result };
  });

  /** RPC: DSIR UPDATE BILL (SINGLE VALUE) — 3 param(s) */
  server.post('/vista/dsir/rpc/dsir-update-bill', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR UPDATE BILL', [q.reqn || '', q.biln || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR UPDATE BILL'], data: result };
  });

  /** RPC: DSIR PAYMENT (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-payment', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR PAYMENT', [q.biln || '', q.amnt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR PAYMENT'], data: result };
  });

  /** RPC: DSIR GET BILL INFO (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-bill-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET BILL INFO', [q.dsir || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET BILL INFO'], data: result };
  });

  /** RPC: DSIR GET PAYMENT HISTORY (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-payment-history', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET PAYMENT HISTORY', [q.biln || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET PAYMENT HISTORY'], data: result };
  });

  /** RPC: DSIR TOTAL CHARGES (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-total-charges', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR TOTAL CHARGES', [q.stdt || '', q.endt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR TOTAL CHARGES'], data: result };
  });

  /** RPC: DSIR FEES RECEIVED (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-fees-received', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR FEES RECEIVED', [q.stdt || '', q.endt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR FEES RECEIVED'], data: result };
  });

  /** RPC: DSIR FEES OUTSTANDING (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-fees-outstanding', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR FEES OUTSTANDING', [q.stdt || '', q.endt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR FEES OUTSTANDING'], data: result };
  });

  /** RPC: DSIR GET BILL DOCS (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-bill-docs', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DSIR GET BILL DOCS', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET BILL DOCS'], data: result };
  });

  /** RPC: DSIR FOIA VALIDATION (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-foia-validation', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR FOIA VALIDATION', [q.start_date || '', q.end_date || '', q.division_s_ || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR FOIA VALIDATION'], data: result };
  });

  /** RPC: DSIR CLEANUP EXEMPTIONS (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-cleanup-exemptions', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR CLEANUP EXEMPTIONS', [q.start_date || '', q.end_date || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR CLEANUP EXEMPTIONS'], data: result };
  });

  /** RPC: DSIR CLEAR FOLLOWUP DATES (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-clear-followup-dates', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR CLEAR FOLLOWUP DATES', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR CLEAR FOLLOWUP DATES'], data: result };
  });

  /** RPC: DSIR BILL HISTORY (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-bill-history', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR BILL HISTORY', [q.bill_ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR BILL HISTORY'], data: result };
  });

  /** RPC: DSIR BILL AUDIT HISTORY (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-bill-audit-history', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR BILL AUDIT HISTORY', [q.bill || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR BILL AUDIT HISTORY'], data: result };
  });

  /** RPC: DSIR UPDATE INCLUDE ON BILL (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-update-include-on-bill', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR UPDATE INCLUDE ON BILL', [q.ien || '', q.ind || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR UPDATE INCLUDE ON BILL'], data: result };
  });

  /** RPC: DSIR COMB PAY AND AUD HIST (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-comb-pay-and-aud-hist', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR COMB PAY AND AUD HIST', [q.bill_ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR COMB PAY AND AUD HIST'], data: result };
  });

  /** RPC: DSIR FEES REC RPT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-fees-rec-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR FEES REC RPT', [q.start_date || '', q.end_date || '', q.divisions || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR FEES REC RPT'], data: result };
  });

  /** RPC: DSIR FEES OUT RPT (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-fees-out-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR FEES OUT RPT', [q.divisions || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR FEES OUT RPT'], data: result };
  });

  /** RPC: DSIR AMOUNT BILLED RPT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-amount-billed-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR AMOUNT BILLED RPT', [q.start_date || '', q.end_date || '', q.divisions || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR AMOUNT BILLED RPT'], data: result };
  });

  /** RPC: DSIR STILL OPEN (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-still-open', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR STILL OPEN', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR STILL OPEN'], data: result };
  });

  /** RPC: DSIR PRIORTY REPORT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-priorty-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR PRIORTY REPORT', [q.start_date || '', q.end_date || '', q.division_s_ || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR PRIORTY REPORT'], data: result };
  });

  /** RPC: DSIR KILL BILL (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-kill-bill', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR KILL BILL', [q.bill_ien || '', q.admin_override || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR KILL BILL'], data: result };
  });

  /** RPC: DSIR ADD NONCOMP PAT (ARRAY) — 5 param(s) */
  server.post('/vista/dsir/rpc/dsir-add-noncomp-pat', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR ADD NONCOMP PAT', [q.name || '', q.ssn || '', q.dob || '', q.ovrd || '', q.ncpien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR ADD NONCOMP PAT'], data: result };
  });

  /** RPC: DSIR ADD ANNOTATION (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dsir/rpc/dsir-add-annotation', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DSIR ADD ANNOTATION', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR ADD ANNOTATION'], data: result };
  });

  /** RPC: DSIR STATUS DISCREPANCY RPT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-status-discrepancy-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR STATUS DISCREPANCY RPT', [q.start_date || '', q.end_date || '', q.clerk_s_ || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR STATUS DISCREPANCY RPT'], data: result };
  });

  /** RPC: DSIR REQUEST INQUIRY (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-request-inquiry', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR REQUEST INQUIRY', [q.roi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR REQUEST INQUIRY'], data: result };
  });

  /** RPC: DSIR FIRST CLOSED DATE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-first-closed-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR FIRST CLOSED DATE', [q.roi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR FIRST CLOSED DATE'], data: result };
  });

  /** RPC: DSIR LAST CLOSED DATE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-last-closed-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR LAST CLOSED DATE', [q.roi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR LAST CLOSED DATE'], data: result };
  });

  /** RPC: DSIR ADD/DEL SENSITIVE PROV (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-add-del-sensitive-prov', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR ADD/DEL SENSITIVE PROV', [q.prov || '', q.del || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR ADD/DEL SENSITIVE PROV'], data: result };
  });

  /** RPC: DSIR GET SENSITIVE PROVIDERS (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-sensitive-providers', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET SENSITIVE PROVIDERS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET SENSITIVE PROVIDERS'], data: result };
  });

  /** RPC: DSIR LIST FOIA OFFSETS (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-list-foia-offsets', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR LIST FOIA OFFSETS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR LIST FOIA OFFSETS'], data: result };
  });

  /** RPC: DSIR GET FOIA OFFSETS (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-foia-offsets', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET FOIA OFFSETS', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET FOIA OFFSETS'], data: result };
  });

  /** RPC: DSIR UPDATE FOIA OFFSETS (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-update-foia-offsets', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR UPDATE FOIA OFFSETS', [q.foia || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR UPDATE FOIA OFFSETS'], data: result };
  });

  /** RPC: DSIR SET LOCKED STATUS (SINGLE VALUE) — 3 param(s) */
  server.post('/vista/dsir/rpc/dsir-set-locked-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR SET LOCKED STATUS', [q.eddt || '', q.lstat || '', q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR SET LOCKED STATUS'], data: result };
  });

  /** RPC: DSIR GET SELECTION ITEMS (ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-selection-items', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR GET SELECTION ITEMS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET SELECTION ITEMS'], data: result };
  });

  /** RPC: DSIR GET AD HOC REPORT (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-ad-hoc-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET AD HOC REPORT', [q.rpt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET AD HOC REPORT'], data: result };
  });

  /** RPC: DSIR GET REPORT LIST (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-report-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET REPORT LIST', [q.rname || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET REPORT LIST'], data: result };
  });

  /** RPC: DSIR GET AD HOC DATA (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-ad-hoc-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET AD HOC DATA', [q.inarray || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET AD HOC DATA'], data: result };
  });

  /** RPC: DSIR GET REQUESTORS (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-requestors', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET REQUESTORS', [q.pref || '', q.styp || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET REQUESTORS'], data: result };
  });

  /** RPC: DSIR GET FULL STATUS TYPES (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-full-status-types', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET FULL STATUS TYPES', [q.act || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET FULL STATUS TYPES'], data: result };
  });

  /** RPC: DSIR RPT EXPEDITED PROCESSING (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-rpt-expedited-processing', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR RPT EXPEDITED PROCESSING', [q.frdt || '', q.todt || '', q.div || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR RPT EXPEDITED PROCESSING'], data: result };
  });

  /** RPC: DSIR UPDATE FEE WAIVER (SINGLE VALUE) — 7 param(s) */
  server.post('/vista/dsir/rpc/dsir-update-fee-waiver', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR UPDATE FEE WAIVER', [q.ien || '', q.fwclerk || '', q.fwrqst || '', q.fwrqstdt || '', q.fwadj || '', q.fwgrant || '', q.fwadjdt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR UPDATE FEE WAIVER'], data: result };
  });

  /** RPC: DSIR TEST PEND CLARIFICATION (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-test-pend-clarification', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR TEST PEND CLARIFICATION', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR TEST PEND CLARIFICATION'], data: result };
  });

  /** RPC: DSIR ADD/EDIT REQUESTOR (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dsir/rpc/dsir-add-edit-requestor', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR ADD/EDIT REQUESTOR', [q.data_array || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR ADD/EDIT REQUESTOR'], data: result };
  });

  /** RPC: DSIR CHANGE PRIMARY ADDRESS (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsir-change-primary-address', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR CHANGE PRIMARY ADDRESS', [q.rqstr || '', q.addrptr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR CHANGE PRIMARY ADDRESS'], data: result };
  });

  /** RPC: DSIR ADD/EDIT ADDRESS (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dsir/rpc/dsir-add-edit-address', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR ADD/EDIT ADDRESS', [q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR ADD/EDIT ADDRESS'], data: result };
  });

  /** RPC: DSIR SET ADDRESS INACTIVE (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-set-address-inactive', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR SET ADDRESS INACTIVE', [q.adrptr || '', q.flagval || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR SET ADDRESS INACTIVE'], data: result };
  });

  /** RPC: DSIR IS PATIENT REQUESTOR (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-is-patient-requestor', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DSIR IS PATIENT REQUESTOR', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR IS PATIENT REQUESTOR'], data: result };
  });

  /** RPC: DSIR SET LAB TYPE (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-set-lab-type', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR SET LAB TYPE', [q.roi || '', q.typ || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR SET LAB TYPE'], data: result };
  });

  /** RPC: DSIR GET LAB TYPE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-lab-type', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET LAB TYPE', [q.roi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET LAB TYPE'], data: result };
  });

  /** RPC: DSIR GET LAB LIST (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsir-get-lab-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR GET LAB LIST', [q.roi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR GET LAB LIST'], data: result };
  });

  /** RPC: DSIR SET LAB LIST (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsir-set-lab-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR SET LAB LIST', [q.roi || '', q.dtls || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR SET LAB LIST'], data: result };
  });

  /** RPC: DSIR LAB INTERIM (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsir-lab-interim', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR LAB INTERIM', [q.dfn || '', q.date1 || '', q.date2 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR LAB INTERIM'], data: result };
  });

  /** RPC: DSIR LAB INTERIMS (GLOBAL ARRAY) — 4 param(s) */
  server.get('/vista/dsir/rpc/dsir-lab-interims', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIR LAB INTERIMS', [q.dfn || '', q.date1 || '', q.date2 || '', q.ortests || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR LAB INTERIMS'], data: result };
  });

  /** RPC: DSIR DEFAULT EXAM SETTINGS (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsir-default-exam-settings', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIR DEFAULT EXAM SETTINGS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIR DEFAULT EXAM SETTINGS'], data: result };
  });

  /** RPC: DSIROIR PRL PAT REQUEST LIST (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsiroir-prl-pat-request-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROIR PRL PAT REQUEST LIST', [q.stdt || '', q.endt || '', q.pat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIR PRL PAT REQUEST LIST'], data: result };
  });

  /** RPC: DSIROIC WPFILER WP FILER (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsiroic-wpfiler-wp-filer', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROIC WPFILER WP FILER', [q.ien || '', q.type || '', q.strlist || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIC WPFILER WP FILER'], data: result };
  });

  /** RPC: DSIROI GETREQST GET REQUEST (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroi-getreqst-get-request', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI GETREQST GET REQUEST', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI GETREQST GET REQUEST'], data: result };
  });

  /** RPC: DSIROIR2 RTYP RECEIVED METHOD (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsiroir2-rtyp-received-method', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROIR2 RTYP RECEIVED METHOD', [q.sdate || '', q.edate || '', q.divl || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIR2 RTYP RECEIVED METHOD'], data: result };
  });

  /** RPC: DSIRRPT1 BYCLRK RPT BY CLERK (GLOBAL ARRAY) — 7 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt1-byclrk-rpt-by-clerk', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT1 BYCLRK RPT BY CLERK', [q.frdt || '', q.todt || '', q.status || '', q.divl || '', q.reqs || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT1 BYCLRK RPT BY CLERK'], data: result };
  });

  /** RPC: DSIRRPT1 RTYP REQUESTS BY TYPE (GLOBAL ARRAY) — 7 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt1-rtyp-requests-by-type', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT1 RTYP REQUESTS BY TYPE', [q.frdate || '', q.todate || '', q.status || '', q.divl || '', q.typs || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT1 RTYP REQUESTS BY TYPE'], data: result };
  });

  /** RPC: DSIRRPTR CRPT CHECK REPORTS (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsirrptr-crpt-check-reports', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIRRPTR CRPT CHECK REPORTS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTR CRPT CHECK REPORTS'], data: result };
  });

  /** RPC: DSIRRPTR STOP CANCEL REPORT (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dsir/rpc/dsirrptr-stop-cancel-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTR STOP CANCEL REPORT', [q.ien || '', q.wep || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTR STOP CANCEL REPORT'], data: result };
  });

  /** RPC: DSIRRPTR GETRPT GET RPT DATA (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsirrptr-getrpt-get-rpt-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTR GETRPT GET RPT DATA', [q.ien || '', q.stfm || '', q.recs || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTR GETRPT GET RPT DATA'], data: result };
  });

  /** RPC: DSIRRPTR PRMS GET PARAMETERS (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsirrptr-prms-get-parameters', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTR PRMS GET PARAMETERS', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTR PRMS GET PARAMETERS'], data: result };
  });

  /** RPC: DSIRRPT2 TTIM TURNAROUND TIME (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt2-ttim-turnaround-time', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT2 TTIM TURNAROUND TIME', [q.frdt || '', q.todt || '', q.divl || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT2 TTIM TURNAROUND TIME'], data: result };
  });

  /** RPC: DSIRRPT3 DTR DELIVERY TYPE RPT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt3-dtr-delivery-type-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT3 DTR DELIVERY TYPE RPT', [q.frdt || '', q.todt || '', q.divl || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT3 DTR DELIVERY TYPE RPT'], data: result };
  });

  /** RPC: DSIRRPT3 RTR HOW RECEIVED RPT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt3-rtr-how-received-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT3 RTR HOW RECEIVED RPT', [q.frdt || '', q.todt || '', q.divl || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT3 RTR HOW RECEIVED RPT'], data: result };
  });

  /** RPC: DSIRRPTA AHR GET AD HOC DATA (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsirrpta-ahr-get-ad-hoc-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTA AHR GET AD HOC DATA', [q.inarray || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTA AHR GET AD HOC DATA'], data: result };
  });

  /** RPC: DSIRRPTB AMTB AMOUNT BILLED (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrptb-amtb-amount-billed', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTB AMTB AMOUNT BILLED', [q.frdt || '', q.todt || '', q.divl || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTB AMTB AMOUNT BILLED'], data: result };
  });

  /** RPC: DSIRRPTB FEEO FEES OUT RPT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrptb-feeo-fees-out-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTB FEEO FEES OUT RPT', [q.divl || '', q.sched || '', q.estart || '', q.frdt || '', q.todt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTB FEEO FEES OUT RPT'], data: result };
  });

  /** RPC: DSIRRPTB FEER FEES REC RPT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrptb-feer-fees-rec-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTB FEER FEES REC RPT', [q.frdt || '', q.todt || '', q.divl || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTB FEER FEES REC RPT'], data: result };
  });

  /** RPC: DSIRRPT4 EXP EXPEDITED REPORT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt4-exp-expedited-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT4 EXP EXPEDITED REPORT', [q.frdt || '', q.todt || '', q.div || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT4 EXP EXPEDITED REPORT'], data: result };
  });

  /** RPC: DSIRRPTF FOIA YEAR END REPORT (GLOBAL ARRAY) — 6 param(s) */
  server.get('/vista/dsir/rpc/dsirrptf-foia-year-end-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTF FOIA YEAR END REPORT', [q.frdt || '', q.todt || '', q.div || '', q.quick || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTF FOIA YEAR END REPORT'], data: result };
  });

  /** RPC: DSIRRPT2 PDH PATIENT DISC HIST (GLOBAL ARRAY) — 6 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt2-pdh-patient-disc-hist', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT2 PDH PATIENT DISC HIST', [q.pat || '', q.frdt || '', q.todt || '', q.sched || '', q.estart || '', q.pname || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT2 PDH PATIENT DISC HIST'], data: result };
  });

  /** RPC: DSIRRPT4 CDD DISCREPANCY RPT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrpt4-cdd-discrepancy-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPT4 CDD DISCREPANCY RPT', [q.frdt || '', q.todt || '', q.clrk || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPT4 CDD DISCREPANCY RPT'], data: result };
  });

  /** RPC: DSIRRPTV FOIAV FOIA VALIDATION (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dsir/rpc/dsirrptv-foiav-foia-validation', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRRPTV FOIAV FOIA VALIDATION', [q.frdt || '', q.todt || '', q.div || '', q.sched || '', q.estart || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTV FOIAV FOIA VALIDATION'], data: result };
  });

  /** RPC: DSIRRPTR KCHK REPORT KILL CHK (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsirrptr-kchk-report-kill-chk', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIRRPTR KCHK REPORT KILL CHK', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRRPTR KCHK REPORT KILL CHK'], data: result };
  });

  /** RPC: DSIRBIL0 BLSOUT BILLS DUE (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsirbil0-blsout-bills-due', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIRBIL0 BLSOUT BILLS DUE', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIRBIL0 BLSOUT BILLS DUE'], data: result };
  });

  /** RPC: DSIROI4 BTCH BATCH PROCESSING (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/dsir/rpc/dsiroi4-btch-batch-processing', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI4 BTCH BATCH PROCESSING', [q.type || '', q.ien || '', q.sellist || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI4 BTCH BATCH PROCESSING'], data: result };
  });

  /** RPC: DSIROI4 EDOCS ELECT DOC CHECK (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroi4-edocs-elect-doc-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI4 EDOCS ELECT DOC CHECK', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI4 EDOCS ELECT DOC CHECK'], data: result };
  });

  /** RPC: DSIROI4 GETDEM GET DEMOGRAPHIC (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroi4-getdem-get-demographic', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI4 GETDEM GET DEMOGRAPHIC', [q.ifn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI4 GETDEM GET DEMOGRAPHIC'], data: result };
  });

  /** RPC: DSIROIC ZIP CODE LOOKUP (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dsir/rpc/dsiroic-zip-code-lookup', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROIC ZIP CODE LOOKUP', [q.pcode || '', q.actdate || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIC ZIP CODE LOOKUP'], data: result };
  });

  /** RPC: DSIROIC GETSTLST STATE LIST (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dsir/rpc/dsiroic-getstlst-state-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DSIROIC GETSTLST STATE LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIC GETSTLST STATE LIST'], data: result };
  });

  /** RPC: DSIROIC CLKDAT GET CLERK INFO (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroic-clkdat-get-clerk-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROIC CLKDAT GET CLERK INFO', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIC CLKDAT GET CLERK INFO'], data: result };
  });

  /** RPC: DSIROIC DOD GET DATE OF DEATH (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroic-dod-get-date-of-death', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROIC DOD GET DATE OF DEATH', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIC DOD GET DATE OF DEATH'], data: result };
  });

  /** RPC: DSIROIC PATID GET DFN AND NAME (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroic-patid-get-dfn-and-name', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROIC PATID GET DFN AND NAME', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROIC PATID GET DFN AND NAME'], data: result };
  });

  /** RPC: DSIROI3 CKRQ CHK PAT REQUESTOR (ARRAY) — 1 param(s) */
  server.get('/vista/dsir/rpc/dsiroi3-ckrq-chk-pat-requestor', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DSIROI3 CKRQ CHK PAT REQUESTOR', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI3 CKRQ CHK PAT REQUESTOR'], data: result };
  });

  /** RPC: DSIROI STBLFLG SET BILL FLAG (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dsir/rpc/dsiroi-stblflg-set-bill-flag', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DSIROI STBLFLG SET BILL FLAG', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DSIROI STBLFLG SET BILL FLAG'], data: result };
  });
}