// Auto-generated by vista-module-gen for Automated Medical Information Exchange (DVBA)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package DVBA
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function dvbaRoutes(server: FastifyInstance) {

  /** RPC: DVBAB GET SET (ARRAY) — 2 param(s) */
  server.post('/vista/dvba/rpc/dvbab-get-set', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB GET SET', [q.dvbfil || '', q.dvbfld || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB GET SET'], data: result };
  });

  /** RPC: DVBAB REPORT CHECKLIST (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-checklist', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB REPORT CHECKLIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT CHECKLIST'], data: result };
  });

  /** RPC: DVBAB CHECK CREDENTIALS (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-check-credentials', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB CHECK CREDENTIALS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB CHECK CREDENTIALS'], data: result };
  });

  /** RPC: DVBAB FIND EXAMS (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-find-exams', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FIND EXAMS', [q.input1 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FIND EXAMS'], data: result };
  });

  /** RPC: DVBAB SEND MSG (SINGLE VALUE) — 5 param(s) */
  server.get('/vista/dvba/rpc/dvbab-send-msg', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB SEND MSG', [q.val1 || '', q.val2 || '', q.val3 || '', q.val4 || '', q.val5 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB SEND MSG'], data: result };
  });

  /** RPC: DVBAB APPOINTMENT LIST (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-appointment-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB APPOINTMENT LIST', [q.val1 || '', q.val2 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB APPOINTMENT LIST'], data: result };
  });

  /** RPC: DVBAB REPORT LISTS (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-lists', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB REPORT LISTS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT LISTS'], data: result };
  });

  /** RPC: DVBAB PTINQ (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-ptinq', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB PTINQ', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB PTINQ'], data: result };
  });

  /** RPC: DVBAB INCREASE EXAM COUNT (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-increase-exam-count', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB INCREASE EXAM COUNT', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB INCREASE EXAM COUNT'], data: result };
  });

  /** RPC: DVBAB HEALTH SUMMARY TEXT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dvba/rpc/dvbab-health-summary-text', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB HEALTH SUMMARY TEXT', [q.dfn || '', q.report_id || '', q.health_summary_type || '', q.date_range || '', q.report_section || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB HEALTH SUMMARY TEXT'], data: result };
  });

  /** RPC: DVBAB 2507 PENDING REPORT (GLOBAL ARRAY) — 6 param(s) */
  server.get('/vista/dvba/rpc/dvbab-2507-pending-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB 2507 PENDING REPORT', [q.dvbcsort || '', q.rstat || '', q.erdays || '', q.oldays || '', q.adivnum || '', q.eltyp || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB 2507 PENDING REPORT'], data: result };
  });

  /** RPC: DVBAB INST LIST (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-inst-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB INST LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB INST LIST'], data: result };
  });

  /** RPC: DVBAB DATETIME (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-datetime', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB DATETIME', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB DATETIME'], data: result };
  });

  /** RPC: DVBAB AMIS REPORT (ARRAY) — 6 param(s) */
  server.get('/vista/dvba/rpc/dvbab-amis-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB AMIS REPORT', [q.bdate || '', q.edate || '', q.ronum || '', q.sbull || '', q.duz || '', q.dvbaprty || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB AMIS REPORT'], data: result };
  });

  /** RPC: DVBAB SC VETERAN REPORT (ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-sc-veteran-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB SC VETERAN REPORT', [q.input1 || '', q.input2 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB SC VETERAN REPORT'], data: result };
  });

  /** RPC: DVBAB PENDING C&P REPORT (GLOBAL ARRAY) — 8 param(s) */
  server.get('/vista/dvba/rpc/dvbab-pending-c-p-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB PENDING C&P REPORT', [q.dvbcsort || '', q.rstat || '', q.erdays || '', q.oldays || '', q.adivnum || '', q.eltyp || '', q.dvbadlmtr || '', q.rofilter || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB PENDING C&P REPORT'], data: result };
  });

  /** RPC: DVBAB REPORT EXAM CHKLIST (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-exam-chklist', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB REPORT EXAM CHKLIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT EXAM CHKLIST'], data: result };
  });

  /** RPC: DVBAB REPORT ADMINQ (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-adminq', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT ADMINQ', [q.bdate || '', q.edate || '', q.royesno || '', q.ronum || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT ADMINQ'], data: result };
  });

  /** RPC: DVBAB REPORT INCOMPVET (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-incompvet', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT INCOMPVET', [q.bdate || '', q.edate || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT INCOMPVET'], data: result };
  });

  /** RPC: DVBAB REPORT DISCHARGE (GLOBAL ARRAY) — 4 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-discharge', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT DISCHARGE', [q.bdate || '', q.edate || '', q.adtype || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT DISCHARGE'], data: result };
  });

  /** RPC: DVBAB REPORT READMIT (GLOBAL ARRAY) — 4 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-readmit', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT READMIT', [q.bdate || '', q.edate || '', q.dvbah || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT READMIT'], data: result };
  });

  /** RPC: DVBAB REPORT ADMISSIONS (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-admissions', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT ADMISSIONS', [q.bdate || '', q.edate || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT ADMISSIONS'], data: result };
  });

  /** RPC: DVBAB REPORT PENDING7131 (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-pending7131', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT PENDING7131', [q.seldiv || '', q.div || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT PENDING7131'], data: result };
  });

  /** RPC: DVBAB REPORT CPDETAILS (ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-cpdetails', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT CPDETAILS', [q.dfn || '', q.zreqda || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT CPDETAILS'], data: result };
  });

  /** RPC: DVBAB REPORT 7131INQ (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-7131inq', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT 7131INQ', [q.zdfn || '', q.recien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT 7131INQ'], data: result };
  });

  /** RPC: DVBAB LABLIST (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-lablist', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB LABLIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB LABLIST'], data: result };
  });

  /** RPC: DVBAB VERSION (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-version', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB VERSION', [q.dvbguiv || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB VERSION'], data: result };
  });

  /** RPC: DVBAB DIVISION (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-division', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB DIVISION', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB DIVISION'], data: result };
  });

  /** RPC: DVBAB TEAM PATIENTS (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-team-patients', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB TEAM PATIENTS', [q.team_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB TEAM PATIENTS'], data: result };
  });

  /** RPC: DVBAB REPORTS (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-reports', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORTS', [q.report_type || '', q.report_string || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORTS'], data: result };
  });

  /** RPC: DVBAB MAIL INIT (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-mail-init', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB MAIL INIT', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB MAIL INIT'], data: result };
  });

  /** RPC: DVBAB SURGERY CASE (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-surgery-case', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DVBAB SURGERY CASE', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB SURGERY CASE'], data: result };
  });

  /** RPC: DVBAB ORIGINAL PROCESSING DATE (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-original-processing-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DVBAB ORIGINAL PROCESSING DATE', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB ORIGINAL PROCESSING DATE'], data: result };
  });

  /** RPC: DVBAB MPI ASSIGN ICN (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-mpi-assign-icn', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DVBAB MPI ASSIGN ICN', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB MPI ASSIGN ICN'], data: result };
  });

  /** RPC: DVBAB REPORT ADMISSION INQUIRY (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-admission-inquiry', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB REPORT ADMISSION INQUIRY', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT ADMISSION INQUIRY'], data: result };
  });

  /** RPC: DVBAB REPORT NEW NOTICES DC (GLOBAL ARRAY) — 0 param(s) */
  server.post('/vista/dvba/rpc/dvbab-report-new-notices-dc', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB REPORT NEW NOTICES DC', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT NEW NOTICES DC'], data: result };
  });

  /** RPC: DVBAB TEMPLATE DEFINITION (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-template-definition', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB TEMPLATE DEFINITION', [q.dvbien || '', q.dvbtype || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB TEMPLATE DEFINITION'], data: result };
  });

  /** RPC: DVBAB NOTE TITLES (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-note-titles', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB NOTE TITLES', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB NOTE TITLES'], data: result };
  });

  /** RPC: DVBAB GET VISIT INFO (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-get-visit-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB GET VISIT INFO', [q.patientname || '', q.visitdate || '', q.clinicien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB GET VISIT INFO'], data: result };
  });

  /** RPC: DVBAB REPORT SPECIAL (GLOBAL ARRAY) — 6 param(s) */
  server.get('/vista/dvba/rpc/dvbab-report-special', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB REPORT SPECIAL', [q.dctypes || '', q.bdate || '', q.edate || '', q.ronum || '', q.rep || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB REPORT SPECIAL'], data: result };
  });

  /** RPC: DVBAB SAVE FORM (SINGLE VALUE) — 4 param(s) */
  server.post('/vista/dvba/rpc/dvbab-save-form', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB SAVE FORM', [q.dvbien || '', q.dvblines || '', q.dvblinecount || '', q.dvblinen || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB SAVE FORM'], data: result };
  });

  /** RPC: DVBAB EXAMS BY DATE (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-exams-by-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB EXAMS BY DATE', [q.begdt || '', q.enddt || '', q.dvbadlmtr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB EXAMS BY DATE'], data: result };
  });

  /** RPC: DVBAB TEMPLATE LIST (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-template-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB TEMPLATE LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB TEMPLATE LIST'], data: result };
  });

  /** RPC: DVBAB LOAD FORM (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-load-form', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB LOAD FORM', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB LOAD FORM'], data: result };
  });

  /** RPC: DVBAB NEW PERSON FILE (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-new-person-file', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB NEW PERSON FILE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB NEW PERSON FILE'], data: result };
  });

  /** RPC: DVBAB FETCH 1U4N (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-fetch-1u4n', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FETCH 1U4N', [q.arr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FETCH 1U4N'], data: result };
  });

  /** RPC: DVBAB TEMPLATE REPORT FULL (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-template-report-full', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB TEMPLATE REPORT FULL', [q.strtdt || '', q.enddt || '', q.dvbdlmt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB TEMPLATE REPORT FULL'], data: result };
  });

  /** RPC: DVBAB FORM DATA BACKUP (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-form-data-backup', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FORM DATA BACKUP', [q.dvbien || '', q.listbox_text || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FORM DATA BACKUP'], data: result };
  });

  /** RPC: DVBAB FORM DATA BACKUP DELETE (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dvba/rpc/dvbab-form-data-backup-delete', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FORM DATA BACKUP DELETE', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FORM DATA BACKUP DELETE'], data: result };
  });

  /** RPC: DVBAB FORM DATA BACKUP RESTORE (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-form-data-backup-restore', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FORM DATA BACKUP RESTORE', [q.ien || '', q.sien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FORM DATA BACKUP RESTORE'], data: result };
  });

  /** RPC: DVBAB FORM COPY (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-form-copy', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FORM COPY', [q.dvbab1 || '', q.dvbab2 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FORM COPY'], data: result };
  });

  /** RPC: DVBAB FIND DUPS (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-find-dups', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FIND DUPS', [q.nam || '', q.dob || '', q.ssn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FIND DUPS'], data: result };
  });

  /** RPC: DVBAB SET DIVISION (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dvba/rpc/dvbab-set-division', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB SET DIVISION', [q.num || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB SET DIVISION'], data: result };
  });

  /** RPC: DVBAB GET URL (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-get-url', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB GET URL', [q.index || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB GET URL'], data: result };
  });

  /** RPC: DVBAB DOD REPORT (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/dvba/rpc/dvbab-dod-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB DOD REPORT', [q.ien || '', q.datatype || '', q.begdate || '', q.enddate || '', q.ormax || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB DOD REPORT'], data: result };
  });

  /** RPC: DVBAB DOD INFO (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-dod-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB DOD INFO', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB DOD INFO'], data: result };
  });

  /** RPC: DVBAB FIND DFN BY ICN (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-find-dfn-by-icn', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB FIND DFN BY ICN', [q.icn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB FIND DFN BY ICN'], data: result };
  });

  /** RPC: DVBAB DOD REPORT TYPES (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-dod-report-types', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB DOD REPORT TYPES', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB DOD REPORT TYPES'], data: result };
  });

  /** RPC: DVBAB CCOW (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-ccow', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB CCOW', [q.infotype || '', q.type || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB CCOW'], data: result };
  });

  /** RPC: DVBAB RESTRICTED LIST PATIENTS (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-restricted-list-patients', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB RESTRICTED LIST PATIENTS', [q.duz || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB RESTRICTED LIST PATIENTS'], data: result };
  });

  /** RPC: DVBAB ZIP2CITY (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-zip2city', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB ZIP2CITY', [q.dvbzip || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB ZIP2CITY'], data: result };
  });

  /** RPC: DVBA CHECK PATCH (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-check-patch', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CHECK PATCH', [q.dvbpatch || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CHECK PATCH'], data: result };
  });

  /** RPC: DVBAB GET VVA TOKEN (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-get-vva-token', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB GET VVA TOKEN', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB GET VVA TOKEN'], data: result };
  });

  /** RPC: DVBAB 8861 NOTIFICATIONS (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-8861-notifications', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB 8861 NOTIFICATIONS', [q.ien || '', q.stat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB 8861 NOTIFICATIONS'], data: result };
  });

  /** RPC: DVBA MVI SEARCH PERSON (ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvba-mvi-search-person', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA MVI SEARCH PERSON', [q.person_traits || '', q.initial_quantity || '', q.name_format || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA MVI SEARCH PERSON'], data: result };
  });

  /** RPC: DVBA MVI GET CORRESPONDING IDS (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-mvi-get-corresponding-ids', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA MVI GET CORRESPONDING IDS', [q.source_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA MVI GET CORRESPONDING IDS'], data: result };
  });

  /** RPC: DVBAD CONTRACTED EXAM REPORTS (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbad-contracted-exam-reports', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAD CONTRACTED EXAM REPORTS', [q.dvbartyp || '', q.dvbafltrs || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAD CONTRACTED EXAM REPORTS'], data: result };
  });

  /** RPC: DVBAD CONTRACTED EXAM CRYPTO (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbad-contracted-exam-crypto', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAD CONTRACTED EXAM CRYPTO', [q.dvbaetyp || '', q.dvbaival || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAD CONTRACTED EXAM CRYPTO'], data: result };
  });

  /** RPC: DVBAB SEND MSG TWO (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvbab-send-msg-two', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB SEND MSG TWO', [q.duz || '', q.rien || '', q.elist || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB SEND MSG TWO'], data: result };
  });

  /** RPC: DVBA CAPRI EXAM XML (SINGLE VALUE) — 4 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-exam-xml', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI EXAM XML', [q.examien || '', q.das || '', q.dattim || '', q.xml || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI EXAM XML'], data: result };
  });

  /** RPC: DVBA CAPRI EXAM LINK TIU (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-exam-link-tiu', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI EXAM LINK TIU', [q.examien || '', q.tiuien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI EXAM LINK TIU'], data: result };
  });

  /** RPC: DVBA CAPRI GET EXAM IEN (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-exam-ien', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET EXAM IEN', [q.tiuien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EXAM IEN'], data: result };
  });

  /** RPC: DVBA CAPRI GETSPCLCONSID (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-getspclconsid', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GETSPCLCONSID', [q['2507_request_ien'] || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GETSPCLCONSID'], data: result };
  });

  /** RPC: DVBA CAPRI LISTSPCLCONSID (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-listspclconsid', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI LISTSPCLCONSID', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI LISTSPCLCONSID'], data: result };
  });

  /** RPC: DVBA CAPRI SETSPCLCONSID (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-setspclconsid', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SETSPCLCONSID', [q['2507_request_ien'] || '', q.special_consideration_list || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SETSPCLCONSID'], data: result };
  });

  /** RPC: DVBA CAPRI LISTINSUFRSN (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-listinsufrsn', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI LISTINSUFRSN', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI LISTINSUFRSN'], data: result };
  });

  /** RPC: DVBA CAPRI LISTCLAIMTYPE (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-listclaimtype', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI LISTCLAIMTYPE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI LISTCLAIMTYPE'], data: result };
  });

  /** RPC: DVBA CAPRI GETCLAIMTYPE (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-getclaimtype', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GETCLAIMTYPE', [q.reqien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GETCLAIMTYPE'], data: result };
  });

  /** RPC: DVBA CAPRI SETCLAIMTYPE (ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-setclaimtype', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SETCLAIMTYPE', [q.reqien || '', q.arrayct || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SETCLAIMTYPE'], data: result };
  });

  /** RPC: DVBA CAPRI GETCANCELREASON (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-getcancelreason', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GETCANCELREASON', [q.list || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GETCANCELREASON'], data: result };
  });

  /** RPC: DVBA CAPRI GETCONTREMARKS (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-getcontremarks', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GETCONTREMARKS', [q.dvbeien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GETCONTREMARKS'], data: result };
  });

  /** RPC: DVBA CAPRI SETCONTREMARKS (WORD PROCESSING) — 4 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-setcontremarks', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SETCONTREMARKS', [q.rqid || '', q.text || '', q.return || '', q.eien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SETCONTREMARKS'], data: result };
  });

  /** RPC: DVBA CAPRI GET REROUTE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-reroute', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET REROUTE', [q.rsp || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET REROUTE'], data: result };
  });

  /** RPC: DVBA CAPRI REROUTE VAMC (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-reroute-vamc', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI REROUTE VAMC', [q.sortby || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI REROUTE VAMC'], data: result };
  });

  /** RPC: DVBA CAPRI GET DIVISION (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-division', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI GET DIVISION', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET DIVISION'], data: result };
  });

  /** RPC: DVBA CAPRI GET DIV COMMENT (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-div-comment', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET DIV COMMENT', [q.div || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET DIV COMMENT'], data: result };
  });

  /** RPC: DVBA CAPRI GET DIV EXAM (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-div-exam', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET DIV EXAM', [q.div || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET DIV EXAM'], data: result };
  });

  /** RPC: DVBA CAPRI GET REROUTE CODE (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-reroute-code', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI GET REROUTE CODE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET REROUTE CODE'], data: result };
  });

  /** RPC: DVBA CAPRI SEND REROUTE (SINGLE VALUE) — 6 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-send-reroute', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SEND REROUTE', [q['2507_request_ien'] || '', q.station_number || '', q.patient_ien || '', q.routing_location || '', q.reroute_reason || '', q.reroute_description || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SEND REROUTE'], data: result };
  });

  /** RPC: DVBA CAPRI REROUTE INFO (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-reroute-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI REROUTE INFO', [q.request_ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI REROUTE INFO'], data: result };
  });

  /** RPC: DVBA CAPRI REROUTE STATUS (SINGLE VALUE) — 4 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-reroute-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI REROUTE STATUS', [q.rien || '', q.rrsta || '', q.rejr || '', q.rmas || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI REROUTE STATUS'], data: result };
  });

  /** RPC: DVBA CAPRI GET EDIPI (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-edipi', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DVBA CAPRI GET EDIPI', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EDIPI'], data: result };
  });

  /** RPC: DVBA CAPRI GET EDIPI2 (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-edipi2', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DVBA CAPRI GET EDIPI2', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EDIPI2'], data: result };
  });

  /** RPC: DVBAB PRF POPUP (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-prf-popup', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB PRF POPUP', [q.ptdfn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB PRF POPUP'], data: result };
  });

  /** RPC: DVBAB HASFLG (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-hasflg', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB HASFLG', [q.ptdfn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB HASFLG'], data: result };
  });

  /** RPC: DVBAB GETFLAG (ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvbab-getflag', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB GETFLAG', [q.ptdfn || '', q.flagid || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB GETFLAG'], data: result };
  });

  /** RPC: DVBAB CLRFLG (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-clrflg', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB CLRFLG', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB CLRFLG'], data: result };
  });

  /** RPC: DVBAB SELF REFERRAL (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-self-referral', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBAB SELF REFERRAL', [q.patient_ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB SELF REFERRAL'], data: result };
  });

  /** RPC: DVBA MVI CERNER CORRELATIONS (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-mvi-cerner-correlations', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA MVI CERNER CORRELATIONS', [q.icn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA MVI CERNER CORRELATIONS'], data: result };
  });

  /** RPC: DVBA ACTIVE DBQ LIST (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-active-dbq-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA ACTIVE DBQ LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA ACTIVE DBQ LIST'], data: result };
  });

  /** RPC: DVBA DBQ CHECK (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-dbq-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA DBQ CHECK', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA DBQ CHECK'], data: result };
  });

  /** RPC: DVBA DBQ GEN CHECK (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-dbq-gen-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA DBQ GEN CHECK', [q.dvbdbq || '', q.dvbdate || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA DBQ GEN CHECK'], data: result };
  });

  /** RPC: DVBA REPORT BUILDER (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-report-builder', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA REPORT BUILDER', [q.array || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA REPORT BUILDER'], data: result };
  });

  /** RPC: DVBA CAPRI DBQ STATUS (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-dbq-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI DBQ STATUS', [q.ien || '', q.dbq_status || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI DBQ STATUS'], data: result };
  });

  /** RPC: DVBA CAPRI GET EFOLDER TOKEN (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-efolder-token', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET EFOLDER TOKEN', [q.duz || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EFOLDER TOKEN'], data: result };
  });

  /** RPC: DVBA CAPRI PARAM INQ (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-param-inq', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI PARAM INQ', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PARAM INQ'], data: result };
  });

  /** RPC: DVBA CAPRI PARAM UPDATE (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-param-update', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI PARAM UPDATE', [q.parameter_name || '', q.value || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PARAM UPDATE'], data: result };
  });

  /** RPC: DVBA CAPRI CLINDOC URLS (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-clindoc-urls', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI CLINDOC URLS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI CLINDOC URLS'], data: result };
  });

  /** RPC: DVBA CAPRI GET TOGGLES (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-toggles', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET TOGGLES', [q.dvbtog || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET TOGGLES'], data: result };
  });

  /** RPC: DVBA CAPRI GET PAR DESC (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-par-desc', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET PAR DESC', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET PAR DESC'], data: result };
  });

  /** RPC: DVBA CAPRI SET METRICS (SINGLE VALUE) — 6 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-set-metrics', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SET METRICS', [q.dvbauth || '', q.dvbpien || '', q.dvbtrans || '', q.dvberr || '', q.dvbstat || '', q.dvbrpd || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SET METRICS'], data: result };
  });

  /** RPC: DVBA CAPRI PURGE MET (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-purge-met', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI PURGE MET', [q.duz || '', q.date || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PURGE MET'], data: result };
  });

  /** RPC: DVBA CAPRI GET MET RPT (ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-met-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET MET RPT', [q.dvbbdt || '', q.dvbedt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET MET RPT'], data: result };
  });

  /** RPC: DVBA CAPRI GET ALL PARAM (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-all-param', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET ALL PARAM', [q.null || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET ALL PARAM'], data: result };
  });

  /** RPC: DVBAB CAPRI ALLOW CLINDOCS (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-capri-allow-clindocs', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DVBAB CAPRI ALLOW CLINDOCS', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB CAPRI ALLOW CLINDOCS'], data: result };
  });

  /** RPC: DVBAB CAPRI EFOLDER LOCATION (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvbab-capri-efolder-location', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBAB CAPRI EFOLDER LOCATION', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB CAPRI EFOLDER LOCATION'], data: result };
  });

  /** RPC: DVBAB CAPRI PROVIDER (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvbab-capri-provider', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    if (!q.dfn) return { ok: false, error: 'dfn query parameter is required' };
    const result = await safeCallRpc('DVBAB CAPRI PROVIDER', [q.dfn]);
    return { ok: true, source: 'vista', rpcUsed: ['DVBAB CAPRI PROVIDER'], data: result };
  });

  /** RPC: DVBA CAPRI SPEC ADD (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-spec-add', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SPEC ADD', [q.dvbname || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SPEC ADD'], data: result };
  });

  /** RPC: DVBA CAPRI SPEC STATUS (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-spec-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SPEC STATUS', [q.dvbien || '', q.dvbstat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SPEC STATUS'], data: result };
  });

  /** RPC: DVBA CAPRI SPEC INACTIVE (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-spec-inactive', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI SPEC INACTIVE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SPEC INACTIVE'], data: result };
  });

  /** RPC: DVBA CAPRI WORKSHEET STAT LIST (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-worksheet-stat-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI WORKSHEET STAT LIST', [q.dvbstat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI WORKSHEET STAT LIST'], data: result };
  });

  /** RPC: DVBA CAPRI WORKSHEET NAME ED (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-worksheet-name-ed', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI WORKSHEET NAME ED', [q.dvbien || '', q.dvbname || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI WORKSHEET NAME ED'], data: result };
  });

  /** RPC: DVBA CAPRI WORKSHEET STATUS (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-worksheet-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI WORKSHEET STATUS', [q.dvbien || '', q.dvbstat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI WORKSHEET STATUS'], data: result };
  });

  /** RPC: DVBA CAPRI UPDATE DBQ TRANSTAT (SINGLE VALUE) — 5 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-update-dbq-transtat', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI UPDATE DBQ TRANSTAT', [q.dvbien || '', q.dvbct || '', q.dvbname || '', q.dvbstat || '', q.dvbresp || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI UPDATE DBQ TRANSTAT'], data: result };
  });

  /** RPC: DVBA CAPRI GET DBQ XML (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-dbq-xml', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET DBQ XML', [q.dvbien || '', q.dvbct || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET DBQ XML'], data: result };
  });

  /** RPC: DVBA CAPRI DBQ TRANS FAIL LIST (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-dbq-trans-fail-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI DBQ TRANS FAIL LIST', [q.dvbduz || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI DBQ TRANS FAIL LIST'], data: result };
  });

  /** RPC: DVBA CAPRI SAVE DBQ XML (SINGLE VALUE) — 7 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-save-dbq-xml', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SAVE DBQ XML', [q.dvbname || '', q.dvbct || '', q.dvbxml || '', q.dvbstat || '', q.dvbresp || '', q.dvbien || '', q.dvbpm5 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SAVE DBQ XML'], data: result };
  });

  /** RPC: DVBA CAPRI NF DATA (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nf-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI NF DATA', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NF DATA'], data: result };
  });

  /** RPC: DVBA CAPRI GET EXAM REPORT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-exam-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET EXAM REPORT', [q.dvbien || '', q.dvbsdt || '', q.dvbedt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EXAM REPORT'], data: result };
  });

  /** RPC: DVBA CAPRI FAIL CHECK (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-fail-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI FAIL CHECK', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI FAIL CHECK'], data: result };
  });

  /** RPC: DVBA CAPRI GITHUB LOCATION (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-github-location', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI GITHUB LOCATION', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GITHUB LOCATION'], data: result };
  });

  /** RPC: DVBA CAPRI GET GITHUB DATA (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-github-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI GET GITHUB DATA', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET GITHUB DATA'], data: result };
  });

  /** RPC: DVBA CAPRI GITHUB DATE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-github-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GITHUB DATE', [q.dvbdate || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GITHUB DATE'], data: result };
  });

  /** RPC: DVBA CAPRI GET GITHUB DATE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-github-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET GITHUB DATE', [q.none || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET GITHUB DATE'], data: result };
  });

  /** RPC: DVBA CAPRI IEPD DATA (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-iepd-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI IEPD DATA', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI IEPD DATA'], data: result };
  });

  /** RPC: DVBA CAPRI GET EXAM PDF (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-exam-pdf', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET EXAM PDF', [q.dvbarray || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EXAM PDF'], data: result };
  });

  /** RPC: DVBA CAPRI CREATE WORKSHEET (ARRAY) — 2 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-create-worksheet', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI CREATE WORKSHEET', [q.dvbdata || '', q.dvbexamlist || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI CREATE WORKSHEET'], data: result };
  });

  /** RPC: DVBA CAPRI SAVE EXAM PDF (SINGLE VALUE) — 7 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-save-exam-pdf', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SAVE EXAM PDF', [q.dvbien || '', q.dvbseq || '', q.dvbexamname || '', q.dvbpdfdata || '', q.dvbtabio || '', q.dvbsmsg || '', q.dvbver || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SAVE EXAM PDF'], data: result };
  });

  /** RPC: DVBA CAPRI GET WORKSHEET (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-worksheet', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET WORKSHEET', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET WORKSHEET'], data: result };
  });

  /** RPC: DVBA CAPRI PASCAL CHECK (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-pascal-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI PASCAL CHECK', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PASCAL CHECK'], data: result };
  });

  /** RPC: DVBA CAPRI GET WORKSHEET LIST (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-worksheet-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET WORKSHEET LIST', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET WORKSHEET LIST'], data: result };
  });

  /** RPC: DVBA CAPRI DELETE CHECK (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-delete-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI DELETE CHECK', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI DELETE CHECK'], data: result };
  });

  /** RPC: DVBA CAPRI DELETE WORKSHEET (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-delete-worksheet', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI DELETE WORKSHEET', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI DELETE WORKSHEET'], data: result };
  });

  /** RPC: DVBA CAPRI WORKSHEET UPDATE (ARRAY) — 9 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-worksheet-update', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI WORKSHEET UPDATE', [q.dvbien || '', q.dvbauth || '', q.dvbtran || '', q.dvbdbq || '', q.dvbf19 || '', q.dvbf20 || '', q.dvbf21 || '', q.dvbf12 || '', q.dvbf1_ || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI WORKSHEET UPDATE'], data: result };
  });

  /** RPC: DVBA CAPRI GET DBQ PDF (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-dbq-pdf', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET DBQ PDF', [q.dvbien || '', q.dvbct || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET DBQ PDF'], data: result };
  });

  /** RPC: DVBA CAPRI INVALID CHAR LIST (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-invalid-char-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI INVALID CHAR LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI INVALID CHAR LIST'], data: result };
  });

  /** RPC: DVBA CAPRI CMT SSN VAR (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-cmt-ssn-var', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI CMT SSN VAR', [q.null || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI CMT SSN VAR'], data: result };
  });

  /** RPC: DVBA CAPRI UNLOCK EXAM (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-unlock-exam', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI UNLOCK EXAM', [q.dvbien || '', q.dvblock || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI UNLOCK EXAM'], data: result };
  });

  /** RPC: DVBA CAPRI ADD EXAM (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-add-exam', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI ADD EXAM', [q.dvbien || '', q.dvbexamname || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI ADD EXAM'], data: result };
  });

  /** RPC: DVBA CAPRI DELETE EXAM (SINGLE VALUE) — 3 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-delete-exam', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI DELETE EXAM', [q.dvbien || '', q.dvbseq || '', q.dvbexamname || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI DELETE EXAM'], data: result };
  });

  /** RPC: DVBA CAPRI CMT TOGGLE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-cmt-toggle', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI CMT TOGGLE', [q.null || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI CMT TOGGLE'], data: result };
  });

  /** RPC: DVBA CAPRI GET EXAM HISTORY (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-exam-history', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET EXAM HISTORY', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EXAM HISTORY'], data: result };
  });

  /** RPC: DVBA CAPRI EXAM RESTORE (SINGLE VALUE) — 5 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-exam-restore', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI EXAM RESTORE', [q.dvbien || '', q.dvbseq || '', q.dvbexam || '', q.dvbsave || '', q.dvbdtm || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI EXAM RESTORE'], data: result };
  });

  /** RPC: DVBA CAPRI TEMP DEF LIST (ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-temp-def-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI TEMP DEF LIST', [q.dvbfilt || '', q.dvbsort || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI TEMP DEF LIST'], data: result };
  });

  /** RPC: DVBA CAPRI GET EXAMINER INFO (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-examiner-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET EXAMINER INFO', [q.dvbduz || '', q.dvbdvi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET EXAMINER INFO'], data: result };
  });

  /** RPC: DVBA CAPRI SAVE SIGNER (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-save-signer', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SAVE SIGNER', [q.dvbien || '', q.dvbcosigner || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SAVE SIGNER'], data: result };
  });

  /** RPC: DVBA CAPRI GET SECID (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-get-secid', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI GET SECID', [q.dvbduz || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI GET SECID'], data: result };
  });

  /** RPC: DVBA CAPRI UNCOSIGN COUNT (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-uncosign-count', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI UNCOSIGN COUNT', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI UNCOSIGN COUNT'], data: result };
  });

  /** RPC: DVBA CAPRI UNCOSIGNED INFO (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-uncosigned-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI UNCOSIGNED INFO', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI UNCOSIGNED INFO'], data: result };
  });

  /** RPC: DVBA CAPRI SECURITY TOGGLE (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-security-toggle', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI SECURITY TOGGLE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SECURITY TOGGLE'], data: result };
  });

  /** RPC: DVBA CAPRI PDF SIG FIELD NAMES (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-pdf-sig-field-names', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI PDF SIG FIELD NAMES', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PDF SIG FIELD NAMES'], data: result };
  });

  /** RPC: DVBA CAPRI SAVE REVIEW DATA (SINGLE VALUE) — 3 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-save-review-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI SAVE REVIEW DATA', [q.dvbien || '', q.dvbtyp || '', q.dvbrevcmt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SAVE REVIEW DATA'], data: result };
  });

  /** RPC: DVBA CAPRI TRAINEE DOC MANAGER (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-trainee-doc-manager', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI TRAINEE DOC MANAGER', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI TRAINEE DOC MANAGER'], data: result };
  });

  /** RPC: DVBA CAPRI TRAINEE SIGNATURE (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-trainee-signature', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI TRAINEE SIGNATURE', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI TRAINEE SIGNATURE'], data: result };
  });

  /** RPC: DVBA CAPRI STATUS COUNT (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-status-count', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI STATUS COUNT', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI STATUS COUNT'], data: result };
  });

  /** RPC: DVBA CAPRI ALERTS DATA (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-alerts-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI ALERTS DATA', [q.dvbst || '', q.dvbduz || '', q.dvbut || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI ALERTS DATA'], data: result };
  });

  /** RPC: DVBA CAPRI PDF LOGIC TOGGLE (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-pdf-logic-toggle', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI PDF LOGIC TOGGLE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PDF LOGIC TOGGLE'], data: result };
  });

  /** RPC: DVBA CAPRI WORKSHEET BY EXAM (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-worksheet-by-exam', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI WORKSHEET BY EXAM', [q.dvbexam || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI WORKSHEET BY EXAM'], data: result };
  });

  /** RPC: DVBA CAPRI PN TOGGLE (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-pn-toggle', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI PN TOGGLE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PN TOGGLE'], data: result };
  });

  /** RPC: DVBA CAPRI SKIP PARENTCHILD (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-skip-parentchild', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI SKIP PARENTCHILD', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SKIP PARENTCHILD'], data: result };
  });

  /** RPC: DVBA CAPRI SKIP CHILD RESET (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-skip-child-reset', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI SKIP CHILD RESET', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SKIP CHILD RESET'], data: result };
  });

  /** RPC: DVBA CAPRI CMT IEPD RESET (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-cmt-iepd-reset', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI CMT IEPD RESET', [q.n_a || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI CMT IEPD RESET'], data: result };
  });

  /** RPC: DVBA CAPRI CMT SKIP COND (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-cmt-skip-cond', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI CMT SKIP COND', [q.n_a || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI CMT SKIP COND'], data: result };
  });

  /** RPC: DVBA CAPRI WORD WRAP (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-word-wrap', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI WORD WRAP', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI WORD WRAP'], data: result };
  });

  /** RPC: DVBA CAPRI MED OPN FIELDS (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-med-opn-fields', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI MED OPN FIELDS', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI MED OPN FIELDS'], data: result };
  });

  /** RPC: DVBA CAPRI SUPPORT MESSAGE (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-support-message', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI SUPPORT MESSAGE', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI SUPPORT MESSAGE'], data: result };
  });

  /** RPC: DVBA CAPRI NRE LOAD (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nre-load', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI NRE LOAD', [q.dvbdivid || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE LOAD'], data: result };
  });

  /** RPC: DVBA CAPRI NRE MARK (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nre-mark', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI NRE MARK', [q.dvbprocessid || '', q.dvbexportmark || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE MARK'], data: result };
  });

  /** RPC: DVBA CAPRI NRE OPEN (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nre-open', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI NRE OPEN', [q.dvbprocessid || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE OPEN'], data: result };
  });

  /** RPC: DVBA CAPRI NRE SAVE (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/dvba/rpc/dvba-capri-nre-save', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI NRE SAVE', [q.dvbsavestring || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE SAVE'], data: result };
  });

  /** RPC: DVBA CAPRI NRE STATIC (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nre-static', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI NRE STATIC', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE STATIC'], data: result };
  });

  /** RPC: DVBA CAPRI NRE SUMMARY (ARRAY) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nre-summary', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI NRE SUMMARY', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE SUMMARY'], data: result };
  });

  /** RPC: DVBA CAPRI NRE HISTORY (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nre-history', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI NRE HISTORY', [q.dvbdivid || '', q.dvbrangeid || '', q.param3 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE HISTORY'], data: result };
  });

  /** RPC: DVBA CAPRI NRE RUNNOW (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-nre-runnow', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI NRE RUNNOW', [q.dvbsavestring || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI NRE RUNNOW'], data: result };
  });

  /** RPC: DVBA CAPRI PROXY DATA (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-proxy-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI PROXY DATA', [q.null || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI PROXY DATA'], data: result };
  });

  /** RPC: DVBA CAPRI ARP RSKDT (ARRAY) — 2 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-arp-rskdt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI ARP RSKDT', [q.dvbaoptions || '', q.dvbdata || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI ARP RSKDT'], data: result };
  });

  /** RPC: DVBA CAPRI OPEN ACCESS CHECK (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-open-access-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI OPEN ACCESS CHECK', [q.dvbien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI OPEN ACCESS CHECK'], data: result };
  });

  /** RPC: DVBA CAPRI LOOKUP OPTSET (ARRAY) — 1 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-lookup-optset', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('DVBA CAPRI LOOKUP OPTSET', [q.dvboptlist || '']);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI LOOKUP OPTSET'], data: result };
  });

  /** RPC: DVBA CAPRI ARP OPTSET (UNKNOWN()) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-arp-optset', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI ARP OPTSET', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI ARP OPTSET'], data: result };
  });

  /** RPC: DVBA CAPRI TOGGLE XML HEADER (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-toggle-xml-header', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI TOGGLE XML HEADER', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI TOGGLE XML HEADER'], data: result };
  });

  /** RPC: DVBA CAPRI CMT SIGFLD NUM (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/dvba/rpc/dvba-capri-cmt-sigfld-num', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('DVBA CAPRI CMT SIGFLD NUM', []);
    return { ok: true, source: 'vista', rpcUsed: ['DVBA CAPRI CMT SIGFLD NUM'], data: result };
  });
}