// Auto-generated by vista-module-gen for IC (IC)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package IC
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function icRoutes(server: FastifyInstance) {
}