// Auto-generated by vista-module-gen for National Health Information Network (NHIN)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package NHIN
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function nhinRoutes(server: FastifyInstance) {

  /** RPC: NHIN GET VISTA DATA (GLOBAL ARRAY) — 6 param(s) */
  server.get('/vista/nhin/rpc/nhin-get-vista-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('NHIN GET VISTA DATA', [q.dfn || '', q.type || '', q.start || '', q.stop || '', q.max || '', q.item || '']);
    return { ok: true, source: 'vista', rpcUsed: ['NHIN GET VISTA DATA'], data: result };
  });
}