// Auto-generated by vista-module-gen for Asists (OOPS)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package OOPS
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function oopsRoutes(server: FastifyInstance) {

  /** RPC: OOPS REMOTE GET USER OPTIONS (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/oops/rpc/oops-remote-get-user-options', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('OOPS REMOTE GET USER OPTIONS', []);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS REMOTE GET USER OPTIONS'], data: result };
  });

  /** RPC: OOPS GET POINTED TO (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-pointed-to', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET POINTED TO', [q.single || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET POINTED TO'], data: result };
  });

  /** RPC: OOPS GET BODY PART (ARRAY) — 0 param(s) */
  server.get('/vista/oops/rpc/oops-get-body-part', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('OOPS GET BODY PART', []);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET BODY PART'], data: result };
  });

  /** RPC: OOPS GET CASE NUMBERS (GLOBAL ARRAY) — 5 param(s) */
  server.get('/vista/oops/rpc/oops-get-case-numbers', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET CASE NUMBERS', [q.person || '', q.cstat || '', q.pstat || '', q.call || '', q.opt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET CASE NUMBERS'], data: result };
  });

  /** RPC: OOPS GET DUPLICATES (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-duplicates', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET DUPLICATES', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET DUPLICATES'], data: result };
  });

  /** RPC: OOPS LOAD OOPS (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-load-oops', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS LOAD OOPS', [q.list || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS LOAD OOPS'], data: result };
  });

  /** RPC: OOPS EMPLOYEE DATA (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-employee-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS EMPLOYEE DATA', [q.name || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS EMPLOYEE DATA'], data: result };
  });

  /** RPC: OOPS NEW PERSON DATA (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-new-person-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS NEW PERSON DATA', [q.name || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS NEW PERSON DATA'], data: result };
  });

  /** RPC: OOPS GET 2260 DATA (ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-get-2260-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET 2260 DATA', [q.input || '', q.pers || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET 2260 DATA'], data: result };
  });

  /** RPC: OOPS REPLACE DATE/TIME (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-replace-date-time', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS REPLACE DATE/TIME', [q.date || '', q.flag || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS REPLACE DATE/TIME'], data: result };
  });

  /** RPC: OOPS GET CKRANGE (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-ckrange', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET CKRANGE', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET CKRANGE'], data: result };
  });

  /** RPC: OOPS GET WITNESSES (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-witnesses', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET WITNESSES', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET WITNESSES'], data: result };
  });

  /** RPC: OOPS GET DEFAULT MD (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-default-md', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET DEFAULT MD', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET DEFAULT MD'], data: result };
  });

  /** RPC: OOPS GET SUPERVISOR (ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-get-supervisor', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET SUPERVISOR', [q.name || '', q.casessn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET SUPERVISOR'], data: result };
  });

  /** RPC: OOPS CREATE AMENDMENT (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/oops/rpc/oops-create-amendment', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS CREATE AMENDMENT', [q.sing || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS CREATE AMENDMENT'], data: result };
  });

  /** RPC: OOPS EDIT 2260 (ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-edit-2260', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS EDIT 2260', [q.input || '', q.arr || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS EDIT 2260'], data: result };
  });

  /** RPC: OOPS CHANGE CASE STATUS (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-change-case-status', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS CHANGE CASE STATUS', [q.input || '', q.fld58 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS CHANGE CASE STATUS'], data: result };
  });

  /** RPC: OOPS REPLACE WP (ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-replace-wp', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS REPLACE WP', [q.input || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS REPLACE WP'], data: result };
  });

  /** RPC: OOPS VALIDATE TIME (ARRAY) — 3 param(s) */
  server.get('/vista/oops/rpc/oops-validate-time', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS VALIDATE TIME', [q.idt || '', q.pdt || '', q.flag || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS VALIDATE TIME'], data: result };
  });

  /** RPC: OOPS GET DATA (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET DATA', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET DATA'], data: result };
  });

  /** RPC: OOPS GET UNION (ARRAY) — 0 param(s) */
  server.get('/vista/oops/rpc/oops-get-union', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('OOPS GET UNION', []);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET UNION'], data: result };
  });

  /** RPC: OOPS DELETE UNION (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/oops/rpc/oops-delete-union', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS DELETE UNION', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS DELETE UNION'], data: result };
  });

  /** RPC: OOPS PUT UNION (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-put-union', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS PUT UNION', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS PUT UNION'], data: result };
  });

  /** RPC: OOPS GET SITE PARAMETER (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-site-parameter', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET SITE PARAMETER', [q.form || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET SITE PARAMETER'], data: result };
  });

  /** RPC: OOPS SET FIELD (ARRAY) — 2 param(s) */
  server.post('/vista/oops/rpc/oops-set-field', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SET FIELD', [q.input || '', q.value || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SET FIELD'], data: result };
  });

  /** RPC: OOPS DELETE SITEP STATION (UNKNOWN()) — 0 param(s) */
  server.post('/vista/oops/rpc/oops-delete-sitep-station', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('OOPS DELETE SITEP STATION', []);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS DELETE SITEP STATION'], data: result };
  });

  /** RPC: OOPS DELETE SITEPAR STATION (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/oops/rpc/oops-delete-sitepar-station', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS DELETE SITEPAR STATION', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS DELETE SITEPAR STATION'], data: result };
  });

  /** RPC: OOPS EDIT SITEPAR STATION (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/oops/rpc/oops-edit-sitepar-station', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS EDIT SITEPAR STATION', [q.input || '', q.data || '', q.form || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS EDIT SITEPAR STATION'], data: result };
  });

  /** RPC: OOPS DELETE WITNESS (ARRAY) — 2 param(s) */
  server.post('/vista/oops/rpc/oops-delete-witness', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS DELETE WITNESS', [q.input || '', q.oops_change_cas || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS DELETE WITNESS'], data: result };
  });

  /** RPC: OOPS WITNESS CREATE (ARRAY) — 4 param(s) */
  server.post('/vista/oops/rpc/oops-witness-create', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS WITNESS CREATE', [q.ien || '', q.info || '', q.cmnt || '', q.comment || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS WITNESS CREATE'], data: result };
  });

  /** RPC: OOPS WITNESS EDIT (ARRAY) — 3 param(s) */
  server.get('/vista/oops/rpc/oops-witness-edit', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS WITNESS EDIT', [q.input || '', q.info || '', q.cmnt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS WITNESS EDIT'], data: result };
  });

  /** RPC: OOPS WITNESS DELETE (ARRAY) — 1 param(s) */
  server.post('/vista/oops/rpc/oops-witness-delete', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS WITNESS DELETE', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS WITNESS DELETE'], data: result };
  });

  /** RPC: OOPS EDIT SITE PARAMETER (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-edit-site-parameter', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS EDIT SITE PARAMETER', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS EDIT SITE PARAMETER'], data: result };
  });

  /** RPC: OOPS APPROVE SIGN FOR EMPLOYEE (ARRAY) — 1 param(s) */
  server.post('/vista/oops/rpc/oops-approve-sign-for-employee', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS APPROVE SIGN FOR EMPLOYEE', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS APPROVE SIGN FOR EMPLOYEE'], data: result };
  });

  /** RPC: OOPS VALIDATE AND SIGN (ARRAY) — 2 param(s) */
  server.post('/vista/oops/rpc/oops-validate-and-sign', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS VALIDATE AND SIGN', [q.input || '', q.sign || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS VALIDATE AND SIGN'], data: result };
  });

  /** RPC: OOPS REPLACE MULTIPLE (ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-replace-multiple', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS REPLACE MULTIPLE', [q.single || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS REPLACE MULTIPLE'], data: result };
  });

  /** RPC: OOPS UNION CONSENT (ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-union-consent', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS UNION CONSENT', [q.ien || '', q.unirep || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS UNION CONSENT'], data: result };
  });

  /** RPC: OOPS GET STATION INFORMATION (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-station-information', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET STATION INFORMATION', [q.statien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET STATION INFORMATION'], data: result };
  });

  /** RPC: OOPS MANUAL XMIT DATA (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-manual-xmit-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS MANUAL XMIT DATA', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS MANUAL XMIT DATA'], data: result };
  });

  /** RPC: OOPS INCIDENT REPORT (ARRAY) — 6 param(s) */
  server.get('/vista/oops/rpc/oops-incident-report', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS INCIDENT REPORT', [q.rpttyp || '', q.cstat || '', q.stdt || '', q.enddt || '', q.ltntt || '', q.stat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS INCIDENT REPORT'], data: result };
  });

  /** RPC: OOPS WCEDIT (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/oops/rpc/oops-wcedit', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS WCEDIT', [q.ien || '', q.caller || '', q.form || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS WCEDIT'], data: result };
  });

  /** RPC: OOPS GET OSHA DATA (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-get-osha-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET OSHA DATA', [q.input || '', q.call || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET OSHA DATA'], data: result };
  });

  /** RPC: OOPS GET PRT ACC STATUS RPT (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-get-prt-acc-status-rpt', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET PRT ACC STATUS RPT', [q.input || '', q.call || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET PRT ACC STATUS RPT'], data: result };
  });

  /** RPC: OOPS CLEAR SIGNATURE (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/oops/rpc/oops-clear-signature', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS CLEAR SIGNATURE', [q.ien || '', q.form || '', q.call || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS CLEAR SIGNATURE'], data: result };
  });

  /** RPC: OOPS NEEDLESTICK LOG (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-needlestick-log', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS NEEDLESTICK LOG', [q.input || '', q.call || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS NEEDLESTICK LOG'], data: result };
  });

  /** RPC: OOPS GET NOI CODE (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-noi-code', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET NOI CODE', [q.opt || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET NOI CODE'], data: result };
  });

  /** RPC: OOPS SET RECORD LOCK (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/oops/rpc/oops-set-record-lock', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SET RECORD LOCK', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SET RECORD LOCK'], data: result };
  });

  /** RPC: OOPS RELEASE RECORD LOCK (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/oops/rpc/oops-release-record-lock', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS RELEASE RECORD LOCK', [q.ien || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS RELEASE RECORD LOCK'], data: result };
  });

  /** RPC: OOPS GET ASISTS CASE (ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-asists-case', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET ASISTS CASE', [q.name || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET ASISTS CASE'], data: result };
  });

  /** RPC: OOPS CHECK PAID EMP DATA (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-check-paid-emp-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS CHECK PAID EMP DATA', [q.ien || '', q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS CHECK PAID EMP DATA'], data: result };
  });

  /** RPC: OOPS GET SINGLE FIELD (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-get-single-field', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET SINGLE FIELD', [q.ien || '', q.fld || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET SINGLE FIELD'], data: result };
  });

  /** RPC: OOPS GET INSTITUTIONS (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/oops/rpc/oops-get-institutions', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('OOPS GET INSTITUTIONS', []);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET INSTITUTIONS'], data: result };
  });

  /** RPC: OOPS SENSITIVE DATA (SINGLE VALUE) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-sensitive-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SENSITIVE DATA', [q.sduz || '', q.emp || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SENSITIVE DATA'], data: result };
  });

  /** RPC: OOPS GET MISC REPORT DATA (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-get-misc-report-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET MISC REPORT DATA', [q.input || '', q.report || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET MISC REPORT DATA'], data: result };
  });

  /** RPC: OOPS GET FAC SHORT LIST (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/oops/rpc/oops-get-fac-short-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('OOPS GET FAC SHORT LIST', []);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET FAC SHORT LIST'], data: result };
  });

  /** RPC: OOPS SELECT CA7 (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-select-ca7', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SELECT CA7', [q.person || '', q.call || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SELECT CA7'], data: result };
  });

  /** RPC: OOPS LIST CAS (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-list-cas', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS LIST CAS', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS LIST CAS'], data: result };
  });

  /** RPC: OOPS MULTIPLE DATA (ARRAY) — 2 param(s) */
  server.get('/vista/oops/rpc/oops-multiple-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS MULTIPLE DATA', [q.input || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS MULTIPLE DATA'], data: result };
  });

  /** RPC: OOPS SET DUAL BENEFITS DATA (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/oops/rpc/oops-set-dual-benefits-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SET DUAL BENEFITS DATA', [q.input || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SET DUAL BENEFITS DATA'], data: result };
  });

  /** RPC: OOPS SIGN CA7 (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/oops/rpc/oops-sign-ca7', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SIGN CA7', [q.input || '', q.sign || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SIGN CA7'], data: result };
  });

  /** RPC: OOPS SIGNATURE VALIDATION (SINGLE VALUE) — 3 param(s) */
  server.get('/vista/oops/rpc/oops-signature-validation', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SIGNATURE VALIDATION', [q.ien || '', q.call || '', q.form || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SIGNATURE VALIDATION'], data: result };
  });

  /** RPC: OOPS ZIP CODE MISMATCH CHECK (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-zip-code-mismatch-check', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS ZIP CODE MISMATCH CHECK', [q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS ZIP CODE MISMATCH CHECK'], data: result };
  });

  /** RPC: OOPS SET OSHA300A (SINGLE VALUE) — 2 param(s) */
  server.post('/vista/oops/rpc/oops-set-osha300a', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SET OSHA300A', [q.sta || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SET OSHA300A'], data: result };
  });

  /** RPC: OOPS GET DETAIL LOCATION (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/oops/rpc/oops-get-detail-location', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS GET DETAIL LOCATION', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS GET DETAIL LOCATION'], data: result };
  });

  /** RPC: OOPS SET DETAIL LOCATION (ARRAY) — 2 param(s) */
  server.post('/vista/oops/rpc/oops-set-detail-location', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('OOPS SET DETAIL LOCATION', [q.parm1 || '', q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['OOPS SET DETAIL LOCATION'], data: result };
  });
}