// Auto-generated by vista-module-gen for Pharmacy Enterprise Customization System (PREC)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package PREC
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function precRoutes(server: FastifyInstance) {
}