// Auto-generated by vista-module-gen for Pharmacy Benefits Management (PSU)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package PSU
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function psuRoutes(server: FastifyInstance) {
}