// Auto-generated by vista-module-gen for PCE Patient Care Encounter (PX)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package PX
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function pxRoutes(server: FastifyInstance) {

  /** RPC: PXRM REMINDER CATEGORY (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-category', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER CATEGORY', [q.category || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER CATEGORY'], data: result };
  });

  /** RPC: PXRM REMINDERS AND CATEGORIES (ARRAY) — 0 param(s) */
  server.get('/vista/px/rpc/pxrm-reminders-and-categories', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('PXRM REMINDERS AND CATEGORIES', []);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDERS AND CATEGORIES'], data: result };
  });

  /** RPC: ORQQPX GET NOT PURPOSE (ARRAY) — 0 param(s) */
  server.get('/vista/px/rpc/orqqpx-get-not-purpose', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('ORQQPX GET NOT PURPOSE', []);
    return { ok: true, source: 'vista', rpcUsed: ['ORQQPX GET NOT PURPOSE'], data: result };
  });

  /** RPC: ORQQPXRM GET WH PROC RESULT (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/orqqpxrm-get-wh-proc-result', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('ORQQPXRM GET WH PROC RESULT', [q.string || '']);
    return { ok: true, source: 'vista', rpcUsed: ['ORQQPXRM GET WH PROC RESULT'], data: result };
  });

  /** RPC: PXRM EDUCATION SUBTOPICS (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-education-subtopics', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM EDUCATION SUBTOPICS', [q.education_topic_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM EDUCATION SUBTOPICS'], data: result };
  });

  /** RPC: PXRM EDUCATION SUMMARY (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-education-summary', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM EDUCATION SUMMARY', [q.clinical_reminder_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM EDUCATION SUMMARY'], data: result };
  });

  /** RPC: PXRM EDUCATION TOPIC (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-education-topic', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM EDUCATION TOPIC', [q.education_topic_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM EDUCATION TOPIC'], data: result };
  });

  /** RPC: PXRM REMINDER CATEGORIES (ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-categories', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER CATEGORIES', [q.dfn || '', q.hospital_location || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER CATEGORIES'], data: result };
  });

  /** RPC: PXRM REMINDER DIALOG (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-dialog', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER DIALOG', [q.clinical_reminder_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER DIALOG'], data: result };
  });

  /** RPC: PXRM REMINDER DIALOG PROMPTS (ARRAY) — 3 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-dialog-prompts', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER DIALOG PROMPTS', [q.dialog_element_ien || '', q.current_historical || '', q.dialog_line_cpt_pov || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER DIALOG PROMPTS'], data: result };
  });

  /** RPC: PXRM REMINDER EVALUATION (ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-evaluation', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER EVALUATION', [q.dfn || '', q.reminder_array || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER EVALUATION'], data: result };
  });

  /** RPC: PXRM REMINDER INQUIRY (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-inquiry', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER INQUIRY', [q.clinical_reminder_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER INQUIRY'], data: result };
  });

  /** RPC: PXRM REMINDER WEB (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-web', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER WEB', [q.clinical_reminder_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER WEB'], data: result };
  });

  /** RPC: PXRM REMINDERS (UNEVALUATED) (ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxrm-reminders-unevaluated', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDERS (UNEVALUATED)', [q.dfn || '', q.hospital_location || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDERS (UNEVALUATED)'], data: result };
  });

  /** RPC: PXRM REMINDER DETAIL (ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-detail', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER DETAIL', [q.dfn || '', q.clinical_reminder_id || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER DETAIL'], data: result };
  });

  /** RPC: PXRM MENTAL HEALTH (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-mental-health', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM MENTAL HEALTH', [q.mental_health_instrument || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM MENTAL HEALTH'], data: result };
  });

  /** RPC: PXRM PROGRESS NOTE HEADER (SINGLE VALUE) — 1 param(s) */
  server.get('/vista/px/rpc/pxrm-progress-note-header', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM PROGRESS NOTE HEADER', [q.hospital_location || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM PROGRESS NOTE HEADER'], data: result };
  });

  /** RPC: PXRM MENTAL HEALTH RESULTS (ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxrm-mental-health-results', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM MENTAL HEALTH RESULTS', [q.test_results || '', q.result_group_element || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM MENTAL HEALTH RESULTS'], data: result };
  });

  /** RPC: PXRM MENTAL HEALTH SAVE (ARRAY) — 1 param(s) */
  server.post('/vista/px/rpc/pxrm-mental-health-save', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM MENTAL HEALTH SAVE', [q.test_results || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM MENTAL HEALTH SAVE'], data: result };
  });

  /** RPC: PXRM REMINDER RPC (ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxrm-reminder-rpc', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRM REMINDER RPC', [q.type || '', q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRM REMINDER RPC'], data: result };
  });

  /** RPC: PX SAVE DATA (SINGLE VALUE) — 4 param(s) */
  server.post('/vista/px/rpc/px-save-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PX SAVE DATA', [q.pcelist || '', q.loc || '', q.pkgname || '', q.src || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PX SAVE DATA'], data: result };
  });

  /** RPC: PXVIMM INFO SOURCE (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxvimm-info-source', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM INFO SOURCE', [q.filter || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM INFO SOURCE'], data: result };
  });

  /** RPC: PXVIMM ADMIN ROUTE (ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxvimm-admin-route', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM ADMIN ROUTE', [q.filter || '', q.pxvsites || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM ADMIN ROUTE'], data: result };
  });

  /** RPC: PXVIMM ADMIN SITE (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxvimm-admin-site', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM ADMIN SITE', [q.filter || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM ADMIN SITE'], data: result };
  });

  /** RPC: PXVIMM IMM LOT (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/px/rpc/pxvimm-imm-lot', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM IMM LOT', [q.filter || '', q.pxvi || '', q.pxloc || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM IMM LOT'], data: result };
  });

  /** RPC: PXVIMM IMM MAN (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/px/rpc/pxvimm-imm-man', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM IMM MAN', [q.filter || '', q.pxvdate || '', q.pxvi || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM IMM MAN'], data: result };
  });

  /** RPC: PXVIMM VIS (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxvimm-vis', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM VIS', [q.filter || '', q.pxvdate || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM VIS'], data: result };
  });

  /** RPC: PXVIMM IMMDATA (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/pxvimm-immdata', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM IMMDATA', [q.filter || '', q.subfiles || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM IMMDATA'], data: result };
  });

  /** RPC: PXVIMM ICR LIST (ARRAY) — 4 param(s) */
  server.get('/vista/px/rpc/pxvimm-icr-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM ICR LIST', [q.pxfile || '', q.filter || '', q.inst || '', q.loc || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM ICR LIST'], data: result };
  });

  /** RPC: PXVIMM VICR EVENTS (ARRAY) — 4 param(s) */
  server.get('/vista/px/rpc/pxvimm-vicr-events', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM VICR EVENTS', [q.dfn || '', q.pxvimm || '', q.pxdate || '', q.pxformat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM VICR EVENTS'], data: result };
  });

  /** RPC: PXVIMM IMM SHORT LIST (ARRAY) — 4 param(s) */
  server.get('/vista/px/rpc/pxvimm-imm-short-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM IMM SHORT LIST', [q.filter || '', q.pxdate || '', q.orexclude || '', q.location || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM IMM SHORT LIST'], data: result };
  });

  /** RPC: PXVIMM IMM DETAILED (GLOBAL ARRAY) — 3 param(s) */
  server.get('/vista/px/rpc/pxvimm-imm-detailed', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM IMM DETAILED', [q.pximm || '', q.pxdate || '', q.pxloc || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM IMM DETAILED'], data: result };
  });

  /** RPC: PXVIMM ADMIN CODES (ARRAY) — 3 param(s) */
  server.get('/vista/px/rpc/pxvimm-admin-codes', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM ADMIN CODES', [q.visit || '', q.pcelist || '', q.retcptdel || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM ADMIN CODES'], data: result };
  });

  /** RPC: PXVIMM IMM FORMAT (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxvimm-imm-format', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM IMM FORMAT', [q.input || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM IMM FORMAT'], data: result };
  });

  /** RPC: PXVIMM VIMM DATA (GLOBAL ARRAY) — 4 param(s) */
  server.get('/vista/px/rpc/pxvimm-vimm-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM VIMM DATA', [q.filter || '', q.list || '', q.date || '', q.demographics || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM VIMM DATA'], data: result };
  });

  /** RPC: PXVSK SKIN SHORT LIST (ARRAY) — 4 param(s) */
  server.get('/vista/px/rpc/pxvsk-skin-short-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVSK SKIN SHORT LIST', [q.date || '', q.filter || '', q.orexclude || '', q.location || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVSK SKIN SHORT LIST'], data: result };
  });

  /** RPC: PXVSK DEF SITES (ARRAY) — 0 param(s) */
  server.get('/vista/px/rpc/pxvsk-def-sites', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('PXVSK DEF SITES', []);
    return { ok: true, source: 'vista', rpcUsed: ['PXVSK DEF SITES'], data: result };
  });

  /** RPC: PXVSK V SKIN TEST LIST (ARRAY) — 4 param(s) */
  server.get('/vista/px/rpc/pxvsk-v-skin-test-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVSK V SKIN TEST LIST', [q.dfn || '', q.skintest || '', q.date || '', q.max || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVSK V SKIN TEST LIST'], data: result };
  });

  /** RPC: PXVIMM IMM DISCLOSURE (SINGLE VALUE) — 4 param(s) */
  server.get('/vista/px/rpc/pxvimm-imm-disclosure', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXVIMM IMM DISCLOSURE', [q.vimm || '', q.agency || '', q.date || '', q.timezone || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXVIMM IMM DISCLOSURE'], data: result };
  });

  /** RPC: PXRMRPCG GENFUPD (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrmrpcg-genfupd', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRMRPCG GENFUPD', [q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRMRPCG GENFUPD'], data: result };
  });

  /** RPC: PXRMRPCC PROMPTVL (SINGLE VALUE) — 4 param(s) */
  server.get('/vista/px/rpc/pxrmrpcc-promptvl', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRMRPCC PROMPTVL', [q.value || '', q.dien || '', q.ovalue || '', q.pat || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRMRPCC PROMPTVL'], data: result };
  });

  /** RPC: PXRMRPCG CANCEL (SINGLE VALUE) — 0 param(s) */
  server.post('/vista/px/rpc/pxrmrpcg-cancel', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('PXRMRPCG CANCEL', []);
    return { ok: true, source: 'vista', rpcUsed: ['PXRMRPCG CANCEL'], data: result };
  });

  /** RPC: PXRMRPCG VIEW (ARRAY) — 3 param(s) */
  server.get('/vista/px/rpc/pxrmrpcg-view', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRMRPCG VIEW', [q.pat || '', q.ien || '', q.value || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRMRPCG VIEW'], data: result };
  });

  /** RPC: PXRMRPCG GENFVALD (ARRAY) — 1 param(s) */
  server.get('/vista/px/rpc/pxrmrpcg-genfvald', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRMRPCG GENFVALD', [q.data || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRMRPCG GENFVALD'], data: result };
  });

  /** RPC: PX ICE WEB (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/px/rpc/px-ice-web', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PX ICE WEB', [q.dfn || '', q.cache || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PX ICE WEB'], data: result };
  });

  /** RPC: PXRPC SAVE2 (ARRAY) — 4 param(s) */
  server.get('/vista/px/rpc/pxrpc-save2', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('PXRPC SAVE2', [q.pcelist || '', q.pkgname || '', q.src || '', q.visit || '']);
    return { ok: true, source: 'vista', rpcUsed: ['PXRPC SAVE2'], data: result };
  });
}