// Auto-generated by vista-module-gen for Survey Generator (QAP)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package QAP
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function qapRoutes(server: FastifyInstance) {
}