// Auto-generated by vista-module-gen for Clinical Information Resource Network (RG)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package RG
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function rgRoutes(server: FastifyInstance) {

  /** RPC: RG REMOTE HL7 TASK (ARRAY) — 0 param(s) */
  server.get('/vista/rg/rpc/rg-remote-hl7-task', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RG REMOTE HL7 TASK', []);
    return { ok: true, source: 'vista', rpcUsed: ['RG REMOTE HL7 TASK'], data: result };
  });

  /** RPC: RG REM ACTIVITY (ARRAY) — 2 param(s) */
  server.get('/vista/rg/rpc/rg-rem-activity', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('RG REM ACTIVITY', [q.icn || '', q.ssn || '']);
    return { ok: true, source: 'vista', rpcUsed: ['RG REM ACTIVITY'], data: result };
  });

  /** RPC: RG VIEW VISTA EXCEPTIONS (ARRAY) — 5 param(s) */
  server.get('/vista/rg/rpc/rg-view-vista-exceptions', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('RG VIEW VISTA EXCEPTIONS', [q.icn || '', q.ssn || '', q.dfn || '', q.brange || '', q.erange || '']);
    return { ok: true, source: 'vista', rpcUsed: ['RG VIEW VISTA EXCEPTIONS'], data: result };
  });
}