// Auto-generated by vista-module-gen for Functional Independence (RMIM)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package RMIM
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function rmimRoutes(server: FastifyInstance) {

  /** RPC: RMIM CONVERT DATE (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-convert-date', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM CONVERT DATE', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM CONVERT DATE'], data: result };
  });

  /** RPC: RMIM SEND EMAIL (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-send-email', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM SEND EMAIL', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM SEND EMAIL'], data: result };
  });

  /** RPC: RMIM GET FORM (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-get-form', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM GET FORM', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM GET FORM'], data: result };
  });

  /** RPC: RMIM GET CASES (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-get-cases', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM GET CASES', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM GET CASES'], data: result };
  });

  /** RPC: RMIM GET SELECTED CASE (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-get-selected-case', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM GET SELECTED CASE', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM GET SELECTED CASE'], data: result };
  });

  /** RPC: RMIM GET USER INFO (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-get-user-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM GET USER INFO', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM GET USER INFO'], data: result };
  });

  /** RPC: RMIM GET DFN (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-get-dfn', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM GET DFN', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM GET DFN'], data: result };
  });

  /** RPC: RMIM FIM PARAMETER (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-fim-parameter', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM FIM PARAMETER', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM FIM PARAMETER'], data: result };
  });

  /** RPC: RMIM GET PATIENT DME (ARRAY) — 1 param(s) */
  server.get('/vista/rmim/rpc/rmim-get-patient-dme', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('RMIM GET PATIENT DME', [q.param1 || '']);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM GET PATIENT DME'], data: result };
  });

  /** RPC: RMIM SAVE FSOD (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/rmim/rpc/rmim-save-fsod', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('RMIM SAVE FSOD', [q.array || '']);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM SAVE FSOD'], data: result };
  });

  /** RPC: RMIM PATIENT LOOKUP (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-patient-lookup', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM PATIENT LOOKUP', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM PATIENT LOOKUP'], data: result };
  });

  /** RPC: RMIM PATIENT INFO (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-patient-info', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM PATIENT INFO', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM PATIENT INFO'], data: result };
  });

  /** RPC: RMIM AUTHOR LOOKUP (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-author-lookup', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM AUTHOR LOOKUP', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM AUTHOR LOOKUP'], data: result };
  });

  /** RPC: RMIM LOCATION LOOKUP (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-location-lookup', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM LOCATION LOOKUP', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM LOCATION LOOKUP'], data: result };
  });

  /** RPC: RMIM RESTRICTED RECORD (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-restricted-record', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM RESTRICTED RECORD', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM RESTRICTED RECORD'], data: result };
  });

  /** RPC: RMIM VERSION (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-version', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM VERSION', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM VERSION'], data: result };
  });

  /** RPC: RMIM CONSULT LIST (GLOBAL ARRAY) — 4 param(s) */
  server.get('/vista/rmim/rpc/rmim-consult-list', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('RMIM CONSULT LIST', [q.dfn || '', q.start_date || '', q.stop_date || '', q.service || '']);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM CONSULT LIST'], data: result };
  });

  /** RPC: RMIM LOCK PATIENT (ARRAY) — 0 param(s) */
  server.post('/vista/rmim/rpc/rmim-lock-patient', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM LOCK PATIENT', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM LOCK PATIENT'], data: result };
  });

  /** RPC: RMIM CHECK DUPLICATE (ARRAY) — 0 param(s) */
  server.get('/vista/rmim/rpc/rmim-check-duplicate', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('RMIM CHECK DUPLICATE', []);
    return { ok: true, source: 'vista', rpcUsed: ['RMIM CHECK DUPLICATE'], data: result };
  });
}