// Auto-generated by vista-module-gen for Social Work (SOW)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package SOW
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function sowRoutes(server: FastifyInstance) {
}