// Auto-generated by vista-module-gen for Virtual Patient Record (VPR)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package VPR
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function vprRoutes(server: FastifyInstance) {

  /** RPC: VPR GET PATIENT DATA (GLOBAL ARRAY) — 7 param(s) */
  server.get('/vista/vpr/rpc/vpr-get-patient-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('VPR GET PATIENT DATA', [q.dfn || '', q.type || '', q.start || '', q.stop || '', q.max || '', q.item || '', q.filter || '']);
    return { ok: true, source: 'vista', rpcUsed: ['VPR GET PATIENT DATA'], data: result };
  });

  /** RPC: VPR DATA VERSION (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/vpr/rpc/vpr-data-version', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('VPR DATA VERSION', []);
    return { ok: true, source: 'vista', rpcUsed: ['VPR DATA VERSION'], data: result };
  });

  /** RPC: VPR GET PATIENT DATA JSON (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/vpr/rpc/vpr-get-patient-data-json', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('VPR GET PATIENT DATA JSON', [q.filter || '']);
    return { ok: true, source: 'vista', rpcUsed: ['VPR GET PATIENT DATA JSON'], data: result };
  });

  /** RPC: VPR GET CHECKSUM (GLOBAL ARRAY) — 1 param(s) */
  server.get('/vista/vpr/rpc/vpr-get-checksum', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('VPR GET CHECKSUM', [q.filter || '']);
    return { ok: true, source: 'vista', rpcUsed: ['VPR GET CHECKSUM'], data: result };
  });
}