// Auto-generated by vista-module-gen for Electronic Signature (XOBE)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package XOBE
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function xobeRoutes(server: FastifyInstance) {

  /** RPC: XOBE ESIG GET CODE (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/xobe/rpc/xobe-esig-get-code', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XOBE ESIG GET CODE', []);
    return { ok: true, source: 'vista', rpcUsed: ['XOBE ESIG GET CODE'], data: result };
  });

  /** RPC: XOBE ESIG SET CODE (SINGLE VALUE) — 1 param(s) */
  server.post('/vista/xobe/rpc/xobe-esig-set-code', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('XOBE ESIG SET CODE', [q.esig || '']);
    return { ok: true, source: 'vista', rpcUsed: ['XOBE ESIG SET CODE'], data: result };
  });

  /** RPC: XOBE ESIG GET DATA (ARRAY) — 0 param(s) */
  server.get('/vista/xobe/rpc/xobe-esig-get-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XOBE ESIG GET DATA', []);
    return { ok: true, source: 'vista', rpcUsed: ['XOBE ESIG GET DATA'], data: result };
  });

  /** RPC: XOBE ESIG SET DATA (ARRAY) — 1 param(s) */
  server.post('/vista/xobe/rpc/xobe-esig-set-data', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('XOBE ESIG SET DATA', [q.values || '']);
    return { ok: true, source: 'vista', rpcUsed: ['XOBE ESIG SET DATA'], data: result };
  });

  /** RPC: XOBE ESIG IS DEFINED (SINGLE VALUE) — 0 param(s) */
  server.get('/vista/xobe/rpc/xobe-esig-is-defined', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XOBE ESIG IS DEFINED', []);
    return { ok: true, source: 'vista', rpcUsed: ['XOBE ESIG IS DEFINED'], data: result };
  });
}