// Auto-generated by vista-module-gen for Toolkit (XT)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package XT
import type { FastifyInstance } from 'fastify';
import { requireSession } from '../../auth/auth-routes.js';
import { safeCallRpc } from '../../lib/rpc-resilience.js';

export async function xtRoutes(server: FastifyInstance) {

  /** RPC: XTMUNIT-TEST LOAD (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xtmunit-test-load', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTMUNIT-TEST LOAD', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTMUNIT-TEST LOAD'], data: result };
  });

  /** RPC: XTMUNIT-TEST NEXT (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xtmunit-test-next', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTMUNIT-TEST NEXT', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTMUNIT-TEST NEXT'], data: result };
  });

  /** RPC: XTMUNIT-TEST GROUP LOAD (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xtmunit-test-group-load', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTMUNIT-TEST GROUP LOAD', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTMUNIT-TEST GROUP LOAD'], data: result };
  });

  /** RPC: XT ECLIPSE M EDITOR (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xt-eclipse-m-editor', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XT ECLIPSE M EDITOR', []);
    return { ok: true, source: 'vista', rpcUsed: ['XT ECLIPSE M EDITOR'], data: result };
  });

  /** RPC: XTDEBUG DO LINE (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xtdebug-do-line', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG DO LINE', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG DO LINE'], data: result };
  });

  /** RPC: XTDEBUG NEXT (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xtdebug-next', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG NEXT', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG NEXT'], data: result };
  });

  /** RPC: XTDEBUG START (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xtdebug-start', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG START', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG START'], data: result };
  });

  /** RPC: XTDEBUG SYMBOL TABLE (GLOBAL ARRAY) — 0 param(s) */
  server.get('/vista/xt/rpc/xtdebug-symbol-table', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG SYMBOL TABLE', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG SYMBOL TABLE'], data: result };
  });

  /** RPC: XTDEBUG ADD BREAKPOINT (GLOBAL ARRAY) — 0 param(s) */
  server.post('/vista/xt/rpc/xtdebug-add-breakpoint', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG ADD BREAKPOINT', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG ADD BREAKPOINT'], data: result };
  });

  /** RPC: XTDEBUG ADD WATCH (GLOBAL ARRAY) — 0 param(s) */
  server.post('/vista/xt/rpc/xtdebug-add-watch', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG ADD WATCH', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG ADD WATCH'], data: result };
  });

  /** RPC: XTDEBUG DELETE BREAK (GLOBAL ARRAY) — 0 param(s) */
  server.post('/vista/xt/rpc/xtdebug-delete-break', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG DELETE BREAK', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG DELETE BREAK'], data: result };
  });

  /** RPC: XTDEBUG DELETE WATCH (GLOBAL ARRAY) — 0 param(s) */
  server.post('/vista/xt/rpc/xtdebug-delete-watch', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const result = await safeCallRpc('XTDEBUG DELETE WATCH', []);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG DELETE WATCH'], data: result };
  });

  /** RPC: XTDEBUG READ INPUT (GLOBAL ARRAY) — 2 param(s) */
  server.get('/vista/xt/rpc/xtdebug-read-input', async (request, reply) => {
    const session = await requireSession(request, reply);
    if (!session) return;
    const q = (request.query || request.body || {}) as Record<string, string>;
    const result = await safeCallRpc('XTDEBUG READ INPUT', [q.xtdebval || '', q.timedout || '']);
    return { ok: true, source: 'vista', rpcUsed: ['XTDEBUG READ INPUT'], data: result };
  });
}