services:
  wv:
    image: worldvista/worldvista-ehr:latest
    container_name: wv
    profiles: ["dev"]
    ports:
      - "2222:22"
      - "9430:9430"
      - "8001:8001"
      - "8080:8080"
      - "9080:9080"
    stdin_open: true
    tty: true
    restart: unless-stopped
