ZVEFFLD ; VistA-Evolved - Probe field numbers for all admin files
 ;
PROBE ;
 N U S U="^"
 ; File #200 - NEW PERSON (users)
 D FIELDS(200,"File #200 NEW PERSON")
 ; File #42 - WARD LOCATION
 D FIELDS(42,"File #42 WARD LOCATION")
 ; File #50 - DRUG
 D FIELDS(50,"File #50 DRUG")
 ; File #60 - LABORATORY TEST
 D FIELDS(60,"File #60 LABORATORY TEST")
 ; File #36 - IB SITE PARAMETERS
 D FIELDS(36,"File #36 IB SITE PARAMETERS")
 ; File #350.9 - INSURANCE TYPE
 D FIELDS(350.9,"File #350.9 INSURANCE TYPE")
 ; File #4 - INSTITUTION
 D FIELDS(4,"File #4 INSTITUTION")
 ; File #40.8 - MEDICAL CENTER DIVISION
 D FIELDS(40.8,"File #40.8 MED CTR DIVISION")
 ; File #49 - SERVICE/SECTION
 D FIELDS(49,"File #49 SERVICE/SECTION")
 ; File #8989.3 - KERNEL SYSTEM PARAMETERS
 D FIELDS(8989.3,"File #8989.3 KERNEL SYS PARAMS")
 Q
 ;
FIELDS(FILENUM,LABEL) ;
 N FLD,NAME,CT
 W !,"==== "_LABEL_" ====",!
 S FLD=0,CT=0
 F  S FLD=$O(^DD(FILENUM,FLD)) Q:'FLD  D
 . S NAME=$P($G(^DD(FILENUM,FLD,0)),U,1)
 . I NAME="" Q
 . S CT=CT+1
 . I CT<80 W "  "_FLD_"="_NAME,!
 W "  ... total fields: "_CT,!
 Q
