ZVELAB ;VE;Laboratory Admin RPCs;2026-03-09
 ;
 ; Custom RPCs for lab admin operations.
 ; File #60 (LABORATORY TEST), File #62 (COLLECTION SAMPLE), File #69.9 (LAB SITE)
 ; Read RPCs: TESTLIST, TESTDET, COLLSAMP, URGENCY
 ; Write RPCs: TESTEDT
 ;
TESTLIST(RESULT,SEARCH,COUNT) ;List lab tests from File #60
 N IEN,NM,I,U,MAXCT,TYPE
 S U="^",I=0,MAXCT=+$G(COUNT)
 I MAXCT<1 S MAXCT=200
 I MAXCT>1000 S MAXCT=1000
 S SEARCH=$G(SEARCH)
 I SEARCH'="" D  Q
 . S NM=SEARCH
 . F  S NM=$O(^LAB(60,"B",NM)) Q:NM=""  Q:$E(NM,1,$L(SEARCH))'=SEARCH  Q:I>=MAXCT  D
 . . S IEN=$O(^LAB(60,"B",NM,""))
 . . Q:'IEN
 . . S TYPE=$P($G(^LAB(60,IEN,0)),U,3)
 . . S I=I+1
 . . S RESULT(I)=IEN_U_NM_U_TYPE_U_$P($G(^LAB(60,IEN,0)),U,4)
 . S RESULT(0)=I
 S IEN=0
 F  S IEN=$O(^LAB(60,IEN)) Q:'IEN  Q:I>=MAXCT  D
 . S NM=$P($G(^LAB(60,IEN,0)),U,1)
 . Q:NM=""
 . S TYPE=$P($G(^LAB(60,IEN,0)),U,3)
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_TYPE_U_$P($G(^LAB(60,IEN,0)),U,4)
 S RESULT(0)=I
 Q
 ;
TESTDET(RESULT,TESTIEN) ;Get lab test detail from File #60
 N U,Z0
 S U="^",TESTIEN=+$G(TESTIEN)
 I 'TESTIEN S RESULT(0)="-1^Test IEN required" Q
 I '$D(^LAB(60,TESTIEN,0)) S RESULT(0)="-1^Test not found" Q
 S Z0=^LAB(60,TESTIEN,0)
 S RESULT(0)="1^OK"
 S RESULT(1)="IEN^"_TESTIEN
 S RESULT(2)="NAME^"_$P(Z0,U,1)
 S RESULT(3)="TYPE^"_$P(Z0,U,3)
 S RESULT(4)="SUBSCRIPT^"_$P(Z0,U,4)
 S RESULT(5)="LOCATION_TYPE^"_$P(Z0,U,5)
 S RESULT(6)="COLLECTION_SAMPLE^"_$P(Z0,U,9)
 S RESULT(7)="SITE_NOTES^"_$G(^LAB(60,TESTIEN,.1))
 Q
 ;
COLLSAMP(RESULT) ;List collection samples from File #62
 N IEN,NM,I,U
 S U="^",I=0,IEN=0
 F  S IEN=$O(^LAB(62,IEN)) Q:'IEN  D
 . S NM=$P($G(^LAB(62,IEN,0)),U,1)
 . Q:NM=""
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^LAB(62,IEN,0)),U,2)
 S RESULT(0)=I
 Q
 ;
URGENCY(RESULT) ;List urgency types from File #62.05
 N IEN,NM,I,U
 S U="^",I=0,IEN=0
 F  S IEN=$O(^LAB(62.05,IEN)) Q:'IEN  D
 . S NM=$P($G(^LAB(62.05,IEN,0)),U,1)
 . Q:NM=""
 . S I=I+1
 . S RESULT(I)=IEN_U_NM
 S RESULT(0)=I
 Q
 ;
TESTEDT(RESULT,TESTIEN,FIELD,VALUE) ;Edit lab test fields in File #60
 ; FIELD: NAME, TYPE, SUBSCRIPT, COLLECTION_SAMPLE
 N U,FDA,IENS,ERR,FLDNUM
 S U="^",TESTIEN=+$G(TESTIEN)
 I 'TESTIEN S RESULT(0)="-1^Test IEN required" Q
 I '$D(^LAB(60,TESTIEN,0)) S RESULT(0)="-1^Test not found" Q
 S FIELD=$G(FIELD),VALUE=$G(VALUE)
 I FIELD="" S RESULT(0)="-1^Field name required" Q
 S FLDNUM=""
 I FIELD="NAME" S FLDNUM=.01
 I FIELD="TYPE" S FLDNUM=.03
 I FIELD="SUBSCRIPT" S FLDNUM=.04
 I FIELD="COLLECTION_SAMPLE" S FLDNUM=.09
 I FIELD="LOCATION_TYPE" S FLDNUM=.05
 I FLDNUM="" S RESULT(0)="-1^Unknown field: "_FIELD Q
 S IENS=TESTIEN_","
 S FDA(60,IENS,FLDNUM)=VALUE
 D FILE^DIE("E","FDA","ERR")
 I $D(ERR) S RESULT(0)="-1^"_$G(ERR("DIERR",1,"TEXT",1)) Q
 S RESULT(0)="1^OK"
 Q
 ;
INSTALL ;Register RPCs in File #8994
 ; Read RPCs
 D REG^ZVEUSER("VE LAB TEST LIST","TESTLIST","ZVELAB")
 D REG^ZVEUSER("VE LAB TEST DETAIL","TESTDET","ZVELAB")
 D REG^ZVEUSER("VE LAB COLL SAMP","COLLSAMP","ZVELAB")
 D REG^ZVEUSER("VE LAB URGENCY","URGENCY","ZVELAB")
 ; Write RPCs
 D REG^ZVEUSER("VE LAB TEST EDIT","TESTEDT","ZVELAB")
 W "ZVELAB RPCs registered",!
 Q
