ZVEPHAR ;VE;Pharmacy Admin RPCs;2026-03-09
 ;
 ; Custom RPCs for pharmacy admin operations.
 ; File #50 (DRUG), File #59 (OUTPATIENT SITE)
 ; Read RPCs: DRUGLIST, DRUGDET, ROUTES, SCHEDULES
 ; Write RPCs: DRUGEDT
 ;
DRUGLIST(RESULT,SEARCH,COUNT) ;List drugs from File #50
 N IEN,NM,I,U,MAXCT,CLASS
 S U="^",I=0,MAXCT=+$G(COUNT)
 I MAXCT<1 S MAXCT=200
 I MAXCT>1000 S MAXCT=1000
 S SEARCH=$G(SEARCH)
 I SEARCH="" D  Q
 . S IEN=0
 . F  S IEN=$O(^PSDRUG(IEN)) Q:'IEN  Q:I>=MAXCT  D
 . . S NM=$P($G(^PSDRUG(IEN,0)),U,1)
 . . Q:NM=""
 . . S CLASS=$P($G(^PSDRUG(IEN,0)),U,2)
 . . S I=I+1
 . . S RESULT(I)=IEN_U_NM_U_CLASS_U_$$FORMSTAT(IEN)
 . S RESULT(0)=I
 S NM=SEARCH
 F  S NM=$O(^PSDRUG("B",NM)) Q:NM=""  Q:$E(NM,1,$L(SEARCH))'=SEARCH  Q:I>=MAXCT  D
 . S IEN=$O(^PSDRUG("B",NM,""))
 . Q:'IEN
 . S CLASS=$P($G(^PSDRUG(IEN,0)),U,2)
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_CLASS_U_$$FORMSTAT(IEN)
 S RESULT(0)=I
 Q
 ;
DRUGDET(RESULT,DRUGIEN) ;Get drug detail from File #50
 N U,Z0
 S U="^",DRUGIEN=+$G(DRUGIEN)
 I 'DRUGIEN S RESULT(0)="-1^Drug IEN required" Q
 I '$D(^PSDRUG(DRUGIEN,0)) S RESULT(0)="-1^Drug not found" Q
 S Z0=^PSDRUG(DRUGIEN,0)
 S RESULT(0)="1^OK"
 S RESULT(1)="IEN^"_DRUGIEN
 S RESULT(2)="NAME^"_$P(Z0,U,1)
 S RESULT(3)="VA_CLASS^"_$P(Z0,U,2)
 S RESULT(4)="DEA_SCHEDULE^"_$P(Z0,U,3)
 S RESULT(5)="UNIT_DOSE^"_$P($G(^PSDRUG(DRUGIEN,660)),U,6)
 S RESULT(6)="FORMULARY^"_$$FORMSTAT(DRUGIEN)
 S RESULT(7)="NATIONAL_DRUG_FILE^"_$P($G(^PSDRUG(DRUGIEN,"ND")),U,1)
 S RESULT(8)="ORDER_UNIT^"_$P($G(^PSDRUG(DRUGIEN,660)),U,8)
 S RESULT(9)="DISPENSE_UNIT^"_$P($G(^PSDRUG(DRUGIEN,660)),U,9)
 Q
 ;
FORMSTAT(IEN) ;Get formulary status
 N STAT
 S STAT=$P($G(^PSDRUG(IEN,"I")),U,1)
 I STAT="" Q "FORMULARY"
 Q "NON-FORMULARY"
 ;
ROUTES(RESULT) ;List medication routes from File #51
 N IEN,NM,I,U
 S U="^",I=0,IEN=0
 F  S IEN=$O(^PS(51,IEN)) Q:'IEN  D
 . S NM=$P($G(^PS(51,IEN,0)),U,1)
 . Q:NM=""
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^PS(51,IEN,0)),U,2)
 S RESULT(0)=I
 Q
 ;
SCHEDULES(RESULT) ;List medication schedules from File #51.1
 N IEN,NM,I,U
 S U="^",I=0,IEN=0
 F  S IEN=$O(^PS(51.1,IEN)) Q:'IEN  D
 . S NM=$P($G(^PS(51.1,IEN,0)),U,1)
 . Q:NM=""
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^PS(51.1,IEN,0)),U,2)
 S RESULT(0)=I
 Q
 ;
DRUGEDT(RESULT,DRUGIEN,FIELD,VALUE) ;Edit drug fields in File #50
 ; Limited to safe administrative fields only
 ; FIELD: VA_CLASS, FORMULARY_STATUS
 N U,FDA,IENS,ERR,FLDNUM
 S U="^",DRUGIEN=+$G(DRUGIEN)
 I 'DRUGIEN S RESULT(0)="-1^Drug IEN required" Q
 I '$D(^PSDRUG(DRUGIEN,0)) S RESULT(0)="-1^Drug not found" Q
 S FIELD=$G(FIELD),VALUE=$G(VALUE)
 I FIELD="" S RESULT(0)="-1^Field name required" Q
 S FLDNUM=""
 I FIELD="VA_CLASS" S FLDNUM=.02
 I FIELD="FORMULARY_STATUS" S FLDNUM=100
 I FIELD="ORDER_UNIT" S FLDNUM=14.5
 I FIELD="DISPENSE_UNIT" S FLDNUM=15
 I FLDNUM="" S RESULT(0)="-1^Unknown or restricted field: "_FIELD Q
 S IENS=DRUGIEN_","
 S FDA(50,IENS,FLDNUM)=VALUE
 D FILE^DIE("E","FDA","ERR")
 I $D(ERR) S RESULT(0)="-1^"_$G(ERR("DIERR",1,"TEXT",1)) Q
 S RESULT(0)="1^OK"
 Q
 ;
INSTALL ;Register RPCs in File #8994
 ; Read RPCs
 D REG^ZVEUSER("VE DRUG LIST","DRUGLIST","ZVEPHAR")
 D REG^ZVEUSER("VE DRUG DETAIL","DRUGDET","ZVEPHAR")
 D REG^ZVEUSER("VE MED ROUTES","ROUTES","ZVEPHAR")
 D REG^ZVEUSER("VE MED SCHEDULES","SCHEDULES","ZVEPHAR")
 ; Write RPCs
 D REG^ZVEUSER("VE DRUG EDIT","DRUGEDT","ZVEPHAR")
 W "ZVEPHAR RPCs registered",!
 Q
