ZVEWARD ;VE;Ward/Bed Admin RPCs;2026-03-09
 ;
 ; Custom RPCs for File #42 (WARD LOCATION) and bed management.
 ; Read RPCs: WARDLIST, WARDDET, CENSUS
 ; Write RPCs: WARDEDT
 ;
WARDLIST(RESULT) ;List wards from File #42
 N IEN,NM,I,U,BEDS,SPEC
 S U="^",I=0,IEN=0
 F  S IEN=$O(^DIC(42,IEN)) Q:'IEN  D
 . S NM=$P($G(^DIC(42,IEN,0)),U,1)
 . Q:NM=""
 . S BEDS=$P($G(^DIC(42,IEN,0)),U,2)
 . S SPEC=$P($G(^DIC(42,IEN,0)),U,3)
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_BEDS_U_SPEC_U_$$WARDOCC(IEN)
 S RESULT(0)=I
 Q
 ;
WARDDET(RESULT,WARDIEN) ;Get ward detail from File #42
 N U,Z0
 S U="^",WARDIEN=+$G(WARDIEN)
 I 'WARDIEN S RESULT(0)="-1^Ward IEN required" Q
 I '$D(^DIC(42,WARDIEN,0)) S RESULT(0)="-1^Ward not found" Q
 S Z0=^DIC(42,WARDIEN,0)
 S RESULT(0)="1^OK"
 S RESULT(1)="IEN^"_WARDIEN
 S RESULT(2)="NAME^"_$P(Z0,U,1)
 S RESULT(3)="BEDS^"_$P(Z0,U,2)
 S RESULT(4)="TREATING_SPEC^"_$P(Z0,U,3)
 S RESULT(5)="SERVICE^"_$P(Z0,U,4)
 S RESULT(6)="DIVISION^"_$P(Z0,U,11)
 S RESULT(7)="BEDSECTION^"_$P(Z0,U,42)
 S RESULT(8)="OCCUPANCY^"_$$WARDOCC(WARDIEN)
 Q
 ;
CENSUS(RESULT) ;Get census counts by ward
 N IEN,NM,I,U,OCC
 S U="^",I=0,IEN=0
 F  S IEN=$O(^DIC(42,IEN)) Q:'IEN  D
 . S NM=$P($G(^DIC(42,IEN,0)),U,1)
 . Q:NM=""
 . S OCC=$$WARDOCC(IEN)
 . S I=I+1
 . S RESULT(I)=IEN_U_NM_U_$P($G(^DIC(42,IEN,0)),U,2)_U_OCC
 S RESULT(0)=I
 Q
 ;
WARDOCC(WARDIEN) ;Count current patients in ward
 N CT,DFN
 S CT=0,DFN=0
 I '$D(^DPT("CN")) Q 0
 F  S DFN=$O(^DPT("CN",DFN)) Q:'DFN  D
 . I $P($G(^DPT(DFN,.1)),U,1)=WARDIEN S CT=CT+1
 Q CT
 ;
WARDEDT(RESULT,WARDIEN,FIELD,VALUE) ;Edit ward fields in File #42
 ; FIELD: NAME, BEDS, TREATING_SPEC, SERVICE, DIVISION
 N U,FDA,IENS,ERR,FLDNUM
 S U="^",WARDIEN=+$G(WARDIEN)
 I 'WARDIEN S RESULT(0)="-1^Ward IEN required" Q
 I '$D(^DIC(42,WARDIEN,0)) S RESULT(0)="-1^Ward not found" Q
 S FIELD=$G(FIELD),VALUE=$G(VALUE)
 I FIELD="" S RESULT(0)="-1^Field name required" Q
 S FLDNUM=""
 I FIELD="NAME" S FLDNUM=.01
 I FIELD="BEDS" S FLDNUM=.02
 I FIELD="TREATING_SPEC" S FLDNUM=.03
 I FIELD="SERVICE" S FLDNUM=.04
 I FIELD="DIVISION" S FLDNUM=.11
 I FLDNUM="" S RESULT(0)="-1^Unknown field: "_FIELD Q
 S IENS=WARDIEN_","
 S FDA(42,IENS,FLDNUM)=VALUE
 D FILE^DIE("E","FDA","ERR")
 I $D(ERR) S RESULT(0)="-1^"_$G(ERR("DIERR",1,"TEXT",1)) Q
 S RESULT(0)="1^OK"
 Q
 ;
INSTALL ;Register RPCs in File #8994
 ; Read RPCs
 D REG^ZVEUSER("VE WARD LIST","WARDLIST","ZVEWARD")
 D REG^ZVEUSER("VE WARD DETAIL","WARDDET","ZVEWARD")
 D REG^ZVEUSER("VE CENSUS","CENSUS","ZVEWARD")
 ; Write RPCs
 D REG^ZVEUSER("VE WARD EDIT","WARDEDT","ZVEWARD")
 W "ZVEWARD RPCs registered",!
 Q
