apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "ve-shared.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
