// Auto-generated by vista-module-gen for Patch Module (A1AE)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package A1AE

export const PACKAGE_NS = 'A1AE';
export const PACKAGE_NAME = 'Patch Module';
