// Auto-generated by vista-module-gen for E Claims Management Engine (BPS)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package BPS

export const PACKAGE_NS = 'BPS';
export const PACKAGE_NAME = 'E Claims Management Engine';

/** RPCs available for this package */
export const BPS_RPCS = {
  BPS_TAS_CLAIM_DATA_EXTRACT: 'BPS TAS CLAIM DATA EXTRACT',
  BPS_TAS_TXN_IENS_NEW: 'BPS TAS TXN IENS NEW',
  BPS_TAS_CLAIM_WRITE_BACK: 'BPS TAS CLAIM WRITE BACK',
  BPS_TAS_DATABASE_RESET: 'BPS TAS DATABASE RESET',
} as const;

export type BpsRpcName = typeof BPS_RPCS[keyof typeof BPS_RPCS];