// Auto-generated by vista-module-gen for Beneficiary Travel (DGBT)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package DGBT

export const PACKAGE_NS = 'DGBT';
export const PACKAGE_NAME = 'Beneficiary Travel';

/** RPCs available for this package */
export const DGBT_RPCS = {
  DGBT_CLAIM_DEDUCTIBLE_PAID: 'DGBT CLAIM DEDUCTIBLE PAID',
} as const;

export type DgbtRpcName = typeof DGBT_RPCS[keyof typeof DGBT_RPCS];