// Auto-generated by vista-module-gen for VA FileMan (DI)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package DI

export const PACKAGE_NS = 'DI';
export const PACKAGE_NAME = 'VA FileMan';
