// Auto-generated by vista-module-gen for Interim Management Support (ECT)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package ECT

export const PACKAGE_NS = 'ECT';
export const PACKAGE_NAME = 'Interim Management Support';
