// Auto-generated by vista-module-gen for General Medical Record - IO (GMRY)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package GMRY

export const PACKAGE_NS = 'GMRY';
export const PACKAGE_NAME = 'General Medical Record - IO';
