// Auto-generated by vista-module-gen for Utilization Management Rollup (IBQ)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package IBQ

export const PACKAGE_NS = 'IBQ';
export const PACKAGE_NAME = 'Utilization Management Rollup';
