// Auto-generated by vista-module-gen for IV (IV)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package IV

export const PACKAGE_NS = 'IV';
export const PACKAGE_NAME = 'IV';
