// Auto-generated by vista-module-gen for Library (LBR)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package LBR

export const PACKAGE_NS = 'LBR';
export const PACKAGE_NAME = 'Library';
