// Auto-generated by vista-module-gen for Oncology (ONC)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package ONC

export const PACKAGE_NS = 'ONC';
export const PACKAGE_NAME = 'Oncology';

/** RPCs available for this package */
export const ONC_RPCS = {
  ONC_VACCR_RPC: 'ONC VACCR RPC',
} as const;

export type OncRpcName = typeof ONC_RPCS[keyof typeof ONC_RPCS];