// Auto-generated by vista-module-gen for Inpatient Medications (PSJ)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package PSJ

export const PACKAGE_NS = 'PSJ';
export const PACKAGE_NAME = 'Inpatient Medications';
