// Auto-generated by vista-module-gen for Pharmacy Benefits Management (PSU)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package PSU

export const PACKAGE_NS = 'PSU';
export const PACKAGE_NAME = 'Pharmacy Benefits Management';
