// Auto-generated by vista-module-gen for QA (QA)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package QA

export const PACKAGE_NS = 'QA';
export const PACKAGE_NAME = 'QA';
