// Auto-generated by vista-module-gen for Clinical Monitoring System (QAM)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package QAM

export const PACKAGE_NS = 'QAM';
export const PACKAGE_NAME = 'Clinical Monitoring System';
