// Auto-generated by vista-module-gen for Radiology Nuclear Medicine (RA)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package RA

export const PACKAGE_NS = 'RA';
export const PACKAGE_NAME = 'Radiology Nuclear Medicine';

/** RPCs available for this package */
export const RA_RPCS = {
  RAMAG_EXAM_ORDER: 'RAMAG EXAM ORDER',
  RAMAG_EXAM_REGISTER: 'RAMAG EXAM REGISTER',
  RAMAG_ORDER_CANCEL: 'RAMAG ORDER CANCEL',
  RAMAG_EXAM_CANCEL: 'RAMAG EXAM CANCEL',
  RAMAG_EXAM_COMPLETE: 'RAMAG EXAM COMPLETE',
  RAMAG_EXAMINED: 'RAMAG EXAMINED',
  RAMAG_EXAM_STATUS_REQUIREMENTS: 'RAMAG EXAM STATUS REQUIREMENTS',
} as const;

export type RaRpcName = typeof RA_RPCS[keyof typeof RA_RPCS];