// Auto-generated by vista-module-gen for Remote Order Entry System (RMPF)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package RMPF

export const PACKAGE_NS = 'RMPF';
export const PACKAGE_NAME = 'Remote Order Entry System';

/** RPCs available for this package */
export const RMPF_RPCS = {
  RMPFDEMOG: 'RMPFDEMOG',
} as const;

export type RmpfRpcName = typeof RMPF_RPCS[keyof typeof RMPF_RPCS];