// Auto-generated by vista-module-gen for List Manager (VALM)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package VALM

export const PACKAGE_NS = 'VALM';
export const PACKAGE_NAME = 'List Manager';
