// Auto-generated by vista-module-gen for Patient Data Exchange (VAQ)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package VAQ

export const PACKAGE_NS = 'VAQ';
export const PACKAGE_NAME = 'Patient Data Exchange';
