// Auto-generated by vista-module-gen for VPE Shell (VEEM)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package VEEM

export const PACKAGE_NS = 'VEEM';
export const PACKAGE_NAME = 'VPE Shell';
