// Auto-generated by vista-module-gen for Integrated Home Telehealth (WEBI)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package WEBI

export const PACKAGE_NS = 'WEBI';
export const PACKAGE_NAME = 'Integrated Home Telehealth';
