// Auto-generated by vista-module-gen for Womens Health (WV)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package WV

export const PACKAGE_NS = 'WV';
export const PACKAGE_NAME = 'Womens Health';

/** RPCs available for this package */
export const WV_RPCS = {
  ORQQPXRM_GET_WH_LETTER_TEXT: 'ORQQPXRM GET WH LETTER TEXT',
  ORQQPXRM_GET_WH_LETTER_TYPE: 'ORQQPXRM GET WH LETTER TYPE',
  WVRPCOR_COVER: 'WVRPCOR COVER',
  WVRPCOR_POSTREP: 'WVRPCOR POSTREP',
  WVRPCOR_SAVEDATA: 'WVRPCOR SAVEDATA',
  WVRPCOR_EIE: 'WVRPCOR EIE',
  WVRPCOR_REASONS: 'WVRPCOR REASONS',
  WVRPCOR_SITES: 'WVRPCOR SITES',
  WVRPCOR_CONSAVE: 'WVRPCOR CONSAVE',
  WVRPCOR_DETAIL: 'WVRPCOR DETAIL',
} as const;

export type WvRpcName = typeof WV_RPCS[keyof typeof WV_RPCS];