// Auto-generated by vista-module-gen for XPAR (XPAR)
// Do NOT edit manually -- regenerate with: node tools/vista-module-gen/cli.mjs --package XPAR

export const PACKAGE_NS = 'XPAR';
export const PACKAGE_NAME = 'XPAR';
