/**
 * routes/index.ts — Barrel import for all domain route plugins.
 *
 * Generated by tools/cprs-extract/generate-api-stubs.mjs
 * DO NOT EDIT BY HAND — re-run the generator to update.
 */

import type { FastifyInstance } from "fastify";

import problemsRoutes from "./problems.js";
import medsRoutes from "./meds.js";
import notesRoutes from "./notes.js";
import ordersRoutes from "./orders.js";
import labsRoutes from "./labs.js";
import reportsRoutes from "./reports.js";

/** Register all domain route plugins on the server. */
export async function registerDomainRoutes(server: FastifyInstance): Promise<void> {
  await server.register(problemsRoutes);
  await server.register(medsRoutes);
  await server.register(notesRoutes);
  await server.register(ordersRoutes);
  await server.register(labsRoutes);
  await server.register(reportsRoutes);
}

/** All scaffolded domains. */
export const SCAFFOLDED_DOMAINS = ["problems","meds","notes","orders","labs","reports"] as const;
