/**
 * routes/labs.ts — Labs domain RPC routes.
 *
 * Originally auto-generated by tools/cprs-extract/generate-api-stubs.mjs.
 * Phase 568: Priority lab RPCs wired to real VistA calls.
 * Phase 580: All lab RPC stubs wired to real VistA calls.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { requireSession } from '../auth/auth-routes.js';
import { safeCallRpc } from '../lib/rpc-resilience.js';
import { log } from '../lib/logger.js';
import { z } from 'zod';

/** RPC catalog entry for the labs domain. */
export interface LabsRpc {
  name: string;
  slug: string;
  isContext: boolean;
  referenceCount: number;
}

/** All RPCs in the labs domain. */
export const LABS_RPCS: LabsRpc[] = [
  { name: 'ORWDLR32 ABBSPEC', slug: 'orwdlr32-abbspec', isContext: false, referenceCount: 1 },
  { name: 'ORWDLR32 ALLSAMP', slug: 'orwdlr32-allsamp', isContext: false, referenceCount: 1 },
  { name: 'ORWDLR32 ALLSPEC', slug: 'orwdlr32-allspec', isContext: false, referenceCount: 1 },
  { name: 'ORWDLR32 DEF', slug: 'orwdlr32-def', isContext: false, referenceCount: 1 },
  {
    name: 'ORWDLR32 GET LAB TIMES',
    slug: 'orwdlr32-get-lab-times',
    isContext: false,
    referenceCount: 1,
  },
  { name: 'ORWDLR32 IC DEFAULT', slug: 'orwdlr32-ic-default', isContext: false, referenceCount: 1 },
  { name: 'ORWDLR32 IC VALID', slug: 'orwdlr32-ic-valid', isContext: false, referenceCount: 1 },
  {
    name: 'ORWDLR32 IMMED COLLECT',
    slug: 'orwdlr32-immed-collect',
    isContext: false,
    referenceCount: 1,
  },
  {
    name: 'ORWDLR32 LAB COLL TIME',
    slug: 'orwdlr32-lab-coll-time',
    isContext: false,
    referenceCount: 1,
  },
  { name: 'ORWDLR32 LOAD', slug: 'orwdlr32-load', isContext: false, referenceCount: 1 },
  { name: 'ORWDLR32 MAXDAYS', slug: 'orwdlr32-maxdays', isContext: false, referenceCount: 1 },
  { name: 'ORWDLR32 ONE SAMPLE', slug: 'orwdlr32-one-sample', isContext: false, referenceCount: 1 },
  {
    name: 'ORWDLR32 ONE SPECIMEN',
    slug: 'orwdlr32-one-specimen',
    isContext: false,
    referenceCount: 1,
  },
  { name: 'ORWDLR32 STOP', slug: 'orwdlr32-stop', isContext: false, referenceCount: 1 },
  {
    name: 'ORWDLR33 FUTURE LAB COLLECTS',
    slug: 'orwdlr33-future-lab-collects',
    isContext: false,
    referenceCount: 1,
  },
  { name: 'ORWDLR33 LASTTIME', slug: 'orwdlr33-lasttime', isContext: false, referenceCount: 1 },
  { name: 'ORWDLR33 LC TO WC', slug: 'orwdlr33-lc-to-wc', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR ALLTESTS', slug: 'orwlrr-alltests', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR ATESTS', slug: 'orwlrr-atests', isContext: false, referenceCount: 2 },
  { name: 'ORWLRR ATG', slug: 'orwlrr-atg', isContext: false, referenceCount: 2 },
  { name: 'ORWLRR ATOMICS', slug: 'orwlrr-atomics', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR CHART', slug: 'orwlrr-chart', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR CHEMTEST', slug: 'orwlrr-chemtest', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR GRID', slug: 'orwlrr-grid', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR INFO', slug: 'orwlrr-info', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR INTERIM', slug: 'orwlrr-interim', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR INTERIMG', slug: 'orwlrr-interimg', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR INTERIMS', slug: 'orwlrr-interims', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR NEWOLD', slug: 'orwlrr-newold', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR PARAM', slug: 'orwlrr-param', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR SPEC', slug: 'orwlrr-spec', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR TG', slug: 'orwlrr-tg', isContext: false, referenceCount: 2 },
  { name: 'ORWLRR USERS', slug: 'orwlrr-users', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR UTGA', slug: 'orwlrr-utga', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR UTGD', slug: 'orwlrr-utgd', isContext: false, referenceCount: 1 },
  { name: 'ORWLRR UTGR', slug: 'orwlrr-utgr', isContext: false, referenceCount: 1 },
];

/** Stub response returned by unimplemented endpoints. */
export interface StubResponse {
  ok: false;
  error: 'Not implemented';
  rpcName: string;
  domain: string;
  slug: string;
  hint: string;
}

/**
 * Register all labs RPC stub routes.
 *
 * Routes: GET /vista/labs/rpc/:slug
 *         GET /vista/labs/rpcs  (catalog listing)
 */
export default async function labsRoutes(server: FastifyInstance): Promise<void> {
  // ── Catalog listing ───────────────────────────────────────────
  server.get('/vista/labs/rpcs', async () => {
    return {
      ok: true,
      domain: 'labs',
      count: 36,
      rpcs: LABS_RPCS,
    };
  });

  // ── Phase 568: Wired priority lab routes ──────────────────────

  /** ORQQL DETAIL — Lab order detail (read) */
  server.get('/vista/labs/:oid/detail', async (request: FastifyRequest, reply: FastifyReply) => {
    await requireSession(request, reply);
    const oid = (request.params as any)?.oid;
    if (!oid) return reply.status(400).send({ ok: false, error: 'oid path parameter required' });
    try {
      const lines = await safeCallRpc('ORQQL DETAIL', [String(oid)]);
      return reply.send({ ok: true, source: 'vista', data: lines, rpcUsed: ['ORQQL DETAIL'], pendingTargets: [] });
    } catch (err: any) {
      log.warn('ORQQL DETAIL failed', { err: err?.message || String(err) });
      return reply.code(502).send({ ok: false, source: 'vista', error: err?.message || 'RPC call failed', rpcUsed: [], pendingTargets: ['ORQQL DETAIL'], _integration: 'pending' });
    }
  });

  /** ORWLR RECENTSIT — Recent lab results by site (read) */
  server.get('/vista/labs/recent', async (request: FastifyRequest, reply: FastifyReply) => {
    await requireSession(request, reply);
    const dfn = (request.query as any)?.dfn;
    if (!dfn) return reply.status(400).send({ ok: false, error: 'dfn query parameter required' });
    try {
      const lines = await safeCallRpc('ORWLR RECENTSIT', [String(dfn)]);
      return reply.send({ ok: true, source: 'vista', data: lines, rpcUsed: ['ORWLR RECENTSIT'], pendingTargets: [] });
    } catch (err: any) {
      log.warn('ORWLR RECENTSIT failed', { err: err?.message || String(err) });
      return reply.code(502).send({ ok: false, source: 'vista', error: err?.message || 'RPC call failed', rpcUsed: [], pendingTargets: ['ORWLR RECENTSIT'], _integration: 'pending' });
    }
  });

  /** ORWLR CUMULATIVE — Cumulative lab report (read) */
  server.get('/vista/labs/cumulative', async (request: FastifyRequest, reply: FastifyReply) => {
    await requireSession(request, reply);
    const dfn = (request.query as any)?.dfn;
    if (!dfn) return reply.status(400).send({ ok: false, error: 'dfn query parameter required' });
    try {
      const lines = await safeCallRpc('ORWLR CUMULATIVE', [String(dfn)]);
      return reply.send({ ok: true, source: 'vista', data: lines, rpcUsed: ['ORWLR CUMULATIVE'], pendingTargets: [] });
    } catch (err: any) {
      log.warn('ORWLR CUMULATIVE failed', { err: err?.message || String(err) });
      return reply.code(502).send({ ok: false, source: 'vista', error: err?.message || 'RPC call failed', rpcUsed: [], pendingTargets: ['ORWLR CUMULATIVE'], _integration: 'pending' });
    }
  });

  /** LR ORDER — Place lab order (write — integration-pending, requires VEHU validation) */
  const LabOrderSchema = z.object({
    dfn: z.string().min(1, 'dfn required'),
    testIen: z.string().min(1, 'testIen required'),
    specimen: z.string().optional(),
    urgency: z.string().optional(),
    comment: z.string().optional(),
  });

  server.post('/vista/labs/order', async (request: FastifyRequest, reply: FastifyReply) => {
    await requireSession(request, reply);
    const body = (request.body as any) || {};
    const parsed = LabOrderSchema.safeParse(body);
    if (!parsed.success) {
      return reply.status(400).send({ ok: false, error: 'Validation failed', details: parsed.error.issues });
    }
    // TODO: Phase 568 — wire to LR ORDER after VEHU validation
    return reply.send({
      ok: false, source: 'vista', error: 'integration-pending',
      rpcUsed: [], pendingTargets: ['LR ORDER'],
      _integration: 'pending',
      _hint: 'LR ORDER writes clinical data — requires VEHU validation before enabling',
    });
  });

  // ── Individual RPC routes (Phase 580: wired to VistA) ───────────

  /** Generic lab RPC caller — DFN-based or paramBuilder for dialog helpers. */
  async function callLabRpc(
    rpcName: string,
    request: FastifyRequest,
    reply: FastifyReply,
    paramBuilder?: (q: any) => string[],
  ) {
    await requireSession(request, reply);
    const q = request.query as any;
    const params = paramBuilder ? paramBuilder(q) : q?.dfn ? [String(q.dfn)] : [];
    try {
      const lines = await safeCallRpc(rpcName, params);
      return reply.send({ ok: true, source: 'vista', rpcUsed: [rpcName], data: lines, pendingTargets: [] });
    } catch (err: any) {
      log.warn(`${rpcName} failed`, { err: err?.message });
      return reply.code(502).send({ ok: false, source: 'vista', error: err?.message || 'RPC call failed', rpcUsed: [], pendingTargets: [rpcName] });
    }
  }

  server.get('/vista/labs/rpc/orwdlr32-abbspec', (req, rep) => callLabRpc('ORWDLR32 ABBSPEC', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-allsamp', (req, rep) => callLabRpc('ORWDLR32 ALLSAMP', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-allspec', (req, rep) => callLabRpc('ORWDLR32 ALLSPEC', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-def', (req, rep) => callLabRpc('ORWDLR32 DEF', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-get-lab-times', (req, rep) => callLabRpc('ORWDLR32 GET LAB TIMES', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-ic-default', (req, rep) => callLabRpc('ORWDLR32 IC DEFAULT', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-ic-valid', (req, rep) => callLabRpc('ORWDLR32 IC VALID', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-immed-collect', (req, rep) => callLabRpc('ORWDLR32 IMMED COLLECT', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-lab-coll-time', (req, rep) => callLabRpc('ORWDLR32 LAB COLL TIME', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-load', (req, rep) => callLabRpc('ORWDLR32 LOAD', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-maxdays', (req, rep) => callLabRpc('ORWDLR32 MAXDAYS', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-one-sample', (req, rep) => callLabRpc('ORWDLR32 ONE SAMPLE', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-one-specimen', (req, rep) => callLabRpc('ORWDLR32 ONE SPECIMEN', req, rep));
  server.get('/vista/labs/rpc/orwdlr32-stop', (req, rep) => callLabRpc('ORWDLR32 STOP', req, rep));
  server.get('/vista/labs/rpc/orwdlr33-future-lab-collects', (req, rep) => callLabRpc('ORWDLR33 FUTURE LAB COLLECTS', req, rep));
  server.get('/vista/labs/rpc/orwdlr33-lasttime', (req, rep) => callLabRpc('ORWDLR33 LASTTIME', req, rep));
  server.get('/vista/labs/rpc/orwdlr33-lc-to-wc', (req, rep) => callLabRpc('ORWDLR33 LC TO WC', req, rep));
  server.get('/vista/labs/rpc/orwlrr-alltests', (req, rep) => callLabRpc('ORWLRR ALLTESTS', req, rep));
  server.get('/vista/labs/rpc/orwlrr-atests', (req, rep) => callLabRpc('ORWLRR ATESTS', req, rep));
  server.get('/vista/labs/rpc/orwlrr-atg', (req, rep) => callLabRpc('ORWLRR ATG', req, rep));
  server.get('/vista/labs/rpc/orwlrr-atomics', (req, rep) => callLabRpc('ORWLRR ATOMICS', req, rep));
  server.get('/vista/labs/rpc/orwlrr-chart', (req, rep) => callLabRpc('ORWLRR CHART', req, rep, (q) => [q?.dfn || '', q?.testName || '']));
  server.get('/vista/labs/rpc/orwlrr-chemtest', (req, rep) => callLabRpc('ORWLRR CHEMTEST', req, rep));
  server.get('/vista/labs/rpc/orwlrr-grid', (req, rep) => callLabRpc('ORWLRR GRID', req, rep));
  server.get('/vista/labs/rpc/orwlrr-info', (req, rep) => callLabRpc('ORWLRR INFO', req, rep));
  server.get('/vista/labs/rpc/orwlrr-interim', (req, rep) => callLabRpc('ORWLRR INTERIM', req, rep, (q) => [q?.dfn || '', q?.p1 || '', q?.p2 || '']));
  server.get('/vista/labs/rpc/orwlrr-interimg', (req, rep) => callLabRpc('ORWLRR INTERIMG', req, rep, (q) => [q?.dfn || '', '', '1', '']));
  server.get('/vista/labs/rpc/orwlrr-interims', (req, rep) => callLabRpc('ORWLRR INTERIMS', req, rep));
  server.get('/vista/labs/rpc/orwlrr-newold', (req, rep) => callLabRpc('ORWLRR NEWOLD', req, rep));
  server.get('/vista/labs/rpc/orwlrr-param', (req, rep) => callLabRpc('ORWLRR PARAM', req, rep));
  server.get('/vista/labs/rpc/orwlrr-spec', (req, rep) => callLabRpc('ORWLRR SPEC', req, rep));
  server.get('/vista/labs/rpc/orwlrr-tg', (req, rep) => callLabRpc('ORWLRR TG', req, rep));
  server.get('/vista/labs/rpc/orwlrr-users', (req, rep) => callLabRpc('ORWLRR USERS', req, rep));
  server.get('/vista/labs/rpc/orwlrr-utga', (req, rep) => callLabRpc('ORWLRR UTGA', req, rep));
  server.get('/vista/labs/rpc/orwlrr-utgd', (req, rep) => callLabRpc('ORWLRR UTGD', req, rep));
  server.get('/vista/labs/rpc/orwlrr-utgr', (req, rep) => callLabRpc('ORWLRR UTGR', req, rep));
}
