/**
 * Claims Lifecycle v1 — Enhanced Domain Types (Phase 91)
 *
 * Extends the existing Phase 38 Claim domain model with:
 * - Enhanced state machine (more granular than the base 10-state FSM)
 * - ClaimScrubResult — deterministic scrubber output
 * - ClaimAttachment — evidence artifacts (SOAs, receipts, labs)
 * - ClaimEvent — append-only lifecycle event log
 * - DenialRecord — structured denial tracking for workbench
 *
 * In-memory stores. Resets on API restart (matching Phase 23 pattern).
 */

/* ── Lifecycle States ──────────────────────────────────────── */

/**
 * Enhanced claim lifecycle states.
 * Superset of the base ClaimStatus from domain/claim.ts.
 * Adds scrub, submission-mode, acknowledgement, partial-pay, and appeal states.
 */
export type ClaimLifecycleStatus =
  | 'draft'
  | 'ready_for_scrub'
  | 'scrub_passed'
  | 'scrub_failed'
  | 'ready_for_submission'
  | 'submitted_electronic'
  | 'submitted_portal'
  | 'submitted_manual'
  | 'exported'
  | 'payer_acknowledged'
  | 'paid_full'
  | 'paid_partial'
  | 'denied'
  | 'returned_to_provider'
  | 'appeal_in_progress'
  | 'closed'
  | 'cancelled';

/** Valid transitions: from → allowed destinations */
export const LIFECYCLE_TRANSITIONS: Record<ClaimLifecycleStatus, ClaimLifecycleStatus[]> = {
  draft:                 ['ready_for_scrub', 'scrub_passed', 'scrub_failed', 'cancelled'],
  ready_for_scrub:       ['scrub_passed', 'scrub_failed', 'cancelled'],
  scrub_passed:          ['ready_for_submission', 'ready_for_scrub', 'cancelled'],
  scrub_failed:          ['draft', 'ready_for_scrub', 'cancelled'],
  ready_for_submission:  ['submitted_electronic', 'submitted_portal', 'submitted_manual', 'exported', 'cancelled'],
  submitted_electronic:  ['payer_acknowledged', 'denied', 'returned_to_provider', 'cancelled'],
  submitted_portal:      ['payer_acknowledged', 'denied', 'returned_to_provider', 'cancelled'],
  submitted_manual:      ['payer_acknowledged', 'denied', 'returned_to_provider', 'cancelled'],
  exported:              ['submitted_electronic', 'submitted_portal', 'submitted_manual', 'cancelled'],
  payer_acknowledged:    ['paid_full', 'paid_partial', 'denied', 'returned_to_provider'],
  paid_full:             ['closed'],
  paid_partial:          ['appeal_in_progress', 'closed'],
  denied:                ['appeal_in_progress', 'closed'],
  returned_to_provider:  ['draft', 'cancelled'],
  appeal_in_progress:    ['paid_full', 'paid_partial', 'denied', 'closed'],
  closed:                [],
  cancelled:             [],
};

export function isValidLifecycleTransition(
  from: ClaimLifecycleStatus,
  to: ClaimLifecycleStatus,
): boolean {
  return LIFECYCLE_TRANSITIONS[from]?.includes(to) ?? false;
}

/* ── Scrubber Types ────────────────────────────────────────── */

export type ScrubSeverity = 'error' | 'warning' | 'info';
export type ScrubOutcome = 'pass' | 'warn' | 'fail';

export interface ScrubFinding {
  ruleId: string;          // e.g. "core.patient_id", "ph.esoa_required"
  severity: ScrubSeverity;
  field?: string;          // e.g. "subscriberId", "lines[0].procedure.code"
  message: string;         // human-readable description
  payerRulePack?: string;  // e.g. "philhealth", "us_medicare", "core"
}

export interface ClaimScrubResult {
  id: string;
  claimCaseId: string;
  outcome: ScrubOutcome;
  findings: ScrubFinding[];
  rulesEvaluated: number;
  scrubDurationMs: number;
  scrubbedAt: string;
  scrubbedBy: string;      // "system" or DUZ
}

/* ── Attachment Types ──────────────────────────────────────── */

export type AttachmentCategory =
  | 'soa'           // Statement of Account
  | 'esoa'          // Electronic SOA (PhilHealth)
  | 'lab_result'
  | 'imaging_report'
  | 'clinical_abstract'
  | 'receipt'
  | 'rx_prescription'
  | 'referral_letter'
  | 'discharge_summary'
  | 'consent_form'
  | 'other';

export interface ClaimAttachment {
  id: string;
  claimCaseId: string;
  category: AttachmentCategory;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  /** Reference to external storage (not stored in-memory) */
  storageRef?: string;
  uploadedBy: string;
  uploadedAt: string;
  /** If true, this attachment was auto-generated (e.g., eSOA from PH gateway) */
  autoGenerated: boolean;
}

/* ── Event Types ───────────────────────────────────────────── */

export interface ClaimEvent {
  id: string;
  claimCaseId: string;
  eventType: string;          // e.g. "lifecycle.transition", "scrub.completed", "attachment.added"
  fromStatus?: ClaimLifecycleStatus;
  toStatus?: ClaimLifecycleStatus;
  actor: string;              // DUZ or "system"
  /** Detail payload — PHI is redacted before storage */
  detail: Record<string, unknown>;
  timestamp: string;
}

/* ── Denial Record ─────────────────────────────────────────── */

export type DenialSource =
  | 'payer_remit'       // from 835/remittance
  | 'payer_status'      // from 277 status
  | 'scrub_reject'      // from scrubber (pre-submission)
  | 'portal_response'   // from payer portal
  | 'manual';           // manually entered

export interface DenialRecord {
  id: string;
  claimCaseId: string;
  source: DenialSource;
  reasonCode: string;         // CARC, PhilHealth denial code, or internal
  reasonDescription: string;
  reasonCategory?: string;    // CO/PR/OA/PI/CR
  denialAmount?: number;      // in cents
  deniedAt: string;
  /** Remediation tracking */
  recommendedAction?: string;
  fieldToFix?: string;
  assignedTo?: string;        // DUZ
  resolvedAt?: string;
  resolvedBy?: string;
  resolutionNote?: string;
  /** Appeal linkage */
  appealId?: string;
}

/* ── ClaimCase — Enhanced Claim Wrapper ────────────────────── */

/**
 * ClaimCase wraps the base Claim (from Phase 38) with enhanced lifecycle,
 * scrub results, attachments, events, and denial tracking.
 *
 * The base Claim fields (patient, provider, payer, lines, diagnoses)
 * are flattened in rather than composed — this keeps the API surface
 * simple and avoids deep nesting.
 */
export interface ClaimCase {
  id: string;
  tenantId: string;

  /** Enhanced lifecycle status */
  lifecycleStatus: ClaimLifecycleStatus;

  /** Link to base claim if one exists in domain/claim-store */
  baseClaimId?: string;

  /** Link to PhilHealth draft if originated from PH posture */
  philhealthDraftId?: string;

  /** Link to LOA case if claim was created from approved LOA */
  loaCaseId?: string;

  /* ── Patient ──────────────────────────────────────────── */
  patientDfn: string;
  patientName?: string;
  patientDob?: string;
  patientGender?: string;
  subscriberId?: string;
  memberPin?: string;        // PhilHealth member PIN

  /* ── Provider ─────────────────────────────────────────── */
  billingProviderNpi?: string;
  renderingProviderNpi?: string;
  facilityCode?: string;
  facilityName?: string;

  /* ── Payer ────────────────────────────────────────────── */
  payerId: string;
  payerName?: string;
  payerType?: 'government' | 'private_hmo' | 'commercial' | 'other';

  /* ── Clinical ─────────────────────────────────────────── */
  claimType: 'professional' | 'institutional' | 'dental' | 'pharmacy';
  dateOfService: string;
  dateOfDischarge?: string;
  diagnoses: Array<{
    code: string;
    qualifier: 'icd10' | 'icd9';
    description?: string;
    isPrimary?: boolean;
  }>;
  procedures: Array<{
    code: string;
    codeType: 'cpt' | 'hcpcs' | 'rvs' | 'icd10pcs';
    description?: string;
    modifiers?: string[];
    units: number;
    chargeAmount: number;   // in cents
  }>;
  totalCharge: number;       // in cents

  /* ── Submission ───────────────────────────────────────── */
  submissionMethod?: 'electronic' | 'portal' | 'manual' | 'export_only';
  submittedAt?: string;
  payerClaimNumber?: string;
  payerAckTimestamp?: string;

  /* ── Financial ────────────────────────────────────────── */
  paidAmount?: number;       // in cents
  adjustmentAmount?: number; // in cents
  patientResponsibility?: number; // in cents
  remitDate?: string;

  /* ── VistA Grounding ──────────────────────────────────── */
  vistaEncounterIen?: string;
  vistaChargeIen?: string;
  vistaArIen?: string;

  /* ── Scrub Results ────────────────────────────────────── */
  lastScrubResult?: ClaimScrubResult;
  scrubHistory: ClaimScrubResult[];

  /* ── Attachments ──────────────────────────────────────── */
  attachments: ClaimAttachment[];

  /* ── Events ───────────────────────────────────────────── */
  events: ClaimEvent[];

  /* ── Denials ──────────────────────────────────────────── */
  denials: DenialRecord[];

  /* ── Flags ────────────────────────────────────────────── */
  isDemo: boolean;
  isMock: boolean;
  priority: 'critical' | 'high' | 'medium' | 'low';

  /* ── Metadata ─────────────────────────────────────────── */
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}
