// Auto-generated by vista-module-gen for Capacity Management Tools (KMPD)
// Do NOT edit manually
'use client';

import { useState, useCallback } from 'react';

const API_BASE = typeof window !== 'undefined'
  ? `${window.location.protocol}//${window.location.hostname}:3001`
  : 'http://127.0.0.1:3001';

const RPCS: { name: string; slug: string }[] = [{"name":"KMPD FILE SEARCH","slug":"kmpd-file-search"},{"name":"KMPD VERSION","slug":"kmpd-version"},{"name":"KMPD ENVIRONMENT","slug":"kmpd-environment"},{"name":"KMPD FILE INQUIRY","slug":"kmpd-file-inquiry"},{"name":"KMPD GLOBAL LIST","slug":"kmpd-global-list"},{"name":"KMPD ERROR LOG DATA","slug":"kmpd-error-log-data"},{"name":"KMPD ROUTINE FIND","slug":"kmpd-routine-find"},{"name":"KMPD ROUTINE INQ","slug":"kmpd-routine-inq"},{"name":"KMPD ROUTINE LINE SRCH","slug":"kmpd-routine-line-srch"},{"name":"KMPD ROUTINE STATS","slug":"kmpd-routine-stats"},{"name":"KMPD ROUTINE SAVE","slug":"kmpd-routine-save"},{"name":"KMPD FM DATE","slug":"kmpd-fm-date"},{"name":"KMPD ERROR LOG DATE","slug":"kmpd-error-log-date"},{"name":"KMPD ASSOC ROUTINE ADD/DEL","slug":"kmpd-assoc-routine-adddel"},{"name":"KMPD APPL STATUS","slug":"kmpd-appl-status"},{"name":"KMPD DATA ELEMENTS","slug":"kmpd-data-elements"},{"name":"KMPD NODES","slug":"kmpd-nodes"},{"name":"KMPD TMG MON DATA","slug":"kmpd-tmg-mon-data"},{"name":"KMPD USER PARAMETERS","slug":"kmpd-user-parameters"},{"name":"KMPD TMG DATES","slug":"kmpd-tmg-dates"},{"name":"KMPD TMG REPORTS","slug":"kmpd-tmg-reports"},{"name":"KMPD REPORT DEFINITION","slug":"kmpd-report-definition"},{"name":"KMPD TMG STATUS","slug":"kmpd-tmg-status"},{"name":"KMPD RUM START/STOP","slug":"kmpd-rum-startstop"},{"name":"KMPD TMG START/STOP","slug":"kmpd-tmg-startstop"},{"name":"KMPD RUM ENV","slug":"kmpd-rum-env"},{"name":"KMPD SEARCH BY LIST","slug":"kmpd-search-by-list"},{"name":"KMPD ERROR LOG LIST","slug":"kmpd-error-log-list"}];

interface RpcResult { ok: boolean; rpcUsed?: string[]; data?: string[]; error?: string; }

export default function CapacityManagementToolsPanel({ dfn: propDfn = '46' }: { dfn?: string }) {
  const [selectedRpc, setSelectedRpc] = useState<string | null>(null);
  const [dfn, setDfn] = useState(propDfn);
  const [result, setResult] = useState<RpcResult | null>(null);
  const [loading, setLoading] = useState(false);

  const callRpc = useCallback(async (slug: string) => {
    setLoading(true);
    setSelectedRpc(slug);
    try {
      const res = await fetch(`${API_BASE}/vista/kmpd/rpc/${slug}?dfn=${dfn}`, { credentials: 'include' });
      const json = await res.json();
      setResult(json);
    } catch (e: unknown) {
      setResult({ ok: false, error: (e as Error).message });
    }
    setLoading(false);
  }, [dfn]);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <label className="text-sm font-medium">Patient DFN:</label>
        <input
          className="px-2 py-1 border rounded text-sm w-24"
          value={dfn}
          onChange={e => setDfn(e.target.value)}
        />
        <span className="text-xs text-muted-foreground">28 RPCs available</span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="md:col-span-1 border rounded-lg p-3 max-h-96 overflow-y-auto">
          <h3 className="font-semibold text-sm mb-2">RPCs</h3>
          {RPCS.length === 0 ? (
            <p className="text-xs text-muted-foreground">No RPCs registered for KMPD.</p>
          ) : (
            <div className="space-y-1">
              {RPCS.map(r => (
                <button
                  key={r.slug}
                  onClick={() => callRpc(r.slug)}
                  className={`w-full text-left text-xs px-2 py-1.5 rounded transition-colors ${
                    selectedRpc === r.slug ? 'bg-primary text-primary-foreground' : 'hover:bg-muted'
                  }`}
                >
                  {r.name}
                </button>
              ))}
            </div>
          )}
        </div>

        <div className="md:col-span-2 border rounded-lg p-3">
          <h3 className="font-semibold text-sm mb-2">
            {selectedRpc ? `Result: ${selectedRpc}` : 'Select an RPC to call'}
          </h3>
          {loading && <div className="animate-pulse text-sm">Calling VistA...</div>}
          {result && !loading && (
            <div className="space-y-2">
              <div className="flex gap-2 text-xs">
                <span className={`px-1.5 py-0.5 rounded ${result.ok ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                  {result.ok ? 'OK' : 'ERROR'}
                </span>
                {result.rpcUsed?.map(r => (
                  <span key={r} className="px-1.5 py-0.5 rounded bg-blue-100 text-blue-800">{r}</span>
                ))}
              </div>
              {result.error && <p className="text-red-500 text-sm">{result.error}</p>}
              {result.data && result.data.length > 0 ? (
                <pre className="text-xs bg-muted p-2 rounded max-h-60 overflow-y-auto whitespace-pre-wrap">
                  {result.data.join('\n')}
                </pre>
              ) : (
                <p className="text-muted-foreground text-sm">No data returned.</p>
              )}
            </div>
          )}
          {!result && !loading && (
            <p className="text-muted-foreground text-sm">Click an RPC on the left to call it against VistA.</p>
          )}
        </div>
      </div>

      <div className="text-xs text-muted-foreground">
        API: <code>${API_BASE}/vista/kmpd/rpc/&lt;slug&gt;?dfn=&lt;n&gt;</code>
      </div>
    </div>
  );
}