/**
 * MHA Note Generator — Phase 536
 *
 * Generates structured TIU note text from a completed MHA administration.
 * The note follows a standard clinical format suitable for filing via
 * TIU CREATE RECORD + TIU SET DOCUMENT TEXT.
 *
 * No PHI is embedded in this module — patient identity comes from VistA context.
 */

import type { MhaScoreResult, MhaAnswer } from "./scoring.js";
import type { FhirQuestionnaire } from "./instruments.js";

/* ------------------------------------------------------------------ */
/* Types                                                                */
/* ------------------------------------------------------------------ */

export interface MhaNoteInput {
  instrumentId: string;
  instrumentTitle: string;
  description?: string;
  answers: MhaAnswer[];
  score: MhaScoreResult;
  administeredAt: string;
  items: Array<{ linkId: string; text: string; answerOptions?: Array<{ code: string; display: string }> }>;
}

/* ------------------------------------------------------------------ */
/* Note generator                                                       */
/* ------------------------------------------------------------------ */

/**
 * Generate structured MHA note text for filing as a TIU document.
 * Returns an array of lines (one per word-processing row).
 */
export function generateMhaNote(input: MhaNoteInput): string[] {
  const lines: string[] = [];

  // Header
  lines.push("=== MENTAL HEALTH ASSESSMENT ===");
  lines.push("");
  lines.push(`Instrument: ${input.instrumentTitle}`);
  lines.push(`Date Administered: ${input.administeredAt}`);
  lines.push("");

  // Scoring summary
  lines.push("--- SCORING SUMMARY ---");
  lines.push(`Total Score: ${input.score.totalScore} / ${input.score.maxScore}`);
  lines.push(`Severity: ${input.score.severity}`);
  lines.push(`Interpretation: ${input.score.interpretation}`);
  if (input.score.redFlag) {
    lines.push("");
    lines.push("*** RED FLAG ***");
    lines.push(`Reason: ${input.score.redFlagReason || "Safety concern identified"}`);
  }
  lines.push("");

  // Individual item responses
  lines.push("--- ITEM RESPONSES ---");
  for (let i = 0; i < input.items.length; i++) {
    const item = input.items[i];
    const answer = input.answers.find((a) => a.linkId === item.linkId);
    const answerValue = answer?.value ?? "N/A";

    // Look up display text for the answer value
    let displayText = answerValue;
    if (item.answerOptions) {
      const opt = item.answerOptions.find((o) => o.code === answerValue);
      if (opt) displayText = `${opt.display} (${answerValue})`;
    }

    const itemScore = input.score.itemScores.find((s) => s.linkId === item.linkId);
    const scoreStr = itemScore !== undefined ? ` [Score: ${itemScore.score}]` : "";

    lines.push(`${i + 1}. ${item.text}`);
    lines.push(`   Response: ${displayText}${scoreStr}`);
  }
  lines.push("");

  // Footer
  lines.push("--- END MENTAL HEALTH ASSESSMENT ---");
  lines.push(`Instrument ID: ${input.instrumentId}`);
  lines.push("Generated by VistA-Evolved MHA Engine (Phase 535/536)");

  return lines;
}

/**
 * Build MhaNoteInput from an administration record + instrument definition.
 */
export function buildNoteInput(
  admin: {
    instrumentId: string;
    answers: MhaAnswer[];
    score: MhaScoreResult;
    administeredAt: string;
  },
  instrument: FhirQuestionnaire,
): MhaNoteInput {
  return {
    instrumentId: admin.instrumentId,
    instrumentTitle: instrument.title,
    description: instrument.description,
    answers: admin.answers,
    score: admin.score,
    administeredAt: admin.administeredAt,
    items: instrument.item.map((item) => ({
      linkId: item.linkId,
      text: item.text,
      answerOptions: item.answerOption?.map((opt) => ({
        code: opt.valueCoding.code,
        display: opt.valueCoding.display,
      })),
    })),
  };
}
