/**
 * Complaint Packs: Back Pain, Cough, Fever, Fatigue, Dizziness
 * Lighter packs (5-10 items each) for common presentations
 */
import type { IntakePack } from '../types.js';

export const backPainPack: IntakePack = {
  packId: 'complaint-back-pain-v1',
  version: '1.0.0',
  title: 'Back Pain Intake',
  description: 'Focused back pain with red flag screening',
  languages: ['en'],
  applicableContexts: {
    departments: ['*'],
    specialties: ['*'],
    visitTypes: ['*'],
    chiefComplaints: ['back pain', 'low back pain', 'lbp', 'lumbar pain'],
  },
  requiredCoverage: ['hpi', 'ros'],
  items: [
    {
      linkId: 'bp-location',
      type: 'choice',
      text: 'Where is the pain?',
      section: 'hpi',
      required: true,
      order: 30,
      answerOption: [
        { value: 'lower', display: 'Lower back' },
        { value: 'mid', display: 'Mid back' },
        { value: 'upper', display: 'Upper back' },
        { value: 'radiating_leg', display: 'Back radiating to leg' },
      ],
    },
    {
      linkId: 'bp-onset',
      type: 'choice',
      text: 'How did it start?',
      section: 'hpi',
      required: true,
      order: 31,
      answerOption: [
        { value: 'injury', display: 'After injury/fall' },
        { value: 'lifting', display: 'After lifting' },
        { value: 'gradual', display: 'Gradually' },
        { value: 'sudden', display: 'Suddenly without cause' },
      ],
    },
    {
      linkId: 'bp-worse',
      type: 'open-choice',
      text: 'What makes it worse?',
      section: 'hpi',
      required: true,
      order: 32,
      answerOption: [
        { value: 'sitting', display: 'Sitting' },
        { value: 'standing', display: 'Standing' },
        { value: 'bending', display: 'Bending' },
        { value: 'walking', display: 'Walking' },
      ],
    },
    {
      linkId: 'bp-numbness',
      type: 'boolean',
      text: 'Any numbness or tingling in your legs?',
      section: 'ros',
      required: true,
      order: 40,
      redFlag: {
        condition: 'true',
        message: 'Radiculopathy - nerve compression',
        severity: 'medium',
      },
    },
    {
      linkId: 'bp-weakness-legs',
      type: 'boolean',
      text: 'Any weakness in your legs?',
      section: 'ros',
      required: true,
      order: 41,
      redFlag: {
        condition: 'true',
        message: 'Motor deficit - cauda equina concern',
        severity: 'high',
      },
    },
    {
      linkId: 'bp-bladder',
      type: 'boolean',
      text: 'Any difficulty controlling your bladder or bowels?',
      section: 'ros',
      required: true,
      order: 42,
      redFlag: {
        condition: 'true',
        message: 'Bowel/bladder dysfunction - cauda equina emergency',
        severity: 'critical',
      },
    },
    {
      linkId: 'bp-saddle',
      type: 'boolean',
      text: 'Any numbness in the groin/saddle area?',
      section: 'ros',
      required: true,
      order: 43,
      redFlag: {
        condition: 'true',
        message: 'Saddle anesthesia - cauda equina emergency',
        severity: 'critical',
      },
    },
    {
      linkId: 'bp-fever',
      type: 'boolean',
      text: 'Any fever?',
      section: 'ros',
      required: true,
      order: 44,
      redFlag: {
        condition: 'true',
        message: 'Fever + back pain - epidural abscess/osteomyelitis concern',
        severity: 'high',
      },
    },
  ],
  complaintClusters: ['back_pain', 'musculoskeletal'],
  specialtyTags: ['orthopedics', 'neurology'],
  departmentTags: [],
  priority: 10,
  outputTemplates: {
    hpiTemplate: 'Back pain: {{bp-location}}. Onset: {{bp-onset}}. Aggravating: {{bp-worse}}.',
    rosTemplate:
      'NEURO: Numbness {{bp-numbness}}, weakness {{bp-weakness-legs}}, bladder/bowel {{bp-bladder}}, saddle {{bp-saddle}}. GENERAL: Fever {{bp-fever}}.',
    noteTemplate: '',
  },
  scoringThresholds: [],
};

export const coughPack: IntakePack = {
  packId: 'complaint-cough-v1',
  version: '1.0.0',
  title: 'Cough Intake',
  description: 'Focused cough history with pulmonary red flags',
  languages: ['en'],
  applicableContexts: {
    departments: ['*'],
    specialties: ['*'],
    visitTypes: ['*'],
    chiefComplaints: ['cough', 'coughing', 'chronic cough'],
  },
  requiredCoverage: ['hpi', 'ros'],
  items: [
    {
      linkId: 'cgh-duration',
      type: 'choice',
      text: 'How long have you had the cough?',
      section: 'hpi',
      required: true,
      order: 30,
      answerOption: [
        { value: 'acute', display: 'Less than 3 weeks' },
        { value: 'subacute', display: '3-8 weeks' },
        { value: 'chronic', display: 'More than 8 weeks' },
      ],
    },
    {
      linkId: 'cgh-productive',
      type: 'choice',
      text: 'Is the cough producing anything?',
      section: 'hpi',
      required: true,
      order: 31,
      answerOption: [
        { value: 'dry', display: 'Dry cough' },
        { value: 'clear', display: 'Clear/white mucus' },
        { value: 'yellow_green', display: 'Yellow or green mucus' },
        { value: 'bloody', display: 'Blood-tinged' },
      ],
    },
    {
      linkId: 'cgh-hemoptysis',
      type: 'boolean',
      text: 'Have you coughed up blood?',
      section: 'hpi',
      required: true,
      order: 32,
      redFlag: {
        condition: 'true',
        message: 'Hemoptysis - TB/malignancy/PE concern',
        severity: 'high',
      },
    },
    {
      linkId: 'cgh-sob',
      type: 'boolean',
      text: 'Shortness of breath?',
      section: 'ros',
      required: true,
      order: 40,
    },
    {
      linkId: 'cgh-wheeze',
      type: 'boolean',
      text: 'Wheezing?',
      section: 'ros',
      required: true,
      order: 41,
    },
    {
      linkId: 'cgh-fever',
      type: 'boolean',
      text: 'Fever?',
      section: 'ros',
      required: true,
      order: 42,
    },
    {
      linkId: 'cgh-weight-loss',
      type: 'boolean',
      text: 'Unintentional weight loss?',
      section: 'ros',
      required: true,
      order: 43,
      redFlag: {
        condition: 'true',
        message: 'Weight loss + cough - malignancy/TB concern',
        severity: 'high',
      },
    },
    {
      linkId: 'cgh-night-sweats',
      type: 'boolean',
      text: 'Night sweats?',
      section: 'ros',
      required: true,
      order: 44,
      redFlag: {
        condition: 'true',
        message: 'Night sweats + cough - TB/lymphoma concern',
        severity: 'high',
      },
    },
    {
      linkId: 'cgh-smoking',
      type: 'boolean',
      text: 'Do you smoke or have you smoked?',
      section: 'pmh',
      required: true,
      order: 50,
    },
  ],
  complaintClusters: ['cough', 'respiratory'],
  specialtyTags: ['pulmonology'],
  departmentTags: [],
  priority: 10,
  outputTemplates: {
    hpiTemplate: 'Cough: {{cgh-duration}}, {{cgh-productive}}. Hemoptysis: {{cgh-hemoptysis}}.',
    rosTemplate:
      'RESP: SOB {{cgh-sob}}, wheeze {{cgh-wheeze}}. GENERAL: Fever {{cgh-fever}}, weight loss {{cgh-weight-loss}}, night sweats {{cgh-night-sweats}}.',
    noteTemplate: '',
  },
  scoringThresholds: [],
};

export const feverPack: IntakePack = {
  packId: 'complaint-fever-v1',
  version: '1.0.0',
  title: 'Fever Intake',
  description: 'Focused fever history with source identification',
  languages: ['en'],
  applicableContexts: {
    departments: ['*'],
    specialties: ['*'],
    visitTypes: ['*'],
    chiefComplaints: ['fever', 'chills', 'temperature', 'febrile'],
  },
  requiredCoverage: ['hpi', 'ros'],
  items: [
    {
      linkId: 'fev-max-temp',
      type: 'string',
      text: 'What is the highest temperature you recorded?',
      section: 'hpi',
      required: false,
      order: 30,
    },
    {
      linkId: 'fev-duration',
      type: 'choice',
      text: 'How long have you had a fever?',
      section: 'hpi',
      required: true,
      order: 31,
      answerOption: [
        { value: 'today', display: 'Started today' },
        { value: 'days', display: '2-3 days' },
        { value: 'week', display: 'About a week' },
        { value: 'prolonged', display: 'More than a week' },
      ],
    },
    {
      linkId: 'fev-pattern',
      type: 'choice',
      text: 'Is the fever constant or does it come and go?',
      section: 'hpi',
      required: true,
      order: 32,
      answerOption: [
        { value: 'constant', display: 'Constant' },
        { value: 'intermittent', display: 'Comes and goes' },
        { value: 'night_only', display: 'Mainly at night' },
      ],
    },
    {
      linkId: 'fev-sore-throat',
      type: 'boolean',
      text: 'Sore throat?',
      section: 'ros',
      required: true,
      order: 40,
    },
    {
      linkId: 'fev-cough',
      type: 'boolean',
      text: 'Cough?',
      section: 'ros',
      required: true,
      order: 41,
    },
    {
      linkId: 'fev-urinary',
      type: 'boolean',
      text: 'Painful or frequent urination?',
      section: 'ros',
      required: true,
      order: 42,
    },
    {
      linkId: 'fev-rash',
      type: 'boolean',
      text: 'Any rash?',
      section: 'ros',
      required: true,
      order: 43,
    },
    {
      linkId: 'fev-neck-stiff',
      type: 'boolean',
      text: 'Stiff neck?',
      section: 'ros',
      required: true,
      order: 44,
      redFlag: { condition: 'true', message: 'Meningismus with fever', severity: 'critical' },
    },
    {
      linkId: 'fev-confusion',
      type: 'boolean',
      text: 'Any confusion or altered mental status?',
      section: 'ros',
      required: true,
      order: 45,
      redFlag: {
        condition: 'true',
        message: 'AMS with fever - sepsis/meningitis concern',
        severity: 'critical',
      },
    },
    {
      linkId: 'fev-travel',
      type: 'boolean',
      text: 'Recent travel outside the country?',
      section: 'hpi',
      required: true,
      order: 33,
    },
    {
      linkId: 'fev-immunocomp',
      type: 'boolean',
      text: 'Are you immunocompromised (HIV, chemo, transplant)?',
      section: 'pmh',
      required: true,
      order: 50,
      redFlag: {
        condition: 'true',
        message: 'Immunocompromised + fever - high risk',
        severity: 'high',
      },
    },
  ],
  complaintClusters: ['fever', 'infectious'],
  specialtyTags: ['infectious_disease'],
  departmentTags: ['ed'],
  priority: 10,
  outputTemplates: {
    hpiTemplate:
      'Fever: max {{fev-max-temp}}, duration {{fev-duration}}, pattern {{fev-pattern}}. Travel: {{fev-travel}}.',
    rosTemplate:
      'ENT: Sore throat {{fev-sore-throat}}. RESP: Cough {{fev-cough}}. GU: Urinary sx {{fev-urinary}}. DERM: Rash {{fev-rash}}. NEURO: Neck stiffness {{fev-neck-stiff}}, confusion {{fev-confusion}}.',
    noteTemplate: '',
  },
  scoringThresholds: [],
};

export const fatiguePack: IntakePack = {
  packId: 'complaint-fatigue-v1',
  version: '1.0.0',
  title: 'Fatigue Intake',
  description: 'Focused fatigue/tiredness history',
  languages: ['en'],
  applicableContexts: {
    departments: ['*'],
    specialties: ['*'],
    visitTypes: ['*'],
    chiefComplaints: ['fatigue', 'tired', 'tiredness', 'exhaustion', 'weakness', 'malaise'],
  },
  requiredCoverage: ['hpi', 'ros'],
  items: [
    {
      linkId: 'fat-duration',
      type: 'choice',
      text: 'How long have you felt fatigued?',
      section: 'hpi',
      required: true,
      order: 30,
      answerOption: [
        { value: 'days', display: 'Days' },
        { value: 'weeks', display: 'Weeks' },
        { value: 'months', display: 'Months' },
        { value: 'years', display: 'Over a year' },
      ],
    },
    {
      linkId: 'fat-onset',
      type: 'choice',
      text: 'How did the fatigue start?',
      section: 'hpi',
      required: true,
      order: 31,
      answerOption: [
        { value: 'sudden', display: 'Suddenly' },
        { value: 'gradual', display: 'Gradually' },
        { value: 'after_illness', display: 'After an illness' },
      ],
    },
    {
      linkId: 'fat-sleep',
      type: 'choice',
      text: 'How is your sleep?',
      section: 'hpi',
      required: true,
      order: 32,
      answerOption: [
        { value: 'good', display: 'Sleeping well' },
        { value: 'insomnia', display: 'Trouble falling/staying asleep' },
        { value: 'excessive', display: 'Sleeping too much' },
        { value: 'unrefreshing', display: 'Sleep is unrefreshing' },
      ],
    },
    {
      linkId: 'fat-mood',
      type: 'boolean',
      text: 'Have you been feeling sad or depressed?',
      section: 'ros',
      required: true,
      order: 40,
    },
    {
      linkId: 'fat-weight-change',
      type: 'boolean',
      text: 'Any unintentional weight change?',
      section: 'ros',
      required: true,
      order: 41,
    },
    {
      linkId: 'fat-fever',
      type: 'boolean',
      text: 'Any fevers?',
      section: 'ros',
      required: true,
      order: 42,
    },
    {
      linkId: 'fat-sob',
      type: 'boolean',
      text: 'Shortness of breath with activity?',
      section: 'ros',
      required: true,
      order: 43,
    },
    {
      linkId: 'fat-night-sweats',
      type: 'boolean',
      text: 'Night sweats?',
      section: 'ros',
      required: true,
      order: 44,
      redFlag: {
        condition: 'true',
        message: 'Night sweats + fatigue - malignancy/TB concern',
        severity: 'medium',
      },
    },
    {
      linkId: 'fat-thyroid',
      type: 'boolean',
      text: 'Known thyroid problems?',
      section: 'pmh',
      required: true,
      order: 50,
    },
  ],
  complaintClusters: ['fatigue', 'general'],
  specialtyTags: ['internal_medicine'],
  departmentTags: [],
  priority: 10,
  outputTemplates: {
    hpiTemplate: 'Fatigue: {{fat-duration}}, onset {{fat-onset}}. Sleep: {{fat-sleep}}.',
    rosTemplate:
      'PSYCH: Depressed mood {{fat-mood}}. GENERAL: Weight change {{fat-weight-change}}, fever {{fat-fever}}, night sweats {{fat-night-sweats}}. RESP: DOE {{fat-sob}}.',
    noteTemplate: '',
  },
  scoringThresholds: [],
};

export const dizzinessPack: IntakePack = {
  packId: 'complaint-dizziness-v1',
  version: '1.0.0',
  title: 'Dizziness Intake',
  description: 'Focused dizziness/vertigo history with central vs. peripheral differentiation',
  languages: ['en'],
  applicableContexts: {
    departments: ['*'],
    specialties: ['*'],
    visitTypes: ['*'],
    chiefComplaints: [
      'dizziness',
      'dizzy',
      'vertigo',
      'lightheaded',
      'lightheadedness',
      'room spinning',
    ],
  },
  requiredCoverage: ['hpi', 'ros'],
  items: [
    {
      linkId: 'diz-type',
      type: 'choice',
      text: 'Which best describes your dizziness?',
      section: 'hpi',
      required: true,
      order: 30,
      answerOption: [
        { value: 'spinning', display: 'Room spinning (vertigo)' },
        { value: 'lightheaded', display: 'Lightheaded/faint' },
        { value: 'unsteady', display: 'Unsteady/off-balance' },
        { value: 'vague', display: 'Hard to describe' },
      ],
    },
    {
      linkId: 'diz-positional',
      type: 'boolean',
      text: 'Does it happen when you change position (lying down, sitting up)?',
      section: 'hpi',
      required: true,
      order: 31,
    },
    {
      linkId: 'diz-duration-episode',
      type: 'choice',
      text: 'How long does an episode last?',
      section: 'hpi',
      required: true,
      order: 32,
      answerOption: [
        { value: 'seconds', display: 'Seconds' },
        { value: 'minutes', display: 'Minutes' },
        { value: 'hours', display: 'Hours' },
        { value: 'constant', display: 'Constant' },
      ],
    },
    {
      linkId: 'diz-hearing',
      type: 'boolean',
      text: 'Any hearing loss or ringing in ears?',
      section: 'ros',
      required: true,
      order: 40,
    },
    {
      linkId: 'diz-nausea',
      type: 'boolean',
      text: 'Nausea or vomiting?',
      section: 'ros',
      required: true,
      order: 41,
    },
    {
      linkId: 'diz-headache',
      type: 'boolean',
      text: 'Headache?',
      section: 'ros',
      required: true,
      order: 42,
    },
    {
      linkId: 'diz-double-vision',
      type: 'boolean',
      text: 'Double vision?',
      section: 'ros',
      required: true,
      order: 43,
      redFlag: {
        condition: 'true',
        message: 'Diplopia with vertigo - central (brainstem) concern',
        severity: 'high',
      },
    },
    {
      linkId: 'diz-weakness',
      type: 'boolean',
      text: 'Any weakness, numbness, or difficulty speaking?',
      section: 'ros',
      required: true,
      order: 44,
      redFlag: {
        condition: 'true',
        message: 'Focal neuro deficit + vertigo - stroke concern',
        severity: 'critical',
      },
    },
    {
      linkId: 'diz-gait',
      type: 'boolean',
      text: 'Difficulty walking?',
      section: 'ros',
      required: true,
      order: 45,
      redFlag: {
        condition: 'true',
        message: 'Gait ataxia with vertigo - cerebellar concern',
        severity: 'high',
      },
    },
  ],
  complaintClusters: ['dizziness', 'neurological'],
  specialtyTags: ['neurology', 'ent'],
  departmentTags: [],
  priority: 10,
  outputTemplates: {
    hpiTemplate:
      'Dizziness: {{diz-type}}, positional: {{diz-positional}}, episode duration: {{diz-duration-episode}}.',
    rosTemplate:
      'ENT: Hearing loss/tinnitus {{diz-hearing}}. GI: Nausea {{diz-nausea}}. NEURO: Headache {{diz-headache}}, diplopia {{diz-double-vision}}, focal deficits {{diz-weakness}}, gait {{diz-gait}}.',
    noteTemplate: '',
  },
  scoringThresholds: [],
};
