/**
 * Complaint Pack: Chest Pain
 * Covers ACS/cardiac differential, associated symptoms, cardiac risk factors
 */
import type { IntakePack } from '../types.js';

const pack: IntakePack = {
  packId: 'complaint-chest-pain-v1',
  version: '1.0.0',
  title: 'Chest Pain Intake',
  description: 'Focused chest pain history including cardiac risk factors and red flags',
  languages: ['en'],
  applicableContexts: {
    departments: ['*'],
    specialties: ['*'],
    visitTypes: ['*'],
    chiefComplaints: ['chest pain', 'chest pressure', 'chest tightness', 'angina'],
  },
  requiredCoverage: ['hpi', 'ros'],
  items: [
    {
      linkId: 'cp-location',
      type: 'choice',
      text: 'Where exactly is the pain?',
      section: 'hpi',
      required: true,
      order: 30,
      answerOption: [
        { value: 'substernal', display: 'Center of chest' },
        { value: 'left', display: 'Left side' },
        { value: 'right', display: 'Right side' },
        { value: 'diffuse', display: 'All over chest' },
        { value: 'epigastric', display: 'Upper stomach area' },
      ],
    },
    {
      linkId: 'cp-quality',
      type: 'choice',
      text: 'How would you describe the pain?',
      section: 'hpi',
      required: true,
      order: 31,
      answerOption: [
        { value: 'sharp', display: 'Sharp/stabbing' },
        { value: 'pressure', display: 'Pressure/squeezing' },
        { value: 'burning', display: 'Burning' },
        { value: 'aching', display: 'Dull ache' },
        { value: 'tearing', display: 'Tearing/ripping' },
      ],
    },
    {
      linkId: 'cp-radiation',
      type: 'open-choice',
      text: 'Does the pain spread anywhere?',
      section: 'hpi',
      required: true,
      order: 32,
      answerOption: [
        { value: 'none', display: 'Stays in one place' },
        { value: 'left_arm', display: 'Left arm' },
        { value: 'jaw', display: 'Jaw or neck' },
        { value: 'back', display: 'Back' },
        { value: 'right_arm', display: 'Right arm' },
      ],
    },
    {
      linkId: 'cp-onset',
      type: 'choice',
      text: 'How did the pain start?',
      section: 'hpi',
      required: true,
      order: 33,
      answerOption: [
        { value: 'sudden', display: 'Suddenly' },
        { value: 'gradual', display: 'Gradually' },
        { value: 'with_exertion', display: 'During activity/exertion' },
        { value: 'at_rest', display: 'At rest' },
      ],
    },
    {
      linkId: 'cp-exertion',
      type: 'boolean',
      text: 'Does the pain get worse with physical activity?',
      section: 'hpi',
      required: true,
      order: 34,
      redFlag: {
        condition: 'true',
        message: 'Exertional chest pain - possible ACS',
        severity: 'high',
      },
    },
    {
      linkId: 'cp-rest-relief',
      type: 'boolean',
      text: 'Does the pain improve with rest?',
      section: 'hpi',
      required: true,
      order: 35,
    },
    {
      linkId: 'cp-nitro',
      type: 'boolean',
      text: 'Do you take nitroglycerin? If yes, does it help?',
      section: 'hpi',
      required: false,
      order: 36,
    },
    {
      linkId: 'cp-sob',
      type: 'boolean',
      text: 'Are you experiencing shortness of breath?',
      section: 'ros',
      required: true,
      order: 40,
      redFlag: {
        condition: 'true',
        message: 'SOB with chest pain - cardiac/PE concern',
        severity: 'high',
      },
    },
    {
      linkId: 'cp-diaphoresis',
      type: 'boolean',
      text: 'Are you sweating more than usual?',
      section: 'ros',
      required: true,
      order: 41,
      redFlag: {
        condition: 'true',
        message: 'Diaphoresis with chest pain - possible ACS',
        severity: 'high',
      },
    },
    {
      linkId: 'cp-nausea',
      type: 'boolean',
      text: 'Do you feel nauseous or have you vomited?',
      section: 'ros',
      required: true,
      order: 42,
    },
    {
      linkId: 'cp-palpitations',
      type: 'boolean',
      text: 'Do you feel your heart racing or skipping beats?',
      section: 'ros',
      required: true,
      order: 43,
    },
    {
      linkId: 'cp-dizziness',
      type: 'boolean',
      text: 'Do you feel dizzy or lightheaded?',
      section: 'ros',
      required: true,
      order: 44,
      redFlag: { condition: 'true', message: 'Syncope/presyncope with CP', severity: 'medium' },
    },
    {
      linkId: 'cp-hx-cad',
      type: 'boolean',
      text: 'History of heart disease, heart attack, or stent?',
      section: 'pmh',
      required: true,
      order: 50,
      redFlag: {
        condition: 'true',
        message: 'Known CAD - higher pretest probability',
        severity: 'medium',
      },
    },
    {
      linkId: 'cp-hx-dm',
      type: 'boolean',
      text: 'Do you have diabetes?',
      section: 'pmh',
      required: true,
      order: 51,
    },
    {
      linkId: 'cp-hx-htn',
      type: 'boolean',
      text: 'Do you have high blood pressure?',
      section: 'pmh',
      required: true,
      order: 52,
    },
    {
      linkId: 'cp-hx-smoking',
      type: 'boolean',
      text: 'Do you currently smoke or have a history of smoking?',
      section: 'pmh',
      required: true,
      order: 53,
    },
    {
      linkId: 'cp-hx-family',
      type: 'boolean',
      text: 'Family history of heart disease before age 55 (male) or 65 (female)?',
      section: 'family_hx',
      required: true,
      order: 54,
    },
  ],
  complaintClusters: ['chest_pain', 'cardiac', 'acs'],
  specialtyTags: ['cardiology', 'emergency'],
  departmentTags: ['ed', 'urgent_care'],
  priority: 10,
  outputTemplates: {
    hpiTemplate:
      'Chest pain: {{cp-quality}} in character, {{cp-location}} location. Onset: {{cp-onset}}. Radiation: {{cp-radiation}}. Exertional: {{cp-exertion}}. Rest relief: {{cp-rest-relief}}.',
    rosTemplate:
      'CV: Palpitations {{cp-palpitations}}. RESP: SOB {{cp-sob}}. GI: Nausea {{cp-nausea}}. NEURO: Dizziness {{cp-dizziness}}. GENERAL: Diaphoresis {{cp-diaphoresis}}.',
    noteTemplate: '',
  },
  scoringThresholds: [],
};

export default pack;
