/**
 * Auto-generated by Phase 108 -- Phase Audit Harness
 * Group: phases-131-to-132
 * Phases: 131, 131, 132, 132
 *
 * DO NOT EDIT MANUALLY -- regenerate with:
 *   node scripts/generate-phase-qa.mjs
 */

import { test, expect } from "@playwright/test";
import { readdirSync } from "node:fs";
import { join, resolve } from "node:path";

const API = process.env.API_URL ?? "http://localhost:3001";
const ROOT = resolve(__dirname, "..", "..", "..", "..");

test.describe("Phase 131: IMPLEMENT: Scheduling SD Depth (VistA-First Lifecycle)", () => {
  test("API routes respond (no 500)", async ({ request }) => {
    const r0 = await request.get(`${API}/scheduling/appointments/cprs`);
    expect(r0.status(), "/scheduling/appointments/cprs not 500").not.toBe(500);
    const r1 = await request.get(`${API}/scheduling/lifecycle/transition`);
    expect(r1.status(), "/scheduling/lifecycle/transition not 500").not.toBe(500);
    const r2 = await request.get(`${API}/scheduling/lifecycle?patientDfn=X`);
    expect(r2.status(), "/scheduling/lifecycle?patientDfn=X not 500").not.toBe(500);
    const r3 = await request.get(`${API}/scheduling/posture`);
    expect(r3.status(), "/scheduling/posture not 500").not.toBe(500);
    const r4 = await request.get(`${API}/scheduling/reference-data`);
    expect(r4.status(), "/scheduling/reference-data not 500").not.toBe(500);
  });

  test("UI component files exist on disk", async () => {
    const componentNames = ["page.tsx"];
    function findFile(dir: string, name: string, depth = 0): boolean {
      if (depth > 6) return false;
      try {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          if (entry.isFile() && entry.name === name) return true;
          if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules") {
            if (findFile(join(dir, entry.name), name, depth + 1)) return true;
          }
        }
      } catch { /* permission error or similar */ }
      return false;
    }
    let found = 0;
    for (const name of componentNames) {
      if (findFile(join(ROOT, "apps"), name)) found++;
    }
    expect(found, `Expected >= 1 of 1 UI files for Phase 131`).toBeGreaterThan(0);
  });

  test("integration-pending responses are compliant", async ({ request }) => {
    // Spot-check first accessible route for pending compliance
    const res = await request.get(`${API}/scheduling/appointments/cprs`);
    expect(res.status(), "/scheduling/appointments/cprs should respond").toBeDefined();
    if (res.status() === 200) {
      const body = await res.json().catch(() => null);
      if (body && body.status === "integration-pending") {
        expect(body, "integration-pending must have nextSteps").toHaveProperty("nextSteps");
      }
    }
  });
});

test.describe("Phase 131: 132 VERIFY", () => {
  test("API routes respond (no 500)", async ({ request }) => {
    const r0 = await request.get(`${API}/scheduling/appointments/cprs?dfn=3`);
    expect(r0.status(), "/scheduling/appointments/cprs?dfn=3 not 500").not.toBe(500);
    const r1 = await request.get(`${API}/scheduling/health`);
    expect(r1.status(), "/scheduling/health not 500").not.toBe(500);
    const r2 = await request.get(`${API}/scheduling/lifecycle`);
    expect(r2.status(), "/scheduling/lifecycle not 500").not.toBe(500);
    const r3 = await request.get(`${API}/scheduling/lifecycle/transition`);
    expect(r3.status(), "/scheduling/lifecycle/transition not 500").not.toBe(500);
    const r4 = await request.get(`${API}/scheduling/posture`);
    expect(r4.status(), "/scheduling/posture not 500").not.toBe(500);
  });

  test("UI component files exist on disk", async () => {
    const componentNames = ["AIAssistPanel.tsx","AcknowledgeLabDialog.tsx","AddAllergyDialog.tsx","AddMedicationDialog.tsx","AddProblemDialog.tsx","AddVitalDialog.tsx","CreateNoteDialog.tsx","EditProblemDialog.tsx","ImagingPanel.tsx","IntakePanel.tsx"];
    function findFile(dir: string, name: string, depth = 0): boolean {
      if (depth > 6) return false;
      try {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          if (entry.isFile() && entry.name === name) return true;
          if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules") {
            if (findFile(join(dir, entry.name), name, depth + 1)) return true;
          }
        }
      } catch { /* permission error or similar */ }
      return false;
    }
    let found = 0;
    for (const name of componentNames) {
      if (findFile(join(ROOT, "apps"), name)) found++;
    }
    expect(found, `Expected >= 1 of 17 UI files for Phase 131`).toBeGreaterThan(0);
  });

  test("integration-pending responses are compliant", async ({ request }) => {
    // Spot-check first accessible route for pending compliance
    const res = await request.get(`${API}/scheduling/appointments/cprs?dfn=3`);
    expect(res.status(), "/scheduling/appointments/cprs?dfn=3 should respond").toBeDefined();
    if (res.status() === 200) {
      const body = await res.json().catch(() => null);
      if (body && body.status === "integration-pending") {
        expect(body, "integration-pending must have nextSteps").toHaveProperty("nextSteps");
      }
    }
  });
});

test.describe("Phase 132: CSRF Synchronizer Token Migration", () => {
  test("API routes respond (no 500)", async ({ request }) => {
    const r0 = await request.get(`${API}/auth/csrf-token`);
    expect(r0.status(), "/auth/csrf-token not 500").not.toBe(500);
    const r1 = await request.get(`${API}/scheduling/lifecycle/transition`);
    expect(r1.status(), "/scheduling/lifecycle/transition not 500").not.toBe(500);
  });

  test("UI component files exist on disk", async () => {
    const componentNames = ["page.tsx","session-context.tsx"];
    function findFile(dir: string, name: string, depth = 0): boolean {
      if (depth > 6) return false;
      try {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          if (entry.isFile() && entry.name === name) return true;
          if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules") {
            if (findFile(join(dir, entry.name), name, depth + 1)) return true;
          }
        }
      } catch { /* permission error or similar */ }
      return false;
    }
    let found = 0;
    for (const name of componentNames) {
      if (findFile(join(ROOT, "apps"), name)) found++;
    }
    expect(found, `Expected >= 1 of 2 UI files for Phase 132`).toBeGreaterThan(0);
  });

  test("integration-pending responses are compliant", async ({ request }) => {
    // Spot-check first accessible route for pending compliance
    const res = await request.get(`${API}/auth/csrf-token`);
    expect(res.status(), "/auth/csrf-token should respond").toBeDefined();
    if (res.status() === 200) {
      const body = await res.json().catch(() => null);
      if (body && body.status === "integration-pending") {
        expect(body, "integration-pending must have nextSteps").toHaveProperty("nextSteps");
      }
    }
  });
});

test.describe("Phase 132: I18N FOUNDATION (MULTILINGUAL UI + INTAKE SCHEMA)", () => {
  test("API routes respond (no 500)", async ({ request }) => {
    const r0 = await request.get(`${API}/admin/intake/question-schema`);
    expect(r0.status(), "/admin/intake/question-schema not 500").not.toBe(500);
    const r1 = await request.get(`${API}/auth/locale`);
    expect(r1.status(), "/auth/locale not 500").not.toBe(500);
    const r2 = await request.get(`${API}/intake/question-schema?locale=en`);
    expect(r2.status(), "/intake/question-schema?locale=en not 500").not.toBe(500);
  });

  test("UI component files exist on disk", async () => {
    const componentNames = ["LanguageSwitcher.tsx","layout.tsx","page.tsx"];
    function findFile(dir: string, name: string, depth = 0): boolean {
      if (depth > 6) return false;
      try {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          if (entry.isFile() && entry.name === name) return true;
          if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules") {
            if (findFile(join(dir, entry.name), name, depth + 1)) return true;
          }
        }
      } catch { /* permission error or similar */ }
      return false;
    }
    let found = 0;
    for (const name of componentNames) {
      if (findFile(join(ROOT, "apps"), name)) found++;
    }
    expect(found, `Expected >= 1 of 3 UI files for Phase 132`).toBeGreaterThan(0);
  });

  test("integration-pending responses are compliant", async ({ request }) => {
    // Spot-check first accessible route for pending compliance
    const res = await request.get(`${API}/admin/intake/question-schema`);
    expect(res.status(), "/admin/intake/question-schema should respond").toBeDefined();
    if (res.status() === 200) {
      const body = await res.json().catch(() => null);
      if (body && body.status === "integration-pending") {
        expect(body, "integration-pending must have nextSteps").toHaveProperty("nextSteps");
      }
    }
  });
});
