/**
 * Static menu data derived from design/contracts/cprs/v1/menus.json (fFrame.dfm mnuFrame).
 * Adapted for web: removed VA-specific items, cleaned captions, mapped actions.
 */

import type { MenuItem } from '@/lib/chart-types';

/**
 * The main menu bar items for the chart shell.
 * Derived from the CPRS fFrame main menu, with VA-specific items removed
 * and captions cleaned of Delphi '&' accelerator markers.
 */
export const MAIN_MENU: MenuItem[] = [
  {
    name: 'mnuFile',
    caption: 'File',
    isSeparator: false,
    shortcut: null,
    tag: null,
    onClick: null,
    visible: true,
    enabled: true,
    children: [
      {
        name: 'mnuFileOpen',
        caption: 'Select New Patient...',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: 'selectPatient',
        visible: true,
        enabled: true,
        children: [],
      },
      {
        name: 'mnuFileRefresh',
        caption: 'Refresh Patient Information',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: 'refresh',
        visible: true,
        enabled: true,
        children: [],
      },
      {
        name: 'sep1',
        caption: '-',
        isSeparator: true,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [],
      },
      {
        name: 'mnuFileEncounter',
        caption: 'Update Provider / Location...',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'mnuFileReview',
        caption: 'Review/Sign Changes...',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'sep2',
        caption: '-',
        isSeparator: true,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [],
      },
      {
        name: 'mnuFilePrint',
        caption: 'Print...',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'mnuFileExit',
        caption: 'Exit',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: 'exit',
        visible: true,
        enabled: true,
        children: [],
      },
    ],
  },
  {
    name: 'mnuEdit',
    caption: 'Edit',
    isSeparator: false,
    shortcut: null,
    tag: null,
    onClick: null,
    visible: true,
    enabled: true,
    children: [
      {
        name: 'mnuEditUndo',
        caption: 'Undo',
        isSeparator: false,
        shortcut: 'Ctrl+Z',
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'mnuEditRedo',
        caption: 'Redo',
        isSeparator: false,
        shortcut: 'Ctrl+Y',
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'sep3',
        caption: '-',
        isSeparator: true,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [],
      },
      {
        name: 'mnuEditCut',
        caption: 'Cut',
        isSeparator: false,
        shortcut: 'Ctrl+X',
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'mnuEditCopy',
        caption: 'Copy',
        isSeparator: false,
        shortcut: 'Ctrl+C',
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'mnuEditPaste',
        caption: 'Paste',
        isSeparator: false,
        shortcut: 'Ctrl+V',
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'sep4',
        caption: '-',
        isSeparator: true,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [],
      },
      {
        name: 'mnuEditPref',
        caption: 'Preferences',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [
          {
            name: 'mnu8pt',
            caption: '8 pt',
            isSeparator: false,
            shortcut: null,
            tag: 8,
            onClick: 'fontSize',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnu10pt',
            caption: '10 pt',
            isSeparator: false,
            shortcut: null,
            tag: 10,
            onClick: 'fontSize',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnu12pt',
            caption: '12 pt',
            isSeparator: false,
            shortcut: null,
            tag: 12,
            onClick: 'fontSize',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnu14pt',
            caption: '14 pt',
            isSeparator: false,
            shortcut: null,
            tag: 14,
            onClick: 'fontSize',
            visible: true,
            enabled: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    name: 'mnuView',
    caption: 'View',
    isSeparator: false,
    shortcut: null,
    tag: null,
    onClick: null,
    visible: true,
    enabled: true,
    children: [
      {
        name: 'mnuViewChart',
        caption: 'Chart Tab',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [
          {
            name: 'mnuChartCover',
            caption: 'Cover Sheet',
            isSeparator: false,
            shortcut: 'Ctrl+S',
            tag: 1,
            onClick: 'tab:cover',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartProbs',
            caption: 'Problem List',
            isSeparator: false,
            shortcut: 'Ctrl+P',
            tag: 2,
            onClick: 'tab:problems',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartMeds',
            caption: 'Medications',
            isSeparator: false,
            shortcut: 'Ctrl+M',
            tag: 3,
            onClick: 'tab:meds',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartOrders',
            caption: 'Orders',
            isSeparator: false,
            shortcut: 'Ctrl+O',
            tag: 4,
            onClick: 'tab:orders',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartNotes',
            caption: 'Progress Notes',
            isSeparator: false,
            shortcut: 'Ctrl+N',
            tag: 6,
            onClick: 'tab:notes',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartCslts',
            caption: 'Consults',
            isSeparator: false,
            shortcut: 'Ctrl+T',
            tag: 7,
            onClick: 'tab:consults',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartSurgery',
            caption: 'Surgery',
            isSeparator: false,
            shortcut: 'Ctrl+U',
            tag: 11,
            onClick: 'tab:surgery',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartDCSumm',
            caption: 'Discharge Summaries',
            isSeparator: false,
            shortcut: 'Ctrl+D',
            tag: 8,
            onClick: 'tab:dcsumm',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartLabs',
            caption: 'Laboratory',
            isSeparator: false,
            shortcut: 'Ctrl+L',
            tag: 9,
            onClick: 'tab:labs',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuChartReports',
            caption: 'Reports',
            isSeparator: false,
            shortcut: 'Ctrl+R',
            tag: 10,
            onClick: 'tab:reports',
            visible: true,
            enabled: true,
            children: [],
          },
        ],
      },
      {
        name: 'mnuViewInfo',
        caption: 'Information',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [
          {
            name: 'mnuViewDemo',
            caption: 'Demographics...',
            isSeparator: false,
            shortcut: null,
            tag: 1,
            onClick: 'info:demographics',
            visible: true,
            enabled: true,
            children: [],
          },
          {
            name: 'mnuViewVisits',
            caption: 'Visits/Provider...',
            isSeparator: false,
            shortcut: null,
            tag: 2,
            onClick: null,
            visible: true,
            enabled: false,
            children: [],
          },
          {
            name: 'mnuInsurance',
            caption: 'Insurance...',
            isSeparator: false,
            shortcut: null,
            tag: 5,
            onClick: null,
            visible: true,
            enabled: false,
            children: [],
          },
          {
            name: 'mnuViewFlags',
            caption: 'Flags...',
            isSeparator: false,
            shortcut: null,
            tag: 6,
            onClick: null,
            visible: true,
            enabled: false,
            children: [],
          },
          {
            name: 'mnuViewReminders',
            caption: 'Reminders...',
            isSeparator: false,
            shortcut: null,
            tag: 8,
            onClick: null,
            visible: true,
            enabled: false,
            children: [],
          },
        ],
      },
    ],
  },
  {
    name: 'mnuTools',
    caption: 'Tools',
    isSeparator: false,
    shortcut: null,
    tag: null,
    onClick: null,
    visible: true,
    enabled: true,
    children: [
      {
        name: 'mnuToolsGraphing',
        caption: 'Graphing...',
        isSeparator: false,
        shortcut: 'Ctrl+G',
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'mnuToolsOptions',
        caption: 'Options...',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
    ],
  },
  {
    name: 'mnuHelp',
    caption: 'Help',
    isSeparator: false,
    shortcut: null,
    tag: null,
    onClick: null,
    visible: true,
    enabled: true,
    children: [
      {
        name: 'mnuHelpContents',
        caption: 'Contents',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: false,
        children: [],
      },
      {
        name: 'sep5',
        caption: '-',
        isSeparator: true,
        shortcut: null,
        tag: null,
        onClick: null,
        visible: true,
        enabled: true,
        children: [],
      },
      {
        name: 'mnuHelpAbout',
        caption: 'About',
        isSeparator: false,
        shortcut: null,
        tag: null,
        onClick: 'about',
        visible: true,
        enabled: true,
        children: [],
      },
    ],
  },
];
